<a href="https://colab.research.google.com/github/yeahjinjeong/2023-GraduationProject-Cafe/blob/main/%EB%A9%94%EB%89%B4_%EC%9E%91%EC%97%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#/content/drive/MyDrive/Colab/cafe/cafe0.csv

In [ ]:
import pandas as pd

In [ ]:
for i in range(0, 780):
  df = pd.read_csv(f"/content/drive/MyDrive/Colab/cafe/cafe{i}.csv", encoding="utf-8", header = 0)
  if len(df) < 35:
    print(f"{i}번째 카페 :")
    print(len(df))

8번째 카페 :
32
102번째 카페 :
34
126번째 카페 :
34
365번째 카페 :
31
482번째 카페 :
30
527번째 카페 :
33

In [ ]:
review_count = pd.read_csv("/content/drive/MyDrive/Colab/최종파일모음/review_count_최종_35개부터.csv", encoding="utf-8", header = 0)

In [ ]:
review_count

,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count
0,1.0,1.275361e+09,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251
1,2.0,3.687750e+07,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48
2,3.0,3.756884e+07,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115
3,5.0,1.149650e+09,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237
4,6.0,3.723620e+07,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130
...,...,...,...,...,...,...,...,...
784,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN
785,NaN,NaN,NaN,45,NaN,NaN,NaN,NaN
786,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN
787,NaN,NaN,NaN,234,NaN,NaN,NaN,NaN
788,NaN,NaN,NaN,3880,NaN,NaN,NaN,NaN

In [ ]:
review_count['data-cid'].astype(int)

IntCastingNaNError: ignored

In [ ]:
lnglat = pd.read_csv("/content/drive/MyDrive/Colab/최종파일모음/review_latlng.csv", encoding="utf-8", header = 0)

In [ ]:
lnglat

       data-cid           카페명      lng(x)     lat(y)
0      data-cid           카페명         NaN        NaN
1    1275361497          르플뢰브  126.945801  37.535276
2      36877505   커피공장103 이촌점  126.954935  37.526261
3      37568842      테이블스 용산점  126.955187  37.532618
4    1149649924   이디야커피 용산원효점  126.951642  37.532505
..          ...           ...         ...        ...
776    11690056     파리바게뜨 한남점  127.006148  37.533367
777    11782468    배스킨라빈스 한남점  127.005521  37.533197
778    31363849   빨라쪼델프레도 HQ점  126.973638  37.540711
779  1119858083  베이커스코드 숙대입구점  126.971670  37.542075
780    11492935     던킨 서울역2호점  126.970484  37.549118

[781 rows x 4 columns]

In [ ]:
review

,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count
0,1,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251
1,2,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48
2,3,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115
3,5,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237
4,6,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130
...,...,...,...,...,...,...,...,...
775,940,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819
776,941,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371
777,942,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164
778,943,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76
779,945,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179"

In [ ]:
review['data-cid'].astype(object)

0      1275361497
1        36877505
2        37568842
3      1149649924
4        37236205
          ...
775      11690056
776      11782468
777      31363849
778    1119858083
779      11492935
Name: data-cid, Length: 780, dtype: object

In [ ]:
lnglat['data-cid'].astype(object)

1      1275361497
2        36877505
3        37568842
4      1149649924
5        37236205
          ...
776      11690056
777      11782468
778      31363849
779    1119858083
780      11492935
Name: data-cid, Length: 780, dtype: object

In [ ]:
lnglat.drop(0 , inplace=True)

In [ ]:
reviewlnglat = pd.merge(review,lnglat, how='outer',on='data-cid')
reviewlnglat

ValueError: ignored

In [ ]:
class1 = pd.read_csv("/content/drive/MyDrive/Colab/최종파일모음/classify0-271.csv", encoding="utf-8", header = 0)
class2 = pd.read_csv("/content/drive/MyDrive/Colab/최종파일모음/classify272-396.csv", encoding="utf-8", header = 0)
class3 = pd.read_csv("/content/drive/MyDrive/Colab/최종파일모음/classify2_397-779.csv", encoding="utf-8", header = 0)

In [ ]:
class_ = pd.concat([class1, class2, class3], axis=0)

In [ ]:
class_

,no.,[0]브런치/식사,[1]커피,[2]차,[3]디저트,[4]비건,[5]공부/개인작업/업무,[6]팀플/회의/스터디,[7]대모임,[8]대화/수다,[9]아이,[10]할아버지/할머니,[11]파티,[12]휴식,[13]sns/핫플,[14]테마
0,0,95,4,0,3,0,15,12,22,16,12,-13,24,205,218,0
1,1,0,1,1,0,0,4,1,-14,2,0,5,1,4,3,0
2,2,13,4,2,0,0,1,0,-4,1,1,1,2,-2,8,0
3,3,1,0,1,0,0,13,5,-38,12,7,15,2,10,1,0
4,4,1,0,0,5,0,9,4,3,8,9,13,11,25,21,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,775,19,0,0,1,0,5,5,0,3,8,10,8,0,3,0
379,776,0,0,0,1,0,2,3,-4,2,8,3,9,-2,10,0
380,777,1,0,0,0,0,7,-2,-1,1,26,0,2,-4,3,0
381,778,17,0,0,2,0,3,1,-3,1,4,5,5,2,4,0
382,779,11,3,0,1,0,2,21,-24,5,7,6,8,8,12,0

In [ ]:
class_.to_csv('/content/drive/MyDrive/Colab/최종파일모음/classify_full.csv')

In [ ]:
basic = pd.read_csv("/content/drive/MyDrive/Colab/최종파일모음/0기본정보.csv", encoding="utf-8", header = 0)

In [ ]:
basic

,Unnamed: 0,name,num,inform
0,0,르플뢰브,0,서울 용산구 원효로1길 20 르플뢰브5마포역 4번 출구에서537m
1,1,르플뢰브,1,마포역 근처일 시: 지하철 도보시 마포역 4번 출구로 나와서 왼쪽으로 백다방을 지나...
2,2,르플뢰브,2,영업 중20:50에 라스트오더20시 50분에 라스트오더펼쳐보기매달 3번째 화요일 정...
3,3,르플뢰브,3,0507-1362-5462안내복사
4,4,르플뢰브,4,"단체석, 무선 인터넷, 남/녀 화장실 구분"
...,...,...,...,...
5663,5663,던킨 서울역2호점,4,"포장, 남/녀 화장실 구분"
5664,5664,던킨 서울역2호점,5,http://www.dunkindonuts.co.kr/
5665,5665,던킨 서울역2호점,6,원래 Dunkin이라는 말은 우리말로 적시다 즉 과자나 빵을 적셔 먹는다는 의미입니...
5666,5666,던킨 서울역2호점,7,식약처 인증 위생등급 매우우수 음식점접기유효기간: 2022.09.16~2024.09...
5667,5667,던킨 서울역2호점,8,정보 수정 제안하기

In [ ]:
basic['num']

0       0
1       1
2       2
3       3
4       4
       ..
5663    4
5664    5
5665    6
5666    7
5667    8
Name: num, Length: 5668, dtype: int64

In [ ]:
cafe = []
text = ""
for i in range(len(basic)):
  if basic['num'][i] != 0:
    text += basic['inform'][i] + "\n"
  else:
    cafe.append(text)
    text = ""

In [ ]:
df = pd.DataFrame(cafe,columns=['cafe'])

In [ ]:
df.to_csv('/content/drive/MyDrive/Colab/최종파일모음/1기본정보뭉침.csv')

In [ ]:
df['index'] = df['index']-1

KeyError: ignored

In [ ]:
df = df.drop(['no'], axis = 1)

In [ ]:
for i in range(0, 780):
  df['no'][i] = i

<ipython-input-56-65553e5f3906>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['no'][i] = i
<ipython-input-56-65553e5f3906>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['no'][i] = i

In [ ]:
df

                                                  cafe
1    마포역 근처일 시: 지하철 도보시 마포역 4번 출구로 나와서 왼쪽으로 백다방을 지나...
2    이촌2동 주민센터 옆\n삼보아파트 2층영업 종료10:30에 영업 시작10시 30분에...
3    자가용 이용시: 강변북로-->원효대교 북단-->전자상가방향에서 유턴\r\n버스 이용...
4    영업 중21:20에 라스트오더21시 20분에 라스트오더펼쳐보기06/03-06/11 ...
5    영업 중21:50에 라스트오더21시 50분에 라스트오더펼쳐보기02-706-4036복...
..                                                 ...
775  영업 중23:00에 영업 종료23시 0분에 영업 종료펼쳐보기02-749-8757복사...
776  영업 중24:00에 영업 종료0시 0분에 영업 종료펼쳐보기02-798-0012복사가...
777  영업 중23:00에 영업 종료23시 0분에 영업 종료펼쳐보기02-749-3868복사...
778  영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기02-709-7820복...
779  영업 종료내일 휴무내일 휴무펼쳐보기02-717-9010복사가격표 사진을 올려주세요....

[779 rows x 1 columns]

In [ ]:
cafe

['',
 "마포역 근처일 시: 지하철 도보시 마포역 4번 출구로 나와서 왼쪽으로 백다방을 지나서 오른쪽 골목으로 직진하고, 언덕을 따라 올라 오시다 보면 왼편에 저희 매장이 있습니다.\n버스 사용 시: 청암자이아파트역(청암동강변삼성아파트방면)에서 하차하여 직진하여 현대주유소 옆의 언덕을 올라 우회전하여 50m만 걸으시면 저희 매장이 있습니다.\n\n주차는 매장 앞 선착순으로 한 자리 이용 가능합니다. 이외에는 가까운 공영주차장을 이용해주시면 감사드리겠습니다 !영업 중20:50에 라스트오더20시 50분에 라스트오더펼쳐보기매달 3번째 화요일 정기 휴무 - 23년 1월 24일 화요일 휴무입니다접기0507-1362-5462안내복사단체석, 무선 인터넷, 남/녀 화장실 구분https://www.instagram.com/cafe_lefleuveLe Fleuve는 '강'이라는 의미를 가진 불어입니다.\n\n모던하고 세련된 분위기의 다이닝카페인 르플뢰브에서 소중한 인연과 캐주얼 다이닝을 즐기고, 도심속에서 찾기 힘든 여유로움과 아늑한 분위기를 만나보세요.\n\n계절별로 다채롭게 아름다운 한강뷰와 여유로운 분위기의 매장에서 다양한 모임을 하실 수 있습니다.\n\n르플뢰브는 맛있고 다양한 음식, 디저트, 커피, 와인을 한 자리에서 즐길 수 있는 공간입니다.\n\n*촬영, 대관, 행사 문의는 매장으로 연락주세요 !정보 수정 제안하기",
 '이촌2동 주민센터 옆\n삼보아파트 2층영업 종료10:30에 영업 시작10시 30분에 영업 시작펼쳐보기02-719-1103복사제로페이포장, 무선 인터넷https://smartstore.naver.com/coffeefactory1032007년에 시작한 헤이리에 있는 커피공장103의 분점입니다.\n갓 볶은 신선한 원두를 구입하실 수 있습니다.정보 수정 제안하기',
 '자가용 이용시: 강변북로-->원효대교 북단-->전자상가방향에서 유턴\r\n버스 이용시: 505(삼구빌딩 하차),7016,2016번(풍전아파트)에서 50미터 거리영업 중21:30에 라스트오더21시 30분에 라스트오더펼쳐보기070-4417-1478복사제로페이단체석, 주차, 포장, 배달, 무선 인터넷, 반려동물 동반, 남/녀 화장실 구분https://www.instagram.com/tablesys/모두용산 원효로3가에 위치한 베이커리카페 테이블스입니다.\n매장 내에서 직접 베이커가 굽는 건강한 빵집입니다. \n레터링케이크, 당근케이크는 예약주문 받습니다.정보 수정 제안하기',
 '영업 중21:20에 라스트오더21시 20분에 라스트오더펼쳐보기06/03-06/11  휴무 - 베이커리 마감 : 영업종료 30분전접기휴무일06/03-06/1102-717-2229복사제로페이, 네이버페이포장http://www.ediya.com/블로그인스타그램페이스북유튜브Always beside you, EDIYA COFFEE\n일상 속 모두에게 커피를 통한 휴식과 영감을 제공하는 이디야커피는,\n대한민국의 커피 문화를 만들어가는 가장 가까운 안식처입니다.식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.09.03~2024.09.022022년 9월 3일~2024년 9월 2일정보 수정 제안하기',
 '영업 중21:50에 라스트오더21시 50분에 라스트오더펼쳐보기02-706-4036복사제로페이단체석, 주차, 포장, 예약, 무선 인터넷, 반려동물 동반, 남/녀 화장실 구분http://www.instagram.com/cafelodge/정보 수정 제안하기',
 '용산구 강변북로 타고 쭉오시다가 전자상가쪽으로 빠져서 산호아파트 건너편으로 들어오시면 바로 보입니다\n\n- 여의도 5번출구에서 262타고 원효2동산호아파트에서 하차\n- 마포역 7016, 마포01 번타고 원효2동주민센타,원효2동산호아파트에서 하차영업 종료내일 휴무내일 휴무펼쳐보기0507-1481-3058안내복사제로페이포장, 배달, 예약, 무선 인터넷, 반려동물 동반, 남/녀 화장실 구분http://www.instagram.com/cafe___root인스타그램용산 원효로 샌드위치맛집으로 알려진 카페!\n시그니처 음료와 샌드위치 맛집인 카페!\n사장님들이 직접 새벽시장에서 공수해오는 싱싱한 야채들로 재료 준비 합니다 믿고 드세요\n핫하고 나름 분위기 있는 카페 입니다정보 수정 제안하기',
 '영업 종료08:00에 영업 시작8시 0분에 영업 시작펼쳐보기0507-1433-3373안내복사단체석, 포장, 남/녀 화장실 구분천연 발효 효모 베이커리\n맛있고 건강한 빵집 수정빵 입니다.',
 '마포역 4번출구영업 종료12:00에 영업 시작12시 0분에 영업 시작펼쳐보기05/27  부처님 오신 날 휴무 - 근로자의 날 휴무입니다접기휴무일05/27 부처님 오신 날0507-1320-8223안내복사네이버페이단체석, 포장, 무선 인터넷, 반려동물 동반, 남/녀 화장실 구분, 장애인 편의시설산천동 휘낭시에가 맛있는 머무르기 좋은 카페',
 '영업 중21:00에 라스트오더21시 0분에 라스트오더펼쳐보기010-8316-9953복사단체석, 주차, 포장, 무선 인터넷, 반려동물 동반신창동 로스터리카페 나무 입니다!\n\n햇볕이 잘 드는 테라스와 편한 좌석이 있으니 잠시 쉬고 싶다면 저희 카페를 방문해주세요:)\n\n작은 공간이 마련되어 있으니 편하게 수다 떨거나 회의할 곳이 필요하다면 저희 카페를 방문해주세요:)\n\n낮엔 나무 인테리어로 따뜻한 공간으로,\n밤엔 멋진 조명과 캔들로 분위기 있는 공간이 됩니다!\n\n- 콘센트가 마련되어 있어 노트북 작업하기 좋습니다.\n- 귀여운 반려동물과 함께 오셔도 좋습니다.\n- 주차는 잠깐 대는 정도는 괜찮습니다.',
 '버스0017승차, 신창제일교회 하차 후 , 바로 앞 골목 도보50m\n(세방아파트후문)영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기접기휴무일05/24-05/250506-807-5951복사지역화폐(모바일), 제로페이포장, 무선 인터넷https://www.instagram.com/ssongs_dessert쏭스디저트카페는 가정식으로 건강과 맛을 위해서 100% 직접 만드는 수제 핸드메이드 카페 입니다.\n커피는원두는 이미 검증된 알레그리아 (파트너 쏭스디저트 카페) 원두를 사용하고, 딸기/청귤/자몽/생강/레몬등 100% 직접 담근 수제청을 사용 합니다.',
 '용산역에서 노량진역 방향으로 한강대교 중앙에 노들섬이 있습니다. 노들섬의 버스정류장에서 20여 미터 진행 하시면 주차장 입구로 들어올수 있어요. 들어와서 우측편에 바로 있습니다.영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기0507-1339-8967안내복사지역화폐(지류,카드,모바일), 제로페이, 네이버페이단체석, 주차, 포장, 배달, 무선 인터넷, 남/녀 화장실 구분https://www.instagram.com/cafevoi저희 바캉스온아일랜드카페는 노들섬에 바캉스를 온것같은 휴식을 제공하자는 컨셉으로 탄생한 공간입니다.\n 직접만든 다양한 수제과일청들을 이용한 라떼와 에이드가 인기메뉴구요. 정교하게 블랜딩되 최상급 로스팅 커피는 당근 맛나답니다^^\n그밖에 다양한 수제 베이커리를 만나보실수 있어 많은분들께서 찾아주신답니다.\n 음악으로는 최상의 소리를 전해주는 진공관앰프와 원음을 전해주는 웨스턴미니스터스피커에서 흘러 나오는 아름다운 음악도 다른곳에서 경험하기 힘든 편안함을 제공합니다.\n바캉스온아일랜드에서 노들섬에서의 휴식을 즐기세요.\n감사합니다.정보 수정 제안하기',
 '영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기02-749-5489복사제로페이생방송투데이 2670회,\xa020.10.05.2020년 10월 5일\xa0락사https://askcafenoodle.modoo.at정보 수정 제안하기',
 '1호선 용산역,  4호선 신용산역 10분거리오늘 휴무매주 토요일 휴무매주 토요일 휴무펼쳐보기05/27  부처님 오신 날 휴무접기휴무일05/27 부처님 오신 날0507-1440-8887안내복사제로페이단체석, 주차, 포장, 예약, 무선 인터넷, 남/녀 화장실 구분커피로만(Coffee Roman)은 스페셜티생두를 로스팅과 블렌딩을 직접하는 전문적인 로스터리 카페입니다.\n\n계절별로 다양하고 전문화된 커피와 티 그리고 각종베리에이션 음료를 경험할 수 있습니다.\n\n30평 규모의 위치. 40명이상 수용할수있으며 7~8대정도 무료로 주차할수있는 전용주차장이 있습니다.정보 수정 제안하기',
 '영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기0507-1327-4293안내복사',
 '- 용산역 1번 출구에서 도보로 5~10분\n- 카페 근처에 주차 불가능, 용산역 내에 유료 주차장 사용 후 도보로 방문영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기070-8862-6003복사제로페이포장, 배달, 무선 인터넷http://travertine.kr인스타그램용산 은행나무길의 카페 트래버틴\n북유럽 스페셜티 커피 La Cabra Coffee의 한국 공식 파트너.\n\n- 주차 불가능, 용산역 유료주차장 사용 권유\n- 반려동물은 매장 외부 동반 가능, 내부 어려움\n- 외부 음식 취식 불가능정보 수정 제안하기',
 '용산구 한강로3가 65-157 B1~2층 골드문커피\n (한강초등학교 정문 맞은 편)영업 종료내일 휴무내일 휴무펼쳐보기 - 생일 이벤트가 없는 매주 "일요일은 휴무" 입니다.접기0507-1301-1427안내복사제로페이단체석, 포장, 예약, 무선 인터넷http://www.goldmoon.coffee인스타그램GOLDMOON COFFEE\n골드문커피\n\n용산구 한강대로 분위기 좋은 카페\n\n대관 및 예약 기타문의\nH.010-3112-6118\nT. 070-4647-2255정보 수정 제안하기',
 '영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기02-6369-8549복사단체석, 포장, 무선 인터넷http://www.pontcoffee.com인스타그램스마트스토어스페셜티 커피 로스터리 폰트커피 용산점 입니다.\n좋은 품질의 커피를 편안하게.정보 수정 제안하기',
 '영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기02-790-4493복사단체석, 주차, 포장, 무선 인터넷https://www.instagram.com/seattle_master정보 수정 제안하기',
 '영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기070-7514-7659복사http://www.marinecoffee.co.kr안녕하세요. 마린커피 빅히트 사옥점입니다.',
 '하이브 사옥 뒷문 바로 맞은편 1분 거리영업 종료11:30에 영업 시작11시 30분에 영업 시작펼쳐보기0507-1337-3384안내복사제로페이포장, 무선 인터넷안녕하세요, 카페 버드입니다.\n카페 영업시간은 11:30-18:00입니다.\n\n이벤트카페 주최 희망 시에는 블로그 통해 안내사항 확인해주세요!\n\n하단은 공간 대관(이벤트 카페X) 예약 관련 사항입니다.\n\n-\n당신이 찾던 바로 그 공간, 카페 버드입니다\n\n카페 사장인 제가 주변인들과 아지트로 수십번도 더 써오면서 늘 행복했던 공간입니다\n그 행복을 여러분과 나누고파 엄청난 가성비로 대관 진행해요 히히\n\n인스타그램 @cafe_bud 들어오시면 적나라한 내부 영상 및 실제 진행한 다양한 모임들 후기 및 사진 올라와있으니 확인해보시는 것을 추천 드립니다\n\n* 네이버예약 이용 시 꼭! 디엠/카톡오픈채팅/네이버톡톡으로 연락을 주셔서 차액을 결제해주셔야 합니다!!\n\n- 예약가능시간\n월요일: 온종일 (카페 정기휴무일)\n화-일: 당일 저녁 7시-익일 오전 9시\n상황에 따라 타요일 또한 종일예약 가능하니 필요 시 문의 주세요\n\n- 인당 만원대 부담 보장\n너무 싼데... 어디 하나 부족한 거 아닐까- 안심하세요! 시설 안내 보시면 알겠지만 이 아지트에는 정말로 없는 게 없답니다\n\n- 시설 안내\n빔프로젝터, 스피커, 무선마이크, 청결한 내부화장실, 냉장고, 얼음 및 온수 무한제공, 주차\n\n- 공간 최대 장점\n테이블 배치+조도 조절이 자유로워서 사무적 분위기부터 감성파티 무드까지 완벽히 소화 가능\n\n-\n\n[ 드리는 말씀 ]\n\n요 물건 데려가셔서 대관비용 확 아껴버리고 주어진 예산 안에서 다른 곳들에 힘줘버리세요, 상사 지인 동료 친구 예쁨 왕창 받을 것이 분명합니다\n\n제가 직접 각종 목적으로 아지트 활용해봤습니다, (밤샘 공모전 준비/빔 필요한 스터디/세미나/강연/소규모 걸스나잇/동문회/홈커밍/신년회) 온갖 규모와 목적의 모임 몽땅 완벽히 소화 가능하고, 오셨던 주변분들 반응도 매번 저 세상으로 핫했습니다\n\n나름대로 이런 저런 모임을 많이 열어본 결과, 얼음 무제한 제공 생각보다 정말 중요하고 희귀하고 좋습니다, 빔프로젝터 스피커 마이크도요, 그래서 다 있는 거예요 ㅎㅎ\n\n주인장이 친절+센스+호탕+어린 것도 생각보다 진짜 중요합니다 (제 자랑ㅎ) 그러니 어쩌다가 이 공간을 찾으셨다면 매우 lucky... 인스타 들어와서 구경하시고 문의 주세요- 확신을 드릴게요! (제 마음대로 할인도 종종 해드립니다아아)정보 수정 제안하기',
 '용산역 또는 신용산역으로 한강대교 쪽으로 걸어서 5분 정도 떨어진 육교 바로 옆에서 더 체임버를 찾아주세요!영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기0507-1414-0325안내복사포장, 무선 인터넷http://www.theroastingchamber.co.kr인스타그램스마트스토어더 체임버는 스페셜티 커피 전문점입니다. IN-HOUSE 로스터리인 더 로스팅 체임버 (TRC) 원두를 프로페셔널 브루잉 머신인 브루비 (BREWVIE)로 추출하여 선보이는 원두 쇼룸 카페 입니다.\n\n또한 BREWVIE의 공식 개발 파트너사 및 총괄 판매사로서, 브루비 머신 소개와 컨설팅을 진행하고 있습니다. 네이버 예약을 통해 언제든지 상담을 신청하실 수 있습니다.정보 수정 제안하기',
 "용산역 옆 드래곤스파 뒷쪽에 위치해있습니다.\n제일세탁소 건너편에 위치해 있습니다\n골목길 코너쪽에 조심스럽게 위치해 있습니다영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기0507-1422-7574안내복사주차, 포장, 무선 인터넷, 반려동물 동반https://www.instagram.com/mercury_espresso_barMercury espressobar 브랜드 스토리\n\n 머큐리는 태양계의 첫번째 행성인 수성을 뜻하기도 하며 그리스 로마신화의 상업과 상인을 수호하는 전령의 신 헤르메스를 뜻하기도 한다.\n\n 헤르메스는 지상에서부터 지하까지 가지 못할 곳이 없다. 그는 신의 세계와 인간의 세계, 지하의 세계를 자유자재로 넘나든다. 이러한 자유로움과 경계를 허무는 그의 능력을 추구하고 동경한다.\n\n 그러하여 '머큐리 에스프레소바'는 이러한 헤르메스를 상징하며 많은 이들에게 커피라는 음료와 디저트, 그리고 공간을 통해 예술의 경계와 삶의 경계를 오고 감을 자유롭게 하여 많은 영감과 자유로움 그리고 편안함을 전하는데에 가치를 둔다.\n\n1호점, 2호점인 '헤미안 브런치바','헤미안 커피바'와 같이 보헤미안의 다채로움과 자유로움, 각양각색의 개성을 추구하는 브랜드로써 자유로운 여행자같은 정신을 이어받아 또 새로운 컨셉과 장소 그리고 다른 스타일을 제시하는 '머큐리'로 파생되었다.\n\n앞으로도 계속해서 시대의 변화의 흐름에 따라 계속해서 경계를 무너뜨리며 많은 이들과 같이 변화해 나갈 수 있는 브랜드가 되기를 추구한다.\n\nMercury espresssobar는 들고 먹을 수 있는 세가지 이상의 디저트와 각종 에스프레소 메뉴 그리고 다양한 음료를 판매합니다. 3잔의 음료를 드시면 에스프레소 또는 아메리카노를 무료제공하오니 커피 소비의 즐거움 또한 느껴보시길 바랍니다.\n\n작은 건물 코너에 위치하여 따스한 햇살과 함께 아침을 열어보세요!\n가끔은 테라스 엣지에 앉아서 에스프레소 한잔 또는 내부에서 음악과 함께 커피 한 잔의 여유로 하루를 만끽하세요!\n\n1호점 : 헤미안 브런치바 : @hemian_brunch_bar : 녹사평대로 250\n2호점 : 헤미안 커피바 : @hemian_coffee_bar : 녹사평대로 40나길 16",
 '신용산역/용산역에서 도보 10분영업 종료12:00에 영업 시작12시 0분에 영업 시작펼쳐보기070-7543-9847복사제로페이포장, 무선 인터넷http://instagram.com/stoked_seoul뉴질랜드, 호주 스타일 수제 디저트 카페 + 테이크 아웃 + 예약 케이크 판매정보 수정 제안하기',
 '용산역 , 신용산역 인근 도보 5분(1호선,4호선,경의중앙선)\n한강대로북단,LG유플러스 정거장 도보 1분\n간선100,150,151,501,504,506,507,605,750A,750B,751,752\n한강초등학교 도보 1분오늘 휴무매주 토요일 휴무매주 토요일 휴무펼쳐보기 - 대관행사 시 주말정상영업접기070-8624-0728복사제로페이포장, 배달, 무선 인터넷, 반려동물 동반http://instagram.com/merci_ck귀엽고 사랑스런 분위기의 메르시쿠키입니다. 직접 고메버터를 이용해 만든 쿠키,레몬케이크,마들렌 등의 디저트와 비주얼부터 귀여운 맛도 좋은 메론소다,크림소다,밀크쉐이크도 같이 즐겨보세요.정보 수정 제안하기',
 '1호선 용산역 1번출구에서 도보 759m 하이브(구 빅히트)건물 뒷편\n4호선 신용산역 2번출구에서 도보로 575m영업 종료내일 휴무내일 휴무펼쳐보기070-7537-3780복사단체석, 포장, 배달, 무선 인터넷, 남/녀 화장실 구분https://www.instagram.com/lombre378_official정보 수정 제안하기',
 '토토미용실 옆, 제일정육점 맞은편에\n위치해있습니다영업 중21:50에 영업 종료21시 50분에 영업 종료펼쳐보기0507-1346-0760안내복사단체석, 주차, 무선 인터넷, 반려동물 동반https://www.instagram.com/greencorner_seoul애견동반,키즈동반,단체석 보유\n주차가능,생일카페 가능합니다:)',
 "'부동산 40번지' 옆 입구 계단으로 올라오시면 됩니다.\n4층은 온더홀, 5층은 로파서울 입니다.\n_\n용산역 1번 출구, 신용산역 3번출구로 나오시면 가깝습니다.\n버스정류장은 한강대교북단, LG유플러스, 용산푸르지오써밋 정류장을 이용하시면 가깝습니다.\n_\n화단 앞은 주차를 금지하오니 참고 부탁드립니다.영업 종료13:00에 영업 시작13시 0분에 영업 시작펼쳐보기0507-1356-8332안내복사네이버페이예약, 무선 인터넷, 반려동물 동반https://www.instagram.com/onthewhole_?igshid=YmMyMTA2M2Y=웹사이트4층에 위치하고 있습니다.\n워크인 이용 가능합니다.\n_\nPopup Cafe and Bar for Food Experiments\n온더홀은 먹을 것을 주제로 전시 경험을 연구하는 f&b 팀입니다.",
 '신용산역 2번출구로 나와 나온방향으로 300 미터 정도 지나 육교 아래 있습니다.영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기02-749-2322복사제로페이, 네이버페이포장http://www.ediya.com/블로그인스타그램페이스북유튜브Always beside you, EDIYA COFFEE\n일상 속 모두에게 커피를 통한 휴식과 영감을 제공하는 이디야커피는,\n대한민국의 커피 문화를 만들어가는 가장 가까운 안식처입니다.식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.08.10~2024.08.092022년 8월 10일~2024년 8월 9일정보 수정 제안하기',
 '차품집은 BTS신사옥 하이브 후문에 위치하고 있습니다.\n매장이 협소하여 주차가 어려우니 가급적 대중교통을 이용해주시기를 부탁드립니다.\n\n지하철 이용시 신용산역 2번 출구로 나와 직진 또는 용산역 1번 출구에서 나와 횡단보도 이용 약 600m, 도보 10분 소요\n\n버스 이용시 한강대교북단.LG유플러스 정류장에서 도보 3분 소요\n100 150 151 152 500 501 504 506 507 605 750A 750B 751 752 0017 N15오늘 휴무05/20 휴무05/20 휴무펼쳐보기05/27-05/28  휴무접기휴무일05/20-05/21, 05/27-05/280507-1329-1670안내복사제로페이단체석, 포장, 방문접수/출장, 예약, 무선 인터넷https://www.instagram.com/chapoom.zip서울 한강로에 위치한 차품집은 차와 공예품을 함께 즐길 수 있는 캐주얼 티하우스입니다. 차품집은 전문 티소믈리에 및 티마스터가 엄선한 티 컬렉션을 바탕으로 밀크티, 티에이드 등 자체 티 베리에이션을 통해 친근하고 편안한 차를 선보이고자 합니다.정보 수정 제안하기',
 '영업 종료08:00에 영업 시작8시 0분에 영업 시작펼쳐보기02-797-0011복사가격표 사진을 올려주세요.추가제로페이포장따듯하고 맛있는 커피로 보답하겠습니다\n*다양한 혜택 & 적립이 가능한 네이버 페이로 결제 가능합니다!',
 '용산역 1번출구로 나오셔서 오른쪽 방향으로 가시면 횡단 보도가 있습니다. 짧은 횡단보도 두개를 건너서 직진하시면 라바테라가 있습니다^^ 역에서부터 약 600미터에요~영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기02-794-1118복사단체석, 주차, 포장, 무선 인터넷https://www.instagram.com/cafe_lavatera/용산역 1번출구로 나오셔서 오른쪽 방향으로 가시면 횡단 보도가 있습니다. 짧은 횡단보도 두개를 건너서 직진하시면 라바테라가 있습니다^^ 역에서부터 약 600미터에요~ 주차도 가능하니 네비에 검색 하시고 오세요! 수제버거는 전화 주문도 가능합니다!정보 수정 제안하기',
 '용산 땡땡거리 근처에 있어요\n마당을 지나 2층에 있답니다. :)영업 종료08:00에 영업 시작8시 0분에 영업 시작펼쳐보기0507-1307-3411안내복사제로페이단체석, 포장, 배달, 예약, 무선 인터넷, 반려동물 동반https://www.instagram.com/ayheyaseoulLA한인타운에서 영감을 받은 베이커리 카페.\n직접 개발한 모던코리안 스타일 디저트와 고퀄리티 싱글오리진 커피, 클래식밀크쉐이크를 즐길수 있는 곳',
 '새로운 BTS사옥 바로옆 주차장입구 1층상가 커피숍영업 중21:50에 라스트오더21시 50분에 라스트오더펼쳐보기0507-1380-7311안내복사지역화폐(지류), 제로페이단체석, 주차, 포장, 예약, 무선 인터넷, 반려동물 동반https://www.instagram.com/블랙드럼은 세계 모든 아티스트를 성원하는 팬들을 응원합니다!정보 수정 제안하기',
 '신용산역 도보 5분\n하이브 신사옥 가는길 육교밑 편의점에서 왼쪽으로 한강초등학교 정문 앞입니다\n주차 가능영업 중21:30에 라스트오더21시 30분에 라스트오더펼쳐보기 - 건물 외관 구조물 해체로 인한 영업 중단접기0507-1310-2174안내복사지역화폐(지류,카드,모바일), 제로페이단체석, 주차, 배달, 예약, 무선 인터넷, 반려동물 동반http://instagram.com/cafe_piedpiper건물 공사로 당분간 저녁시간만 주차가 가능하니 방문 전 전화바랍니다. 주차장은 카페 방문 이외 목적으로는 이용하실 수 없습니다.정보 수정 제안하기',
 "에르디는 주차가 불가한 관계로 되도록 도보 방문을 추천드립니다. 대중교통 방문과 도보 방문시 역 기준으로 안내 하겠습니다.\n\n1. 용산역 1번 출구로 나와 도보 8분 거리에 위치해 있습니다.\n\n2. 신용산역 3번 출구로 나와 도보 10분 거리에 위치해 있습니다.\n\n3. 삼각지역 4번 출구로 나와 750A 버스를 타고 한강대교 북단,LG 유플러스 하차 후 도보 3분 거리에 위치해 있습니다.영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기 - 휴무가 발생할 경우 '새소식'을 통해 안내드리겠습니다.접기0507-1333-4855안내복사단체석, 포장, 무선 인터넷, 반려동물 동반https://www.instagram.com/errd.seoul/안녕하세요. 에르디(ERRD) 입니다.\n\n에르디(ERRD)는 'EVERY DAY'의 속어(Slang)입니다. 에르디는 매일 매일 반복되는 일상, 그 일상을 채우는 오늘의 가치에 대해 귀기울이는 공간입니다.\n\n자세히 들여다볼수록 어제와는 조금씩 다른 오늘들. 에르디는 공간안에서 낯선 사람들과 시간을 매개체로 일상을 재해석하며 시간을 차곡차곡 쌓아 나갑니다.\n\n작은 골목에서 일상의 가치에 대해 함께 이야기하고자 합니다. 당신의 오늘,요일, 매일. 에르디. '당신에게 오늘은 어떤 요일(DAY)인가요?'\n\n<에르디 in 용리단길>\n\n용리단길은 이태원의 경리단길, 망원동의 망리단길에 이어 또 다른 힙플레이스로 자리잡고 있습니다.\n\n환승역 정도로만 기억되던 신용산역, 용산역, 삼각지역 주변으로 매력적인 컨셉을 가진 여러 매장이 생겨나고 있습니다.\n\n에르디 역시 시작은 서울대 입구 샤로수 길 점으로 시작되어 더 많은 고객님께 선보이기위해 용산점이 만들어지게 되었습니다.\n\n<에르디가 가진 특별한 메뉴>\n\n에르디에는 다른 카페에서는 볼 수 없는 특별한 메뉴가 있습니다.\n\n- 헤이-너트 크림 라떼 : 수제 카라멜이 들어간 우유 베이스에 헤이즐넛, 아몬드, 마카다미아를 넣어 고소한 맛이 일품인 크림라떼\n\n- 커스터드 크림 라떼 : 달달한 우유 블렌딩에 수제 커스터드 크림을 올리고 토치로 한 번 카라멜라이징한 크림브륄레 음료\n\n- 로우 슈페너 : 부드러운 우유 블렌딩에 컵 주변으로 사탕수수를 묻히고 크림과 저어 먹는 음료\n\n이 세 메뉴를 대표로 약 20개에 달하는 메뉴가 여러분을 기다리고 있습니다.\n\n<에르디 순간을 기록하다>\n\n에르디는 오늘의 가치에 귀 기울이고 어제와 달라진 모습에서 소소한 특별함을 발견합니다.\n\n현대의 우리는 어떠한 형태로든 소식을 알지 못한다면 영원히 다시 볼 수 없는 사이가 될지도 모릅니다. 그래서 에르디는 순간의 '흔적'을 남기는 경험을 제공합니다.\n\n특별한 사진기로 '사진'을 남기고 '종이'에 하루를 기록하며 소중한 추억을 남기는 공간이 되기를 바랍니다.\n\n에르디는 수 많은 일상이 있다고 생각합니다.\n\n바쁜 일상, 권태로운 일상, 힘든 일상, 지겨운 일상, 답답한 일상, 정신 없는 일상, 따분한 일상, 똑같은 일상, 외로운 일상, 씁쓸한 일상, 우울한 일상, 즐거운 일상, 행복한 일상, 노력하는 일상 등\n\n당신의 일상은 어떤가요? 당신의 오늘은 어떤가요? 당신은 어떤 사람인가요? 끝없이 질문을 던지며,\n\n에르디는 같은 자리에서 당신을 기다리고 또 당신을 기록합니다.",
 '-용산역 1번출구 신용산역 3번출구 직진 500m\n-용산 bts사옥 건너편\n-오근내닭갈비2 옆입니다영업 중22:00에 라스트오더22시 0분에 라스트오더펼쳐보기 - 영업시간, 휴무일 관련 안내 인스타그램 확인부탁드립니다접기0507-1379-8772안내복사제로페이주차, 포장, 예약, 무선 인터넷https://www.instagram.com/hammered_yongsan낮 시간(10~18)은 이탈리아 정통 에스프레소 와 카페 메뉴,\n저녁 시간(18~02)은 위스키, 와인, 칵테일이 준비되어있습니다.정보 수정 제안하기',
 '영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기05/30  휴무접기휴무일05/30070-4012-2149복사포장, 무선 인터넷, 반려동물 동반https://www.instagram.com/the_miller_rabbit토끼마을로 놀러오세요:)\n소금빵 휘낭시에 당근파운드 각종쿠키&케이크',
 '영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기0507-1304-7339안내복사단체석, 무선 인터넷, 남/녀 화장실 구분https://www.instagram.com/fellacoffeechoco/웹사이트소통과 가치창출을 최우선으로 하는 펠어커피초코 입니다. 경험해 보지 못한 나만의 신개념 커피를 원하신다면 고객님 만족을 최우선으로 하는 저희 펠어커피를 찾아주세요.\n\n펠어커피초코는 카카오 메이커가 카카오빈을 로스팅하여 만든 수제 빈투바 생초콜릿과 초콜릿 디저트, 펠어커피 로스팅공장에서 직접 로스팅한 신선한 스페셜티커피를 제공하고 있습니다.\n\n펠어커피초코는 바리스타 로스터 브랜딩 디자이너 쉐프등 7명의 분야별 전문가로 구성되어 있으며 언제나 고객의 관점에서 고객의 니드에 맞게 능동적인 피드백을 적극 반영하고 수정해 나가며 하나의 제품을 만들어 나가고 있습니다',
 '용산역과 신용산역에서 한강대교 방면으로 오시면\r\n베르가모 웨딩홀 뒷편에 있습니다영업 종료12:00에 영업 시작12시 0분에 영업 시작펼쳐보기02-792-4688복사제로페이주차, 포장, 예약, 무선 인터넷, 반려동물 동반, 장애인 편의시설서울대의 At Panini의 후속 카페 Sion 입니다.\r\n이번엔 바쁘고 빠르게가 아닌\r\n조용하고 잔잔하게가 테마입니다.\r\n잠시 편하게 쉬어갈 수 있는 아지트가 되기를...정보 수정 제안하기',
 '영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기 - 공휴일 영업시간 14:30-19:30접기070-7585-2546복사제로페이주차, 포장, 배달, 예약, 무선 인터넷, 반려동물 동반https://www.instagram.com/wknd_bakery_매일굽는 구움과자와 디저트가 맛있는 베이커리카페입니다.',
 '용산 엘지유플러스본사 건너편\n신용산역 3번출구에서 도보 5분영업 종료11:00에 영업 시작11시 0분에 영업 시작펼쳐보기0507-1453-3319안내복사제로페이단체석, 주차, 예약, 무선 인터넷https://www.instagram.com/repos_de_lala/저희 레뽀드라라는 프리미엄 커피 / 디저트 카페입니다, 레뽀드 라라는 항상 최상의 품질과 맛을 추구합니다. 이를 위해 저희 매장에서는 프랑스 버터와 유정란, 100% 동물성 생크림, 비정제 설탕 등 최고급의 재료를 거짓없이 사용하고 있습니다.\n특히 저희 레뽀드라라에서 사용하는 프랑스에서 직수입하는 최고급버터 중 하나인 프랑스 이즈니 고메버터는 일반 버터보다 더 부드러운 질감과 고소하고 풍미깊은 버터 특유의 향을 자랑합니다. 유정란은 고단백, 낮은 지방 함량으로 건강함을 올려주고, 100% 동물성 생크림이 부드러운 맛과 질감을 더해줍니다. 매일 아침 레뽀드라라는 약 12종의 시그니처 스콘과 휘낭시에를 만들고 있습니다. 가족,친구를 대접한다는 마음으로 항상 마음을 담아 베이커리 하나에도 정성을 기울이고 있습니다. 저희 레뽀드 라라는 누군가에게 선물하고 싶은 마음 이라는 모토를 가지고 임하고 있습니다. 그 만큼 손님들을 저희 가족처럼 생각하여 가족들이 먹는 마음으로 최고급 재료 사용과 청결한 마음가짐으로 위생에 각별히 신경을 기울이고 있습니다. 항상 고객님들의 믿음에 보답하는 레뽀드라라 되겠습니다.정보 수정 제안하기',
 '용산역 근교에 위치해 있습니다. 주차는 불가능합니다!영업 중21:50에 라스트오더21시 50분에 라스트오더펼쳐보기 - 라스트 오더는 영업시간 한 시간전접기가격표 사진을 올려주세요.추가네이버페이일 - 목 11:30-22:00 / 라스트 오더 21시\n금 - 토 11:30-23:00 / 라스트오더 22시\n-주차 불가능\n-애견 동반 가능/ 케어 부탁 드려요 :)\n-아이 동반 가능 / 아이가 다치지 않게 부탁 드려요:)',
 '지하철 1호선 용산역 2번 출구, 아이파크몰 서관(TASTE PARK) 6층 영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기1522-3232복사주차http://www.starbucks.co.kr/인스타그램페이스북1.주차가능 2.주차장 위치-아이파크몰 주차장 이용 3.주차가능 대수-100대 이상 4.주차 조건-조건부 무료(음료 구매시 60분 무료) 5.주차요금정산방법-POS 파트너에게 요청식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.05.08~2024.05.072022년 5월 8일~2024년 5월 7일정보 수정 제안하기사장님, 플레이스를무료로 직접\xa0관리하세요!권한 받기',
 '용산역 아이파크몰 6층 테마파크 팝콘D스퀘어 카페 팝퍼블영업 종료10:30에 영업 시작10시 30분에 영업 시작펼쳐보기02-6373-3360복사단체석, 주차, 포장, 무선 인터넷, 남/녀 화장실 구분, 장애인 편의시설http://popcond.com/index.php?p=popable인스타그램다양한 캐릭터와 애니메이션이 공존하는 콜라보카페!\n\n수시로 변하는 캐릭터팝업 카페를 팝퍼블에서 만나보세요 \n단 ! 오늘 만났던 콜라보가 다음엔 없을 수 있다는 점 기억해 주세요~정보 수정 제안하기',
 '영업 중24:00에 영업 종료0시 0분에 영업 종료펼쳐보기 - 설날 영업시간접기02-6085-1400복사제로페이주차, 무선 인터넷, 반려동물 동반커피 라스트 오더 8시\n카페(커피만)이용은 9시에 마감됩니다.\n9시부터 마감까지 Bar(주류) 시간 입니다.정보 수정 제안하기',
 '영업 중21:30에 라스트오더21시 30분에 라스트오더펼쳐보기02-2012-0616복사제로페이주차, 포장, 배달, 예약, 무선 인터넷, 남/녀 화장실 구분http://www.billyangel.co.kr/프리미엄 디저트 편집샵 빌리엔젤 케이크 용산아이파크몰점\n\n저렴한 가격대와 최고의 맛, 그리고 품질이라는 슬로건 아래,\n\n빌리엔젤은 오늘도 누구나 쉽게, 빠르게, 저렴한 가격으로 디저트를 즐길 수 있는 장소가 되기 위해 노력하고 있습니다.\n\n빌리엔젤은 최고급 재료로 만든 맛있는 케이크를 누구나 즐길 수 있는 새로운 디저트 문화를 지향합니다.정보 수정 제안하기',
 '용산역 아이파크몰영업 종료10:30에 영업 시작10시 30분에 영업 시작펼쳐보기02-2012-0604복사제로페이, 네이버페이단체석, 주차, 무선 인터넷용산아이파크몰 6층에 위치하고있는 프리미업 디져트 카페 투썸플레이스 입니다.식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.09.29~2024.09.282022년 9월 29일~2024년 9월 28일정보 수정 제안하기',
 '영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기02-2012-0467복사http://www.tazzadorocoffee.co.kr인스타그램이태리 3대 커피샵으로, 전세계적으로 유명한 타짜도로(TAZZADORO)는 \n100여년의 전통을 가지고 있으며, 이태리에서도 몇 안 되는 커피 장인 회사로 타짜도로만의 독특한 블렌딩과 로스팅으로 유명하다. 또한 인공향이나 레시틴 등 첨가제가 없는 100% 천연 커피이다.\n최고의 커피를 즐기기 위해 방문하는 전 세계인으로 인해 타짜도로 매장은 늘 활기차고, 한국에서도 로마에 가면 반드시 들려야 하는 3대 맛집으로 유명하다.\n- 죽기전에 가봐야할 장소 1000 선정\n- 죽기전에 먹어야할 음식 1000 선정\n정보 수정 제안하기',
 '용산 아이파크몰 동관 6층영업 중21:30에 영업 종료21시 30분에 영업 종료펼쳐보기02-2012-0690복사http://www.baristapaulbassett.co.kr/인스타그램페이스북폴바셋 용산 아이파크몰점의 스마트주문 페이지 입니다.식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02021.08.12~2023.08.112021년 8월 12일~2023년 8월 11일정보 수정 제안하기사장님, 플레이스를무료로 직접\xa0관리하세요!권한 받기',
 '용산아이파크몰 6층 스타벅스 주변영업 중21:30에 라스트오더21시 30분에 라스트오더펼쳐보기0507-1341-0709안내복사주차, 포장, 예약, 무선 인터넷, 남/녀 화장실 구분, 장애인 편의시설http://www.gong-cha.co.kr/brand/GONG CHA 는 버블티의 본고장 타이완에서 2006년 시작되어 \n신선하고 건강한 재료를 통해 버블티의 새로운 맛을 개척해 냈습니다. \n그 결과 2009년부터 해외 시장으로까지 퍼져나가 \n현재 홍콩, 마카오, 싱카폴, 말레시아, 필리핀, 중국 전역에 걸쳐 180개여개의 \n매장으로 퍼져나가 2012년 , Gong Cha 의 새로운 맛을\nGong Cha Korea 로 느끼실 수 있습니다.\n\n주차 1시간무료식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02023.02.16~2025.02.152023년 2월 16일~2025년 2월 15일정보 수정 제안하기',
 '영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기02-2012-0731복사안녕하세요.\n커피빈코리아 입니다.\n많은 이용 부탁드립니다.식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.08.18~2024.08.172022년 8월 18일~2024년 8월 17일',
 '영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기무선 인터넷, 남/녀 화장실 구분http://www.hollys.co.kr/인스타그램페이스북다양한 토양과 기후에서 자란 커피 원두는 그 속에 각기 다른 맛과 향의 비밀을 숨기고 있습니다.\n생두를 로스팅하여 에스프레소를 만드는 과정은 단순하고 평범해 보이지만, 사실은 로스팅과 추출법 등의 미묘하고 작은 차이가\n커피 맛을 변화시킵니다.\n\n원두에 숨겨진 이러한 커피의 비밀을 하나 하나 밝혀가면서 많은 사람들이 커피와 함께 소중한 순간을 즐기도록 해주는 것이\n바로 할리스가 추구하는 [커피의 즐거움]입니다.\n\n오늘도 할리스는 전세계의 커피 산지를 연구하고, 원두 본연의 맛을 살리기 위한 수많은 블랜딩을 개발하는 등 다양한\n노력을 지속하고 있습니다. 커피가 주는 아름다움을 보다 많은 고객들이 즐길 수 있도록, 매 순간 의미 있는 작은 차이를\n만들어가는 할리스가 되겠습니다.식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02023.05.03~2025.05.022023년 5월 3일~2025년 5월 2일정보 수정 제안하기사장님, 플레이스를무료로 직접\xa0관리하세요!권한 받기',
 "용산역 1번 출구 1분, 신용산역 3번 출구 2분\n\n네비게이션에 '아이파크몰', '용산역'을 검색하시면 쉽게 방문하실 수 있으며, 자세한 위치는 아이파크몰 1층 초입에 있습니다.\n\n저희 아방 갤러리 카페 용산아이파크몰점은 주차공간이 쾌적하고 무료주차 2시간이 가능하기 때문에 자가용으로 오시는것도 추천 드립니다.영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기0507-1337-3776안내복사단체석, 주차, 포장, 배달, 무선 인터넷, 남/녀 화장실 구분http://avantbakery.com/인스타그램AVANT Gallery Cafe\n\n좋은 재료를 이용하여 만드는 디저트와 고급 원두로 만드는 커피를 제공합니다. 국내 외 유명 작가들의 미술작품을 상설 전시하며 판매를 대행하고 있습니다.\n\nAVANT+ 는 갤러리 카페로서, 대중의 일상에 스며드는 예술을 의미합니다. 매장의 다양한 국내외 유명작가들의 미술 작품과 함께 향긋한 커피와 일상 속에서 직접 예술을 경험해보시기 바랍니다\n\nA life with Art정보 수정 제안하기",
 '이용시간을 알려주세요.추가02-2012-0101복사식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02023.03.28~2025.03.272023년 3월 28일~2025년 3월 27일',
 '용산역 아이파크몰 서관 4층에 올라오면 오른편에 바로 있습니다.영업 중22:00에 라스트오더22시 0분에 라스트오더펼쳐보기02-2012-0473복사제로페이단체석, 주차, 포장, 무선 인터넷, 남/녀 화장실 구분https://tomntoms.com/블로그인스타그램스마트스토어페이스북깨끗하고 분위기 좋은 매장에서 신선하고 맛있는 커피와 따뜻한 프레즐 함께 드시며 소중한사람과 즐거운시간 보내세요정보 수정 제안하기',
 '영업 종료10:30에 영업 시작10시 30분에 영업 시작펼쳐보기02-2012-0443복사제로페이단체석, 주차, 포장, 무선 인터넷식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.09.16~2024.09.152022년 9월 16일~2024년 9월 15일정보 수정 제안하기',
 '영업 중22:00에 영업 종료22시 0분에 영업 종료펼쳐보기02-2012-0425복사포장, 배달, 무선 인터넷식약처 인증 위생등급 매우우수 음식점접기유효기간:\xa02022.09.29~2024.09.282022년 9월 29일~2024년 9월 28일사장님, 플레이스를무료로 직접\xa0관리하세요!권한 받기',
 '영업 중21:30에 라스트오더21시 30분에 라스트오더펼쳐보기 - 매장이용시간: 21:30접기02-2012-0500복사제로페이, 네이버페이http://www.caffe-pascucci.co.kr/파스쿠찌 용산아이파크몰점입니다. 네이버 스마트주문에서 간편하게 주문하세요!정보 수정 제안하기',

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
menu = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/졸업프로젝트/yongsangu_menu.csv", encoding="utf-8", header = 0)

In [ ]:
menu

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]+Sheet1!",NaN
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'..."
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파..."
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[]
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400..."

In [ ]:
americano = []
for k in range(len(menu)):
        if menu['네이버 메뉴'][k].find('아메리카노') != -1: # 없다가 아니면 = 있으면
          americano.append(1)
        else:
          americano.append(0)

In [ ]:
latte = []
for k in range(len(menu)):
        if menu['네이버 메뉴'][k].find('라떼') != -1: # 없다가 아니면 = 있으면
          latte.append(1)
        else:
          latte.append(0)

In [ ]:
menu['네_아메'] = americano

In [ ]:
menu['네_라떼'] = latte

In [ ]:
menu = menu.astype({'카카오 메뉴':'str'})

In [ ]:
americano = []
for k in range(len(menu)):
        if menu['카카오 메뉴'][k].find('아메리카노') != -1: # 없다가 아니면 = 있으면
          americano.append(1)
        else:
          americano.append(0)

In [ ]:
latte = []
for k in range(len(menu)):
        if menu['카카오 메뉴'][k].find('라떼') != -1: # 없다가 아니면 = 있으면
          latte.append(1)
        else:
          latte.append(0)

In [ ]:
menu['카_아메'] = americano

In [ ]:
menu['카_라떼'] = latte

In [ ]:
menu

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,네_라떼,카_아메,카_라떼
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]+Sheet1!",nan,1,0,0,0
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ...",1,0,1,1
2,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[],0,0,0,0
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'...",1,0,1,1
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",nan,1,1,0,0
...,...,...,...,...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파...",1,0,0,0
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",nan,1,1,0,0
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[],0,0,0,0
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",nan,0,0,0,0
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400...",1,0,0,0

In [ ]:
americano=[]
for k in range(len(menu)):
  if menu['네_아메'][k]==1 or menu['카_아메'][k]==1:
    americano.append(1)
  else:
    americano.append(0)

In [ ]:
latte=[]
for k in range(len(menu)):
  if menu['네_라떼'][k]==1 or menu['카_라떼'][k]==1:
    latte.append(1)
  else:
    latte.append(0)

In [ ]:
menu['아메리카노'] = americano

In [ ]:
menu['라떼'] = latte

In [ ]:
menu

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,네_라떼,카_아메,카_라떼,아메리카노,라떼
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]+Sheet1!",nan,1,0,0,0,1,0
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ...",1,0,1,1,1,1
2,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[],0,0,0,0,0,0
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'...",1,0,1,1,1,1
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",nan,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파...",1,0,0,0,1,0
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",nan,1,1,0,0,1,1
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[],0,0,0,0,0,0
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",nan,0,0,0,0,0,0
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400...",1,0,0,0,1,0

In [ ]:
menu2 = menu[(menu['아메리카노'] == 1) | (menu['라떼'] == 1)]
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,네_라떼,카_아메,카_라떼,아메리카노,라떼
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]+Sheet1!",nan,1,0,0,0,1,0
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ...",1,0,1,1,1,1
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'...",1,0,1,1,1,1
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",nan,1,1,0,0,1,1
5,37236205,2.405972e+07,카페로찌,"[{'에스프레소': '3,000원'}, {'아메리카노': '3,000원'}, {'카...","[{'에스프레소': '3,000'}, {'아메리카노': '3,000'}, {'카페라...",1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1065,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,"[{'룽고 (Standard)': '4,900원'}, {'카페라떼 (Standard...",nan,0,1,0,0,0,1
1066,18184715,8.123978e+06,파리크라상 한남점,"[{'머쉬룸 오믈렛 브런치': '16,000원'}, {'클럽 샌드위치 브런치': '...","[{'파리 크라상(AOP 버터)': '3,900'}, {'몽블랑브레드': '6,50...",1,1,0,0,1,1
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파...",1,0,0,0,1,0
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",nan,1,1,0,0,1,1
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400...",1,0,0,0,1,0

In [ ]:
menu['네이버 메뉴'][0] = [{'아메리카노': '6,500원'}]

<ipython-input-6-940a74b949db>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu['네이버 메뉴'][0] = [{'아메리카노': '6,500원'}]

In [ ]:
menu2 = menu

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]",NaN
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'..."
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파..."
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[]
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400..."

In [ ]:
menu2 = menu2.reset_index(drop=True)

In [ ]:
menu2 = menu2.astype({'카카오 메뉴':'str'})
menu2 = menu2.astype({'네이버 메뉴':'str'})

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]",NaN
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'..."
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파..."
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[]
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400..."

In [ ]:
menu2['네이버 메뉴'] = menu2['네이버 메뉴'].str.replace('{', '[')
menu2['네이버 메뉴'] = menu2['네이버 메뉴'].str.replace("}", "]")
menu2['네이버 메뉴'] = menu2['네이버 메뉴'].str.replace(":", ",")

<ipython-input-10-a78e39284b9f>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  menu2['네이버 메뉴'] = menu2['네이버 메뉴'].str.replace('{', '[')
<ipython-input-10-a78e39284b9f>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  menu2['네이버 메뉴'] = menu2['네이버 메뉴'].str.replace("}", "]")

In [ ]:
menu2['카카오 메뉴'] = menu2['카카오 메뉴'].str.replace('{', '[')
menu2['카카오 메뉴'] = menu2['카카오 메뉴'].str.replace("}", "]")
menu2['카카오 메뉴'] = menu2['카카오 메뉴'].str.replace(":", ",")

<ipython-input-11-4c680e41ff68>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  menu2['카카오 메뉴'] = menu2['카카오 메뉴'].str.replace('{', '[')
<ipython-input-11-4c680e41ff68>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  menu2['카카오 메뉴'] = menu2['카카오 메뉴'].str.replace("}", "]")

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴
0,1275361497,8.264307e+08,르플뢰브,"[['아메리카노', '6,500원']]",nan
1,36877505,2.139356e+07,커피공장103 이촌점,"[['아메리카노', '3,500원'], ['(원두)하우스블렌드', '5,000원']]","[['에스프레소', '3,500'], ['아메리카노(HOT)', '3,500'], ..."
2,37568842,1.904932e+09,테이블스 용산점,"[['아인슈페너', '5,000원'], ['초코큐브파운드', '3,500원'], [...",[]
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[['핫아메리카노', '1,700원'], ['뚱카롱', '2,500원'], ['마카...","[['아메리카노', '1,700'], ['카페라떼', '2,500'], ['핫초코'..."
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[['카페 아메리카노', '3,200원'], ['카페 라떼', '4,200원'], ...",nan
...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[['파인트', '8,900원'], ['쿼터', '17,000원'], ['패밀리',...","[['옹기종기팩', '26,500'], ['아빠왔다팩', '13,500'], ['파..."
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[['꼬빠 삐꼴라(1가지맛)(컵or콘)', '4,500원'], ['꼬빠 메디아(2가...",nan
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[]
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[['(아몬드)크림치즈스틱', '5,400원'], ['(할라피뇨,블랙페퍼)치즈핫도그...",nan
1073,11492935,8.257019e+06,던킨 서울역2호점,"[['아메리카노', '4,100원']]","[['올스타 도넛세트', '15,800'], ['버라이어티 10팩', '18,400..."

In [ ]:
for i in range(len(menu2)):
  if menu2['카카오 메뉴'][i]=="nan":
    menu2['카카오 메뉴'][i] = "[]"

<ipython-input-13-8899f9d05417>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu2['카카오 메뉴'][i] = "[]"

In [ ]:
from ast import literal_eval

# 문자열을 리스트로 변환
def str_to_list(x):
    try:
        return literal_eval(x)
    except: #해당 값이 null값이거나 오류가 있을 때, None을 return 하기
        return None

# df['컬럼명'] = df['컬럼명'].apply(lambda x: str_to_list(x))
# df['결측값수'] = df['결측값수'].apply(lambda x: str_to_list(x))
menu2['네이버 메뉴'] = menu2['네이버 메뉴'].apply(lambda x: str_to_list(x))
menu2['카카오 메뉴'] = menu2['카카오 메뉴'].apply(lambda x: str_to_list(x))

In [ ]:
index1 = []
americano = []
for i in range(len(menu2)):
  print(i)
  for j in range(len(menu2['네이버 메뉴'][i])):
    if menu2['네이버 메뉴'][i][j][0].find("americano") != -1:
      print(menu2['네이버 메뉴'][i][j])
      index1.append(i)
      americano.append(menu2['네이버 메뉴'][i][j])
    if menu2['네이버 메뉴'][i][j][0].find("아메리카노") != -1:
      print(menu2['네이버 메뉴'][i][j])
      index1.append(i)
      americano.append(menu2['네이버 메뉴'][i][j])
    if menu2['네이버 메뉴'][i][j][0] == "커피":
      print(menu2['네이버 메뉴'][i][j])
      index1.append(i)
      americano.append(menu2['네이버 메뉴'][i][j])

0
['아메리카노', '6,500원']
1
['아메리카노', '3,500원']
2
3
['핫아메리카노', '1,700원']
4
['카페 아메리카노', '3,200원']
5
['아메리카노', '3,000원']
6
['아이스아메리카노', '2,000원']
['아메리카노', '1,500원']
7
['아메리카노', '3,000원']
['아메리카노 ICE', '3,500원']
8
['아메리카노', '3,000원']
9
10
['아이스아메리카노', '4,000원']
['샌드위치+아메리카노', '7,500원']
11
['아메리카노', '3,700원']
12
13
['아메리카노(ICED)', '4,300원']
['아메리카노(HOT)', '3,800원']
14
15
['아메리카노', '2,500원']
16
17
18
['아메리카노', '5,000원']
19
['커피', '3,000~5,000']
20
['아메리카노', '3,500원']
21
['아메리카노', '2,000원']
['아이스 아메리카노', '2,500원']
22
23
24
25
['아메리카노', '4,800원']
26
['아메리카노', '3,000원']
27
['아메리카노', '2,000원']
28
29
30
31
['아메리카노', '4,300원']
32
33
['아메리카노', '5,000원']
34
['아메리카노', '5,000원']
35
36
['카페 아메리카노', '3,200원']
37
38
['아메리카노', '3,000원']
39
['아메리카노', '3,300원']
40
41
42
['아메리카노', '4,000원']
43
['아메리카노', '4,500원']
44
['아메리카노', '3,500원']
45
['아메리카노', '5,000원']
46
['아메리카노', '4,000원']
47
48
49
50
['아메리카노', '3,800원']
51
52
['아메리카노', '3,000원']
53
['아메리카노', '5,000원']
54
['카페 아메리카노', '4,500원']
55
['아메리카노', '4,300원']
56
['아메리카노', '5,000원']
57
['아메리카노', '4,600원']
58
['아메리카노', '4,500원']
['카페아메리카노', '4,500원']
59
60
61
62
['아메리카노', '5,000원']
63
['카페 아메리카노', '4,500원']
64
65
66
['아메리카노', '4,000원']
67
68
['아메리카노', '4,500원']
69
['아메리카노', '4,800원']
70
['콜드브루 아메리카노', '4,800원']
71
['프루티 아메리카노', '6,500원']
72
['아메리카노(HOT)', '3,000원']
['아메리카노(ICE)', '3,500원']
73
74
['아메리카노', '2,500원']
75
76
['아메리카노 (펠트)', '4,500원']
77
78
['아메리카노(HOT)', '2,500원']
['아메리카노(ICE)', '3,000원']
79
['아메리카노', '3,000원']
80
81
82
['아메리카노', '1,500원']
83
['아메리카노', '3,000원']
84
['아메리카노', '2,500원']
85
86
['카페 아메리카노', '4,500원']
87
['아이스아메리카노', '2,000원']
88
['(L)HOT 카페 아메리카노', '3,200원']
['(L)ICED 카페 아메리카노', '3,200원']
['(EX)HOT 카페 아메리카노', '4,200원']
['(EX)ICED 카페 아메리카노', '4,200원']
['비니스트디카페인아메리카노(20T)', '4,700원']
['비니스트디카페인아메리카노(80+20T)', '16,400원']
89
90
['아메리카노', '4,300원']
['벨벳아메리카노', '5,300원']
91
92
['아메리카노', '3,000원']
93
['아메리카노(HOT)', '2,400원']
['아메리카노(ICE)', '2,400원']
94
95
['빅사이즈 아메리카노', '2,500원']
96
97
['아메리카노', '3,800원']
98
['아메리카노(싱글오리진)', '4,800원']
99
['아이스아메리카노', '2,000원']
100
['아메리카노', '4,000원']
101
['아메리카노', '3,800원']
102
['아메리카노', '1,500원']
103
104
105
106
['아메리카노', '2,500원']
107
['아메리카노', '4,000원']
['더치아메리카노', '4,500원']
108
['커피', '3,000원']
109
110
['아메리카노', '2,000원']
111
['아메리카노 R', '3,800원']
['아메리카노 L', '4,800원']
112
['카페 아메리카노', '4,500원']
113
['아메리카노', '4,500원']
114
['아메리카노 (hot/iced)', '4,000원']
115
['카페 아메리카노', '3,200원']
116
['아메리카노', '4,000원']
117
118
['아메리카노', '4,500원']
119
['아메리카노', '4,000원']
['연한 아메리카노', '3,500원']
120
['핫아메리카노', '1,500원']
121
['커피', '3,500원']
122
123
124
125
['B 빅 아메리카노(4샷)', '4,600원']
['B 빅 아메리카노(4샷)(1L)', '4,600원']
['B 헤이즐넛아메리카노(1L)', '5,300원']
['B 대만흑당  아메리카노(1L)', '5,800원']
126
['아메리카노', '4,500원']
127
128
['아메리카노 HOT/ICE', '3,400원']
129
['아메리카노', '3,500원']
130
131
['아메리카노', '5,500원']
132
['아메리카노', '4,300원']
133
['아메리카노', '4,000원']
134
135
136
['아메리카노', '2,500원']
137
['세븐레이크 아메리카노', '3,300원']
['랑케블랙 아메리카노', '3,000원']
138
['아메리카노 4+1(ICED ONLY(500ml))', '15,600원']
['아메리카노 [ Americano ]', '3,900원']
['아메리카노 1L', '7,300원']
139
['아메리카노', '3,500원']
140
['[하루 10개 한정세트] 아메리카노 4캔+백억떡 4개([2,600원 저렴합니당])', '19,000원']
['[아메리카노 4캔 행사중입니다]', '14,000원']
['[냉장 보관용] 아메리카노 (얼음X)(2+1 아메리카노 (얼음X))', '10,000원']
['[냉장 보관용] 아메리카노 (얼음X)(5+1 아메리카노 (얼음X))', '20,000원']
['[냉장 보관용] 아메리카노 (얼음X)(9+1 아메리카노 (얼음X))', '32,000원']
['아메리카노(ICE(500ml캔))', '3,900원']
['아메리카노(HOT(355ml캔))', '3,900원']
['아메리카노(얼음빼주세요(355ml캔))', '3,900원']
141
142
['아메리카노', '3,300원']
['아메리카노 to go', '2,800원']
143
144
['아메리카노', '4,800원']
145
['카페 아메리카노', '4,500원']
146
147
148
149
['카페 아메리카노', '4,500원']
150
['아메리카노', '5,000원']
151
['카페 아메리카노', '3,200원']
152
['아메리카노', '3,900원']
153
154
155
['아메리카노 HOT/ICE', '3,900원']
156
['아메리카노', '3,800원']
157
['카페아메리카노', '3,800원']
['헤이즐넛 아메리카노', '5,000원']
158
159
['아메리카노', '2,500원']
160
161
162
['카페 아메리카노', '4,500원']
163
['아메리카노', '3,000원']
164
['빽사이즈 아메리카노(ICED)', '3,500원']
['아메리카노(HOT)', '1,800원']
['아메리카노(ICED)', '2,300원']
165
['(V)아이스 아메리카노', '5,500원']
['(R)아메리카노', '4,500원']
['(R)아이스 아메리카노', '4,500원']
166
167
['아메리카노', '4,300원']
['디카페인아메리카노', '4,800원']
168
['에스프레소/아메리카노', '1,800원']
169
['카페 아메리카노', '4,100원']
170
171
['아메리카노', '2,500원']
172
173
174
['아메리카노', '2,500원']
175
['아메리카노', '3,000원']
176
['아메리카노', '2,800원']
177
['아메리카노(S)', '5,000원']
178
['아메리카노 (H/I)', '4,900~5,400']
179
['아메리카노', '5,000원']
['헤이즐넛 아메리카노', '5,300원']
180
['아메리카노', '4,800원']
181
['생아메리카노', '1,800원']
182
['아메리카노 hot', '4,000원']
183
['아메리카노 코나 블렌드', '4,200원']
['아메리카노 코나 100%', '6,000원']
184
185
186
['HOT 아메리카노', '4,000원']
['아이리쉬 아메리카노', '4,500원']
187
188
189
['아메리카노', '2,500원']
190
['아메리카노(Hot/Ice)', '3,500원']
191
['카페 아메리카노', '4,900원']
192
193
194
['아메리카노', '4,500원']
195
['아메리카노', '2,500원']
196
197
198
['아메리카노 M', '1,600원']
199
200
['아메리카노', '2,000원']
201
['아메리카노', '3,500원']
['디카페인아메리카노', '5,000원']
202
203
['아메리카노', '4,500원']
204
['아메리카노', '4,500원']
205
['아메리카노', '4,500원']
206
['아메리카노', '4,800원']
207
208
209
['아메리카노', '2,800원']
210
['americano', '3,800원']
211
212
213
['아메리카노', '2,000원']
214
215
216
['아메리카노', '4,400원']
217
['(HOT)아메리카노', '2,000원']
['(ICE)아메리카노', '2,500원']
['(HOT)헤이즐넛아메리카노', '3,200원']
['(ICE)헤이즐넛아메리카노', '3,200원']
['메가엠지씨스틱 오리지날 아메리카노', '4,600원']
['메가엠지씨스틱 디카페인 아메리카노', '5,400원']
218
219
['아메리카노', '3,500원']
220
['아메리카노', '2,500원']
221
['아메리카노', '2,500원']
222
['아메리카노', '3,800원']
223
['아메리카노', '5,000원']
224
225
226
['아메리카노', '4,000원']
227
['아메리카노', '5,000원']
228
['카페 아메리카노', '5,000원']
229
230
['아메리카노', '5,500원']
231
232
233
234
['아메리카노', '4,000원']
235
['카페 아메리카노', '3,200원']
236
['시나몬 아메리카노', '2,900원']
['아메리카노', '2,200원']
237
238
['콜드브루 아메리카노', '4,500원']
['커피', '4,300원']
239
240
['아메리카노', '4,000원']
241
242
['아메리카노', '3,400원']
243
244
245
['아메리카노', '4,500원']
246
247
248
['아메리카노', '1,500원']
249
250
['아이스아메리카노', '3,800원']
251
['아메리카노', '3,000원']
252
['아메리카노', '2,900원']
253
254
['아메리카노', '3,000원']
255
['아메리카노', '2,900원']
256
['오츠 아메리카노', '4,500원']
257
258
['아메리카노', '4,000원']
259
['아메리카노', '3,500원']
260
['카페 아메리카노', '4,500원']
261
['카페 아메리카노', '4,500원']
262
['아메리카노', '3,500원']
263
['아메리카노', '4,400원']
264
265
['아메리카노 - hot', '4,500원']
266
['빽사이즈 아메리카노(ICED)', '3,500원']
['아메리카노(HOT)', '1,800원']
['아메리카노(ICED)', '2,300원']
267
268
['카페 아메리카노', '3,200원']
269
270
271
['아메리카노', '4,000원']
272
273
['아메리카노', '4,000원']
274
275
['아메리카노', '4,500원']
276
['아메리카노', '2,800원']
277
['아메리카노', '4,500원']
278
['아메리카노', '2,000원']
279
280
['유기농 아메리카노', '4,000원']
281
282
['아메리카노', '4,500원']
283
['아메리카노', '3,900원']
284
['아메리카노', '5,000원']
285
['아메리카노(다크/미디움)', '2,500원']
286
['아메리카노', '2,900원']
287
288
289
['유자아메리카노', '6,000원']
['아메리카노', '4,000원']
290
['카페 아메리카노', '4,500원']
291
292
['아메리카노', '1,500원']
293
['아메리카노(일반)', '3,500원']
294
295
296
['아메리카노', '2,000원']
297
['아메리카노', '3,200원']
298
299
['아메리카노', '3,000원']
300
301
['아메리카노', '1,000원']
302
303
304
305
['아메리카노', '1,500원']
306
['아메리카노', '1,700원']
307
['아메리카노', '2,000원']
308
['아메리카노 ', '1,500원']
309
['아메리카노', '3,000원']
310
['아메리카노', '2,300원']
311
312
['아메리카노', '2,000원']
313
['아메리카노', '2,500원']
314
['아메리카노', '2,500원']
315
316
317
['아메리카노', '3,500원']
318
['아메리카노', '3,500원']
319
['아메리카노', '2,000원']
320
['아메리카노', '3,500원']
321
322
323
['아메리카노', '4,500원']
324
325
326
['아메리카노', '2,500원']
327
['아메리카노', '3,000원']
328
['아메리카노', '3,000원']
329
330
['카페 아메리카노', '4,500원']
331
['아메리카노', '1,500원']
332
333
334
['제로슈가 스위트 아메리카노', '3,000원']
['아메리카노', '2,500원']
['시그니처 아메리카노', '2,700원']
['헤이즐넛 아메리카노', '3,000원']
['허니아메리카노', '3,000원']
335
['아메리카노', '3,000원']
336
['아이스 아메리카노 M', '1,400원']
337
['아메리카노', '2,700원']
338
['아메리카노', '1,500원']
['아이스아메리카노', '1,900원']
339
340
['아메리카노', '1,800원']
['1리터 보틀 아메리카노', '4,200원']
['아메리카노(디카페인)', '2,800원']
341
342
['아메리카노 (세가지 블렌드 중 택)', '4,000원']
343
['아메리카노', '3,000원']
344
['아메리카노', '4,800원']
345
['아메리카노(R)', '4,500원']
346
['아메리카노', '3,500원']
347
348
['아메리카노', '5,000원']
349
['아메리카노', '3,000원']
350
351
['아메리카노', '4,500원']
352
['카페 아메리카노', '4,500원']
353
354
355
['카페 아메리카노', '3,200원']
356
['아메리카노', '3,000원']
357
['카페 아메리카노', '4,500원']
358
359
['1리터 아메리카노', '3,000원']
['아메리카노', '1,800원']
['코코넛 아메리카노 L', '2,000원']
360
['아메리카노', '3,300원']
361
['아메리카노', '5,000원']
362
['아메리카노ICE(리유저블컵)(IASO원두(Medium))', '4,500원']
363
364
['아메리카노', '4,500원']
365
['아메리카노', '4,500원']
366
['아메리카노', '4,000원']
367
['아메리카노', '4,500원']
368
['아메리카노(HOT/ICE)', '4,500원']
369
['아메리카노 (HOT/ICE)', '5,000원']
['크림 아메리카노(HOT/ICE)', '5,500원']
370
371
['아메리카노', '6,000원']
372
['아메리카노(hot)', '4,500원']
['아메리카노(ice)', '5,000원']
373
['(NO.1) 아메리카노', '3,000원']
['헤이즐넛아메리카노', '3,500원']
374
['아메리카노', '4,500원']
375
['카페 아메리카노', '3,200원']
376
['아메리카노', '2,000원']
377
378
['아메리카노', '3,500원']
379
['아메리카노', '4,300원']
380
['아메리카노 L 사이즈', '2,800원']
381
['아메리카노 ,D(ICE(2샷))', '3,800원']
382
383
384
['아메리카노', '3,300원']
385
['카페 아메리카노', '4,500원']
386
['아메리카노', '4,300원']
387
388
['커피', '3,000~5,000']
389
['아메리카노', '3,500원']
390
['아이스아메리카노', '3,000원']
391
['아메리카노 HOT/ICED', '4,500원']
392
['아메리카노', '4,000원']
393
['아메리카노', '4,000원']
394
['아메리카노', '2,000원']
['1리터 아메리카노(only ICE)', '3,500원']
['꿀 아메리카노', '3,300원']
['치즈크림 아메리카노(only ICE)', '4,300원']
395
['아메리카노', '2,800원']
396
397
['아메리카노', '3,500원']
398
['카페 아메리카노', '4,500원']
399
['카페 아메리카노', '4,500원']
400
['(L)HOT 카페 아메리카노', '3,200원']
['(L)ICED 카페 아메리카노', '3,200원']
['(EX)HOT 카페 아메리카노', '4,200원']
['(EX)ICED 카페 아메리카노', '4,200원']
['비니스트디카페인아메리카노(20T)', '4,700원']
401
['아메리카노', '3,500원']
402
403
['아메리카노', '1,500원']
404
405
['아메리카노', '2,000원']
406
['커피', '2,500원']
407
['아메리카노(HOT)', '3,500원']
408
['아메리카노', '1,900원']
409
['아메리카노', '1,500원']
410
['아메리카노', '4,800원']
411
['아메리카노', '3,500원']
412
413
414
['아메리카노', '5,300원']
415
['카페 아메리카노', '4,500원']
416
['아메리카노', '4,100원']
417
['아메리카노', '1,500원']
418
419
420
421
['아메리카노(ICE+500원)', '2,500원']
422
['아메리카노', '4,000원']
423
424
425
426
['아메리카노', '4,000원']
427
428
['아메리카노', '5,500원']
429
['아메리카노', '5,000원']
430
['아메리카노', '6,000원']
431
['아메리카노', '4,500원']
432
433
434
['커피', '변동']
435
['아메리카노', '5,000원']
436
['아메리카노', '4,000원']
437
438
['아메리카노', '3,500원']
439
440
441
['아메리카노', '3,800원']
442
443
444
['아메리카노', '3,500원']
['꿀아메리카노', '4,300원']
445
446
447
448
['아메리카노', '3,500원']
449
450
['아메리카노', '5,500원']
451
452
['디카페인 아메리카노', '4,800원']
['아메리카노', '4,000원']
453
['아메리카노', '4,500원']
454
['아메리카노 Americano', '4,000원']
455
['아메리카노', '4,800원']
456
457
['아메리카노', '변동']
458
['아메리카노', '4,000원']
459
['아메리카노', '2,900원']
460
['아메리카노', '4,000원']
461
['아메리카노', '4,000원']
462
463
['아메리카노', '4,000원']
464
['카페 아메리카노', '3,200원']
465
466
['아메리카노', '3,000원']
467
468
469
['아메리카노', '3,800원']
470
['아메리카노', '3,500원']
471
['아메리카노', '3,500원']
['헤이즐넛 아메리카노', '4,000원']
472
['아메리카노', '2,500원']
['코코넛워터 아메리카노', '3,500원']
473
['아메리카노', '3,500원']
474
475
476
['아메리카노', '5,000원']
477
['아메리카노', '4,500원']
478
['아메리카노', '6,000원']
479
480
481
['아메리카노', '4,500원']
482
483
484
['아메리카노', '3,800원']
485
['americano', '4,300원']
486
['아메리카노', '3,000원']
487
['아메리카노', '3,300원']
488
489
['아메리카노', '4,000원']
490
['아메리카노', '2,500원']
491
492
493
['아메리카노', '4,000원']
494
['아메리카노', '2,000원']
495
['카페 아메리카노', '4,500원']
496
497
['아메리카노', '5,000원']
498
499
500
['아메리카노', '6,200원']
['헤이즐넛 아메리카노', '6,500원']
501
502
['아메리카노', '5,000원']
503
['아메리카노', '4,300원']
504
['아메리카노', '3,800원']
505
['Hot 아메리카노', '5,000원']
['Iced 아메리카노', '5,000원']
506
507
508
['아메리카노', '6,000원']
509
['아메리카노', '4,500원']
510
['아메리카노', '5,000원']
511
512
513
['아메리카노 Americano', '5,000원']
514
['아메리카노', '3,300원']
515
['아메리카노', '5,000원']
516
['아메리카노', '4,000원']
517
518
['아메리카노', '4,200원']
519
['아메리카노', '5,000원']
520
['아메리카노 AMERICANO', '3,500원']
521
['아메리카노', '3,800원']
['헤이즐넛 아메리카노', '4,000원']
522
['아메리카노', '5,000원']
523
['아메리카노', '4,500원']
524
525
['아메리카노', '5,000원']
526
['아메리카노', '5,000원']
527
528
['아메리카노', '4,500원']
529
['카페 아메리카노', '4,500원']
530
531
['아메리카노(R)', '4,500원']
532
['빽사이즈 아메리카노(ICED)', '3,500원']
['아메리카노(HOT)', '1,800원']
['아메리카노(ICED)', '2,300원']
533
534
['아메리카노', '4,600원']
535
536
['아이스아메리카노', '4,500원']
537
['아메리카노 - TWO', '4,600원']
['아메리카노 - XIX', '4,900원']
538
539
540
541
['아메리카노(ICED OR HOT)', '3,800원']
542
['카페 아메리카노', '4,500원']
543
['카페 아메리카노', '3,200원']
544
['카페 아메리카노', '4,500원']
545
['아메리카노', '5,500원']
546
['아메리카노', '변동']
547
['아메리카노', '1,400원']
548
['아메리카노(2샷)', '2,900원']
549
550
['Americano 아메리카노', '5,000원']
551
['카페 아메리카노', '4,500원']
552
553
554
['아메리카노', '4,500원']
555
['아메리카노', '5,000원']
556
557
['아메리카노', '5,000원']
558
559
560
['아메리카노', '3,500원']
561
['아메리카노', '4,500원']
['아메리카노 아이스', '4,500원']
562
['아메리카노', '4,800원']
['아이스아메리카노', '5,500원']
563
['아메리카노', '4,000원']
564
565
566
['아메리카노', '4,500원']
['디카페인 아메리카노', '5,000원']
567
['아메리카노Americano', '4,500원']
568
569
570
['아메리카노', '7,000원']
571
['아메리카노', '5,800원']
572
573
['아메리카노', '4,000원']
574
575
576
577
['아메리카노', '5,000원']
578
['아메리카노', '4,500원']
579
['아메리카노', '4,500원']
580
['마카롱 아이스크림 샌드위치+아메리카노', '9,000원']
['아메리카노', '4,000원']
581
582
['아메리카노', '5,000원']
583
584
585
['아메리카노', '5,000원']
586
587
['아메리카노', '6,000원']
588
['아메리카노 R', '3,800원']
589
590
['아메리카노', '4,500원']
591
['아메리카노', '4,500원']
592
593
594
['아메리카노 (ICE)', '4,000원']
['아메리카노 (HOT)', '4,000원']
595
596
['아메리카노', '4,000원']
597
598
599
['아메리카노', '5,000원']
600
601
602
603
604
605
['아메리카노', '4,000원']
606
607
608
['아메리카노', '4,500원']
609
['아메리카노', '5,000원']
610
611
['아메리카노', '8,000원']
612
613
['아메리카노', '5,000원']
614
615
['카페 아메리카노', '4,100원']
616
617
['아메리카노', '4,000~4,300']
618
619
620
['americano', '7,000원']
621
['아메리카노', '변동']
622
['아메리카노', '4,000원']
623
['아메리카노', '5,300원']
['아이스아메리카노', '5,800원']
624
['아메리카노', '4,500원']
625
['빽사이즈 아메리카노(ICED)', '3,500원']
['아메리카노(HOT)', '1,800원']
['아메리카노(ICED)', '2,300원']
626
['아메리카노', '3,500원']
627
628
629
630
['아메리카노', '2,800원']
631
['ICE/HOT 카페 아메리카노', '2,500원']
632
633
['아메리카노', '3,000원']
634
['아메리카노(HOT)', '3,000원']
635
636
637
['아메리카노 HOT', '5,300원']
['아메리카노 ICE', '5,800원']
638
639
640
641
['아메리카노(S)', '5,000원']
642
643
644
645
['아메리카노', '4,000원']
646
647
['아이스 아메리카노', '3,000원']
648
['아메리카노', '3,800원']
649
['아메리카노', '3,500원']
650
651
['아이스아메리카노+ B.E.L.T 샌드위치', '9,800원']
['아이스아메리카노+리얼브라우니', '6,500원']
652
653
654
['아메리카노', '4,500원']
655
656
['카페 알롱제(아메리카노)', '4,500원']
657
['아메리카노', '4,600원']
658
659
['아메리카노', '5,500원']
660
661
662
['아이스 아메리카노', '7,000원']
663
664
665
666
['아메리카노', '4,000원']
667
['아메리카노', '1,500원']
668
['Hot 아메리카노', '4,000원']
['Iced)아메리카노(480ml)', '4,000원']
669
['아메리카노(ice)', '4,300원']
670
671
['아메리카노hot', '2,000원']
['아메리카노ice', '2,500원']
672
['아메리카노', '2,500원']
673
674
675
['아메리카노', '5,000원']
676
677
['아메리카노', '4,500원']
678
['아메리카노', '6,000원']
679
680
681
['아메리카노', '5,000원']
682
683
['아메리카노', '17,000원']
684
685
686
687
['아메리카노', '5,000원']
688
689
690
691
['아메리카노', '5,000원']
692
693
694
695
696
['아메리카노', '4,900원']
['디카페인 아메리카노', '5,400원']
697
698
699
['카페 아메리카노', '4,500원']
700
['아메리카노', '5,000원']
701
702
703
['아메리카노', '5,300원']
704
['아메리카노', '4,500원']
705
706
707
708
['아메리카노', '5,000원']
709
['Black (아메리카노)', '5,000원']
710
711
712
713
714
715
716
717
718
['아메리카노', '6,000원']
719
720
721
722
['아메리카노', '5,200원']
723
724
725
['아메리카노', '4,100원']
726
727
728
729
730
731
732
['아메리카노 HOT', '4,300원']
['아메리카노 iced', '4,800원']
733
734
735
['아메리카노', '4,500원']
736
['아메리카노', '4,500원']
737
['아메리카노', '2,500원']
738
['카페 아메리카노', '4,500원']
739
['아메리카노HOT', '1,500원']
['아메리카노ICE', '2,000원']
740
['아메리카노_달콤 시그니처', '4,100원']
741
['아메리카노', '4,500원']
742
['카페 아메리카노', '3,200원']
743
['아메리카노', '1,000원']
744
745
746
747
['아메리카노', '3,500원']
748
['Americano (아메리카노)', '5,500원']
749
['아메리카노', '4,000원']
750
751
['아메리카노', '3,200원']
752
753
['americano (ice +200)', '4,600원']
754
['아메리카노 H/I', '4,500원']
755
756
['아메리카노', '2,500원']
757
758
759
['아메리카노', '4,500원']
760
761
762
['아메리카노', '3,500원']
763
764
['아메리카노', '6,000원']
765
['카페 아메리카노', '4,500원']
766
['아메리카노', '6,000원']
767
768
['아메리카노', '4,300원']
769
770
771
['아메리카노', '3,000원']
772
['아메리카노', '3,500원']
773
774
775
776
['아메리카노 핫', '3,000원']
777
['아메리카노', '2,500원']
778
779
780
['아이스아메리카노+ B.E.L.T 샌드위치', '10,000원']
['아이스아메리카노+리얼브라우니', '6,500원']
781
782
783
784
['아메리카노', '4,500원']
785
786
['아이스 아메리카노', '3,700원']
['아메리카노', '3,200원']
787
788
789
['아메리카노', '변동']
790
791
792
793
794
795
796
['아메리카노', '3,800원']
797
798
['아메리카노', '3,900원']
799
['아메리카노', '2,700원']
800
['아메리카노', '5,000원']
801
['아메리카노 + 시오빵 + 시오 카야버터', '10,200원']
['아메리카노', '3,500원']
['헤이즐넛 아메리카노', '4,000원']
['아메리카노 (보틀)', '8,000원']
['헤이즐넛 아메리카노 (보틀)', '9,000원']
['콜드브루 아메리카노', '5,000원']
802
803
['카페아메리카노', '4,100원']
804
805
806
807
808
['그랑드카페 아메리카노(HOT)', '3,500원']
['그랑드카페 아이스아메리카노', '3,500원']
809
['아메리카노(hot/ice)', '3,000원']
810
811
['아메리카노', '3,000원']
812
813
['커피', '2,500원']
814
815
816
817
818
['아이스 아메리카노', '3,800원']
['아메리카노', '3,600원']
819
['아메리카노', '3,800원']
820
821
822
['아메리카노', '4,300원']
823
824
825
826
827
828
['아이스 아메리카노', '3,700원']
['아메리카노', '3,200원']
829
830
831
832
833
['아메리카노 R', '2,500원']
834
835
836
['아메리카노', '2,000원']
837
838
839
840
841
['아메리카노', '2,500원']
['눈꽃아메리카노', '3,500원']
842
843
['아메리카노', '3,500원']
['디카페인 아메리카노', '4,500원']
['헤이즐넛 아메리카노', '4,000원']
844
['아메리카노', '3,800원']
845
846
847
848
849
850
['아이스 아메리카노', '3,700원']
['BIG 아이스 아메리카노', '4,300원']
['아메리카노', '3,200원']
851
['아메리카노(ICE)', '3,500원']
852
['아메리카노', '4,500원']
853
854
855
856
['아이스 아메리카노', '4,500원']
857
858
['아아스아메리카노', '3,000원']
859
860
861
862
['아메리카노', '4,500원']
863
['아메리카노', '4,000원']
864
['아메리카노', '4,000원']
865
['아메리카노 hot', '3,000원']
866
867
['아메리카노', '1,500원']
868
['아메리카노', '4,000원']
869
['아메리카노 (핫)', '2,500원']
870
['아메리카노', '3,000원']
871
['아메리카노', '4,100원']
872
873
874
['아메리카노', '2,500원']
875
['아메리카노(고소한 원두)', '3,800원']
876
['아메리카노', '4,500원']
877
['아메리카노', '2,000원']
878
879
880
['아메리카노', '1,500원']
881
['카페 아메리카노', '3,000원']
882
883
['아메리카노', '4,000원']
884
885
['아메리카노(Ice)', '4,500원']
['아메리카노(Hot)', '4,500원']
886
887
['아메리카노', '4,000원']
888
['아메리카노', '4,800원']
889
['아메리카노', '3,000원']
890
['아메리카노(UP)', '2,700원']
['크로플 + 아메리카노', '10,000원']
891
['아메리카노', '4,700원']
892
893
['ICE 아메리카노', '4,000원']
['HOT 아메리카노', '3,500원']
894
895
896
['아메리카노', '3,800원']
897
['아메리카노 S', '1,200원']
898
899
['아메리카노', '4,000원']
900
['아메리카노', '4,000원']
901
['아메리카노', '2,500원']
902
['americano', '3,500원']
903
['아메리카노', '2,500원']
904
905
906
907
908
['아메리카노', '2,500원']
909
['아메리카노', '4,000원']
['1L아메리카노', '6,000원']
910
['아메리카노', '4,000원']
911
['아메리카노', '3,500원']
912
913
914
915
['아메리카노', '2,000원']
916
['아메리카노', '4,500원']
917
['아메리카노', '5,000원']
918
919
['아메리카노', '5,000원']
920
921
['아메리카노 HOT', '2,000원']
['아메리카노 ICE', '2,500원']
922
923
924
['아메리카노', '2,500원']
925
926
['아메리카노', '3,800원']
927
['(HOT)디카페인 아메리카노', '2,800원']
928
929
930
931
932
['카페 아메리카노', '4,500원']
933
934
['아메리카노 hot', '2,500원']
['아메리카노 ice', '3,000원']
935
936
['아메리카노', '2,000원']
937
['아메리카노', '4,500원']
938
['카페 아메리카노', '4,500원']
939
['카페 아메리카노', '4,500원']
940
941
942
943
['아메리카노/카페라떼/바닐라/연유라떼', '변동']
944
['카페 아메리카노', '4,500원']
945
946
947
948
949
950
['아메리카노', '3,000원']
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
['아메리카노(핫)', '3,000원']
['아메리카노(아이스)', '3,500원']
966
967
968
['아메리카노', '4,000원']
969
['아메리카노 (아이스)', '6,500원']
['아메리카노', '6,000원']
970
971
972
['아메리카노/에스프레소', '5,000원']
973
974
['아메리카노 클래식 h', '4,500원']
['아메리카노 클래식 i', '5,000원']
['아메리카노 어센틱 h', '5,000원']
['아메리카노 어센틱 i', '5,500원']
975
['커피', '3,000원']
976
['아메리카노', '4,000원']
977
978
979
980
['[HIVE]아이스 아메리카노', '4,400원']
['[HIVE]아메리카노', '4,400원']
981
['아메리카노', '5,000원']
982
983
['아메리카노', '1,900원']
984
['아메리카노', '5,000원']
985
['아메리카노', '5,000원']
986
987
['아메리카노', '4,500원']
988
989
990
991
['아메리카노', '4,500원']
992
993
['아메리카노', '5,300원']
994
995
996
['중복으로 선택하셔도 하나만나가용((후기약속)아메리카노ICE(얼음O))', '500원']
['중복으로 선택하셔도 하나만나가용((후기약속)아메리카노ICE(얼음X))', '500원']
['중복으로 선택하셔도 하나만나가용((후기약속)아메리카노HOT)', '500원']
['아메리카노(ICE(얼음O))', '4,500원']
['아메리카노(ICE(얼음X))', '4,500원']
['아메리카노(HOT)', '4,500원']
997
['카페 아메리카노', '4,500원']
998
999
['카페 아메리카노', '4,500원']
1000
1001
1002
1003
1004
1005
['카페 아메리카노', '4,900원']
1006
1007
['아메리카노+와플/크로폴(택1)', '6,500원']
1008
['아메리카노', '3,500원']
1009
1010
1011
1012
['(캔) LS 아이스 아메리카노', '3,700원']
['LS 아이스 아메리카노', '3,700원']
1013
1014
1015
1016
['아메리카노(M)', '4,200원']
['아이스 아메리카노(M)', '4,200원']
['아이스 아메리카노(L)', '4,700원']
['아이스 아메리카노(XL)', '5,700원']
1017
1018
1019
1020
1021
1022
1023
['카페 아메리카노', '4,900원']
1024

In [ ]:
index2 = []
latte = []
for i in range(len(menu2)):
  print(i)
  for j in range(len(menu2['네이버 메뉴'][i])):
    if menu2['네이버 메뉴'][i][j][0].find("카페라떼") != -1:
      print(menu2['네이버 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['네이버 메뉴'][i][j])
    if menu2['네이버 메뉴'][i][j][0].find("카페 라떼") != -1:
      print(menu2['네이버 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['네이버 메뉴'][i][j])
    if menu2['네이버 메뉴'][i][j][0] == "라떼":
      print(menu2['네이버 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['네이버 메뉴'][i][j])
    if menu2['네이버 메뉴'][i][j][0].find("latte") != -1 :
      print(menu2['네이버 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['네이버 메뉴'][i][j])

0
1
2
3
4
['카페 라떼', '4,200원']
5
['카페라떼', '3,500원']
6
7
['카페라떼', '4,000원']
8
['카푸치노 / 카페라떼', '3,800원']
9
10
['아이스카페라떼', '4,500원']
11
['카페라떼', '4,500원']
12
13
['카페라떼(HOT)', '4,300원']
14
15
16
17
18
['카페라떼', '5,500원']
19
20
['카페라떼', '4,000원']
21
22
23
['카페라떼', '4,500원']
['흑당카페라떼', '5,000원']
24
25
['카페라떼', '5,300원']
26
27
28
29
['라떼', '5,500원']
30
31
['라떼', '4,800원']
32
33
['카페라떼', '5,500원']
34
35
36
['카페 라떼', '4,200원']
37
38
39
['카페라떼', '3,800원']
40
41
42
43
44
45
['카페라떼', '5,500원']
46
['카페라떼', '5,000원']
47
48
49
50
51
52
['카페라떼', '4,000원']
53
54
['카페 라떼', '5,000원']
55
['카페라떼', '5,000원']
56
['카페라떼', '5,500원']
57
58
['바닐라카페라떼/카페모카', '5,500원']
['카페라떼/카푸치노', '5,000원']
59
['카페 라떼', '5,500원']
60
['카페라떼 (Standard)', '5,700원']
61
62
63
['카페 라떼', '5,200원']
64
65
66
['카페 라떼', '4,700원']
67
['크림 달고나 카페라떼', '변동']
68
69
['카페라떼', '5,300원']
70
71
72
['HOT 카페라떼', '4,000원']
73
74
['카페라떼', '3,200원']
75
76
77
78
['카페라떼 (HOT)', '3,500원']
['카페라떼 (ICE)', '4,000원']
79
['카페라떼', '4,000원']
80
81
82
83
84
['카페라떼', '3,300원']
85
86
['카페 라떼', '5,000원']
87
88
89
90
['카페라떼', '4,900원']
91
92
['카페라떼', '4,000원']
93
94
95
96
97
98
99
100
['카페라떼', '5,000원']
101
102
103
104
105
106
['카페라떼', '3,000원']
107
['라떼', '4,500원']
108
109
110
['카페라떼', '3,800원']
111
['카페라떼 R', '4,300원']
['카페라떼 L', '5,300원']
112
['카페 라떼', '5,000원']
113
['카페 라떼', '5,500원']
114
['카페라떼', '4,500원']
115
['카페 라떼', '4,200원']
116
['카페 라떼', '4,500원']
117
118
['카페라떼', '5,000원']
119
120
['핫카페라떼', '2,500원']
['아이스카페라떼', '2,500원']
121
122
123
124
125
['B 카페라떼(4샷)(1L)', '6,000원']
126
['카페라떼', '5,000원']
127
128
129
130
131
['카페라떼', '6,500원']
132
['카페라떼', '4,800원']
133
['카페라떼', '4,500원']
134
135
136
['카페라떼', '3,500원']
137
['세븐레이크 카페라떼', '3,800원']
['랑케블랙 카페라떼', '3,500원']
138
['카페라떼 [ Caffe Latte ]', '4,500원']
['카페라떼 1L', '8,500원']
139
140
['[카페라떼 4캔 행사중입니다]', '16,000원']
['카페라떼(ICE(500ml캔))', '4,400원']
['카페라떼(HOT(355ml캔))', '4,400원']
141
142
143
144
['카페라떼', '5,800원']
145
['카페 라떼', '5,000원']
146
147
148
149
['카페 라떼', '5,000원']
150
151
['카페 라떼', '4,200원']
152
['카페라떼', '4,700원']
153
154
['Vanila latte', '4,800원']
['Salted caramel latte', '4,800원']
155
['카페라떼 HOT/ICE', '4,300원']
156
['카페 라떼', '4,300원']
157
['카페라떼', '4,500원']
['달고나 카페라떼', '6,000원']
158
159
['카페라떼', '3,000원']
160
161
162
['카페 라떼', '5,000원']
163
['카페라떼', '4,000원']
164
["빽사이즈 빽's카페라떼(ICED)", '5,000원']
["빽's카페라떼(HOT)", '3,500원']
["빽's카페라떼(ICED)", '3,500원']
165
['(V)아이스 카페라떼', '6,000원']
166
167
168
['카페라떼', '2,500원']
['바닐라카페라떼 핫', '3,000원']
169
['카페 라떼', '4,600원']
170
['얼그레이 카페라떼 + 펄', '4,900원']
['카라멜카페라떼 L', '4,500원']
['카라멜카페라떼 J', '5,600원']
['바닐라 카페라떼 L', '4,500원']
171
172
173
174
['카페라떼', '3,500원']
175
['카페라떼', '3,500원']
176
['카페라떼', '3,200원']
177
178
179
['카페라떼', '5,500원']
180
['카페라떼', '5,800원']
181
['생우유 카페라떼', '3,500원']
182
183
184
185
186
['카페라떼', '4,500원']
187
188
189
['카페라떼', '3,000원']
190
['카페라떼(Hot/Ice)', '4,000원']
191
['카페라떼', '5,400원']
192
193
194
['라떼', '5,000원']
195
196
197
198
['카페라떼 M', '2,700원']
199
200
['카페라떼', '3,500원']
201
['카페라떼', '4,500원']
202
203
204
205
206
['카페라떼', '5,300원']
207
208
209
['카페라떼', '3,500원']
210
211
212
['카페라떼', '4,000원']
213
['바닐라 카페라떼', '3,500원']
['카페라떼', '3,000원']
214
215
216
217
218
219
['카페라떼', '4,000원']
220
['카페라떼', '3,500원']
221
222
223
['카페라떼', '6,000원']
224
225
226
227
['카페라떼', '5,500원']
228
['카페라떼', '5,500원']
229
230
['카페 라떼', '6,000원']
231
232
233
['라떼', '5,000원']
234
['카페라떼', '4,500원']
235
['카페 라떼', '4,200원']
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
['카페라떼', '3,800원']
255
256
['카페라떼', '5,000원']
257
258
259
['카페 라떼', '4,000원']
260
['카페 라떼', '5,000원']
261
['카페 라떼', '5,200원']
262
263
['카페라떼', '5,000원']
264
265
266
["빽사이즈 빽's카페라떼(ICED)", '5,000원']
["빽's카페라떼(HOT)", '3,500원']
["빽's카페라떼(ICED)", '3,500원']
267
268
['카페 라떼', '4,200원']
269
270
271
['카페라떼', '4,500원']
272
273
['카페라떼', '4,500원']
274
['카페라떼', '3,800원']
275
['라떼', '5,000원']
276
['카페라떼/플랫화이트', '3,500원']
277
278
['카페라떼', '2,800원']
279
280
281
282
283
['라떼', '4,600원']
284
['카페라떼', '5,500원']
285
['카페라떼', '3,500원']
286
['카페 라떼', '4,000원']
287
288
289
['카페라떼비엔나', '6,000원']
['카페라떼', '5,500원']
290
['카페 라떼', '5,000원']
291
292
293
['카페라떼', '3,800원']
294
295
296
['카페라떼', '2,500원']
297
['스택빈 카페라떼', '4,000원']
298
299
['카페라떼', '4,000원']
300
301
302
303
304
305
306
['카페라떼', '2,400원']
307
['카페라떼', '2,500원']
308
309
310
['카페라떼', '2,800원']
311
312
['카페라떼', '2,500원']
313
314
315
316
317
318
['카페라떼', '4,000원']
319
320
['카페라떼', '4,000원']
321
322
323
324
325
326
['카페라떼', '3,400원']
327
['카페라떼', '3,500원']
328
['라떼', '4,000원']
329
330
['카페 라떼', '5,000원']
331
332
333
334
['카페라떼', '3,300원']
335
['카페라떼', '3,300원']
336
337
338
['카페라떼', '2,300원']
339
340
341
342
['카페라떼 (세가지 블렌드 중 택)', '4,500원']
343
344
345
['카페라떼(R)', '5,000원']
['바닐라카페라떼(R)', '5,500원']
['달고나카페라떼(R)', '6,000원']
346
['카페 라떼', '3,800원']
347
348
349
['라떼', '3,800원']
350
351
['카페라떼', '5,000원']
352
['카페 라떼', '5,000원']
353
354
355
['카페 라떼', '4,200원']
356
['카페라떼', '3,800원']
357
['카페 라떼', '5,200원']
358
359
['1리터 카페라떼', '4,000원']
['코코넛 카페라떼 L', '2,500원']
360
361
362
['녹차카페라떼(HOT)', '4,800원']
['녹차카페라떼(ICE)', '4,800원']
363
364
['카페라떼', '5,000원']
365
366
['카페라떼', '4,500원']
367
368
['카페라떼(HOT/ICE)', '5,000원']
369
['카페라떼 (HOT/ICE)', '5,500원']
['크림 카페라떼(HOT/ICE)', '6,000원']
370
371
['카페라떼', '6,500원']
372
['카페라떼(hot)', '5,000원']
373
['카페라떼', '3,500원']
374
['카페라떼', '5,000원']
375
['카페 라떼', '4,200원']
376
['카페라떼', '3,000원']
377
378
['카페라떼', '4,000원']
379
['라떼', '4,800원']
380
381
['카페라떼 ,D(ICE(2샷))', '4,300원']
382
383
384
385
['카페 라떼', '5,000원']
386
387
388
389
['카페라떼', '4,500원']
390
['카페라떼', '3,000원']
391
['카페라떼 HOT/ICED', '6,000원']
392
['카페라떼', '5,000원']
393
394
['카페라떼', '3,300원']
['꿀 카페라떼', '4,300원']
['치즈크림 카페라떼(only ICE)', '4,800원']
395
['카페라떼 HOT', '3,500원']
396
397
398
['카페 라떼', '5,000원']
399
['카페 라떼', '5,000원']
400
401
['카페라떼', '4,500원']
402
403
404
405
['라떼', '3,000원']
406
407
408
['카페라떼', '2,500원']
409
410
['카페라떼', '5,300원']
411
412
413
['크림 달고나 카페라떼', '변동']
414
415
['카페 라떼', '5,000원']
416
['스페니쉬 연유 카페라떼', '5,600원']
['바닐라 카페라떼 /카페모카', '5,100원']
['카페라떼/카푸치노', '4,600원']
417
418
419
420
421
422
['카페라떼', '4,600원']
423
424
425
426
['카페라떼', '4,500원']
427
428
429
430
431
432
['Nuttycream latte', '7,000원']
433
['핑크 카페라떼', '4,800원']
['그린 카페라떼', '4,800원']
['오렌지 카페라떼', '5,500원']
['바다 카페라떼', '5,500원']
434
435
['카페라떼', '5,500원']
436
['카페라떼', '4,500원']
437
438
439
440
441
442
443
444
['카페라떼', '4,000원']
445
446
447
448
['라떼', '4,000원']
449
450
['카페라떼', '6,000원']
451
452
453
['라떼', '5,000원']
454
['카페라떼 Cafe latte', '4,500원']
['카페라떼 Cafe latte', '4,500원']
455
456
457
['카페라떼', '변동']
458
459
460
['카페라떼', '4,500원']
461
['카페라떼', '4,500원']
462
463
464
['카페 라떼', '4,200원']
465
466
['카페라떼', '4,000원']
467
468
469
470
471
['카페라떼', '4,000원']
472
473
['카페라떼', '4,000원']
474
475
476
477
['카페라떼', '5,500원']
478
['카페라떼', '6,500원']
479
['카페라떼', '5,000원']
480
481
['카페라떼', '5,000원']
482
483
484
['카페라떼', '4,000원']
485
['vanilla latte', '5,000원']
486
487
488
489
['카페라떼', '4,500원']
490
['라떼', '3,000원']
491
492
493
494
['카페라떼', '3,000원']
495
['카페 라떼', '5,000원']
496
497
498
499
500
['카페라떼', '6,500원']
501
502
503
504
505
['Hot 카페라떼', '6,000원']
['Iced 카페라떼', '6,000원']
506
507
508
['카페라떼', '6,500원']
509
510
['카페라떼', '5,500원']
511
512
513
514
['카페라떼', '3,900원']
515
['카페라떼', '5,500원']
516
['카페라떼', '4,500원']
517
518
519
['카페라떼', '6,000원']
520
['카페라떼 CAFE LATTE', '4,500원']
521
['카페라떼', '4,200원']
522
['카페라떼', '6,000원']
523
['카페라떼', '5,500원']
524
525
['카페라떼', '5,500원']
526
['카페라떼', '6,000원']
527
['strawberry latte', '6,700원']
528
529
['카페 라떼', '5,000원']
530
531
532
["빽사이즈 빽's카페라떼(ICED)", '5,000원']
["빽's카페라떼(HOT)", '3,500원']
["빽's카페라떼(ICED)", '3,500원']
533
534
['카페라떼', '5,200원']
535
536
537
538
539
540
541
['코아시스 라떼(latte)', '4,500원']
542
['카페 라떼', '5,000원']
543
['카페 라떼', '4,200원']
544
['카페 라떼', '5,200원']
545
['카페라떼', '6,000원']
546
['카페라떼', '변동']
547
['카페라떼', '2,400원']
548
549
550
551
['카페 라떼', '5,000원']
552
553
554
['카페라떼', '5,000원']
555
['라떼', '5,500원']
556
557
['카페라떼', '5,500원']
558
559
['오트사이드 카페 라떼', '5,500원']
560
['카페라떼', '4,500원']
561
['카페라떼', '5,000원']
['카페라떼 아이스', '5,500원']
562
['카페라떼', '5,500원']
['아이스카페라떼', '6,000원']
563
564
565
566
['카페라떼', '5,000원']
567
568
['라떼', '5,500원']
569
570
571
572
['카페라떼', '6,000원']
573
['카페라떼', '4,500원']
574
575
576
577
578
['카페라떼', '5,000원']
579
['카페라떼', '5,500원']
580
['카페라떼', '4,500원']
581
582
583
584
585
['카페라떼', '5,500원']
586
587
588
589
590
['카페라떼', '5,500원']
591
['카페라떼', '5,300원']
592
593
594
['카페 라떼 (ICE)', '4,500원']
595
596
['카페라떼', '4,500원']
597
598
599
['카페라떼', '5,500원']
600
601
['카페라떼', '4,500원']
['오트카페라떼-비건라떼', '5,000원']
602
['카페라떼', '5,500원']
603
604
['카페라떼', '5,000원']
605
['카페라떼', '5,000원']
606
607
608
['라떼', '5,000원']
609
['카페라떼', '5,500원']
610
611
612
613
['카페 라떼', '5,500원']
614
['카페라떼', '5,500원']
615
['카페 라떼', '4,600원']
616
617
618
619
620
['latte', '7,500원']
621
622
623
['카페라떼', '5,500원']
624
['카페라떼', '5,000원']
625
["빽사이즈 빽's카페라떼(ICED)", '5,000원']
["빽's카페라떼(HOT)", '3,500원']
["빽's카페라떼(ICED)", '3,500원']
626
['카페라떼', '4,000원']
627
628
629
630
['카페라떼', '3,300원']
631
['ICE/HOT 카페 라떼', '3,000원']
632
633
['라떼', '4,500원']
634
['카페라떼', '3,500원']
635
636
637
638
639
640
641
642
643
644
645
['라떼', '4,500원']
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
['카페 라떼', '7,500원']
663
664
665
666
667
668
['Hot)카페라떼(300ml)', '5,000원']
['Iced)카페라떼(480ml)', '5,000원']
669
670
671
['카페라떼hot', '3,000원']
['카페라떼ice', '3,500원']
672
673
674
675
['카페라떼', '5,500원']
676
677
['라떼', '5,500원']
678
['카페라떼', '6,500원']
679
['카페라떼', '6,300원']
680
681
682
['Vanilla bean latte', '7,000원']
683
684
685
686
687
688
689
690
691
['카페라떼', '5,500원']
692
693
694
695
696
['카페라떼', '5,400원']
697
698
['카페라떼', '5,500원']
699
['카페 라떼', '5,000원']
700
['카페라떼', '5,500원']
701
702
703
704
['카페라떼', '5,000원']
705
706
707
708
['Cream choco latte', '6,500원']
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
['카페 라떼', '4,500원']
726
727
728
729
730
731
732
733
734
735
736
['라떼', '5,000원']
737
['카페라떼', '3,000원']
738
['카페 라떼', '5,000원']
739
740
741
['카페라떼', '5,000원']
742
['카페 라떼', '4,200원']
743
['카페라떼', '1,500원']
744
745
746
747
['카페라떼', '4,800원']
748
['Caffe Latte (카페라떼)', '6,000원']
749
['카페라떼', '4,500원']
750
751
752
['카페라떼', '7,000원']
753
['latte (ice +200)', '4,800원']
754
['카페 라떼 H/I', '5,000원']
755
['라떼', '4,500원']
756
['카페라떼', '3,500원']
757
758
759
['카페라떼', '5,000원']
760
761
762
['카페라떼', '3,800원']
763
764
['카페라떼', '6,500원']
765
['카페 라떼', '5,000원']
766
767
768
['카페라떼', '4,800원']
769
770
771
['카페라떼', '3,500원']
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
['카페라떼', '3,700원']
['아이스 카페라떼', '4,200원']
787
788
789
790
791
792
793
794
795
796
797
798
['카페라떼', '4,500원']
799
['카페라떼', '3,200원']
800
['카페라떼/카페모카/카라멜마끼아또/두유라떼', '5,500원']
801
['카페라떼', '4,500원']
['카페라떼 (보틀)', '10,000원']
802
803
804
805
806
807
808
['카페라떼 (HOT)', '3,900원']
['아이스카페라떼', '3,900원']
809
['카페라떼 (hot/ice)', '3,500원']
810
811
['라떼', '3,500원']
812
813
814
815
816
817
818
['아이스 카페라떼', '4,200원']
['카페라떼', '4,000원']
819
820
821
822
823
824
825
826
827
828
['카페라떼', '3,700원']
['아이스 카페라떼', '4,200원']
829
830
831
832
833
['카페라떼 R', '3,000원']
834
835
836
['카페라떼', '3,000원']
837
838
839
840
841
['카페라떼', '3,000원']
842
843
['카페라떼', '4,000원']
844
['카페라떼', '4,500원']
845
846
847
848
849
850
['카페라떼', '3,700원']
['아이스 카페라떼', '4,200원']
851
['카페라떼(ICE)', '4,000원']
852
853
854
855
856
857
858
['아이스 카페라떼', '3,500원']
859
860
861
862
['카페라떼', '5,000원']
863
864
['카페라떼', '4,500원']
865
866
['라떼', '6,000원']
867
['카페라떼', '3,000원']
868
869
870
['카페라떼', '3,500원']
871
['카페라떼', '4,600원']
872
873
874
['카페라떼', '4,000원']
875
['[LATTE](카페라떼)', '4,300원']
876
877
['카페라떼', '3,500원']
878
879
880
['카페라떼', '2,500원']
881
['카페 라떼', '4,000원']
882
883
['라떼', '4,500원']
884
885
['카페라떼(Ice)', '5,000원']
['카페라떼(Hot)', '5,000원']
886
887
['카페라떼', '4,500원']
888
['카페라떼', '5,300원']
889
['카페라떼', '3,500원']
890
['카페 라떼(톨사이즈)', '3,300원']
['카페 라떼(Size UP)', '3,800원']
['크로플 + 카페라떼', '11,000원']
891
['카페라떼', '5,200원']
892
893
894
895
896
897
898
899
['바닐라카페라떼', '4,800원']
900
['카페라떼', '5,000원']
901
['카페라떼', '4,000원']
902
['cafe latte', '4,000원']
903
['카페라떼', '3,000원']
904
905
906
907
908
909
['라떼', '4,500원']
910
['카페라떼', '4,500원']
911
['카페라떼', '4,500원']
912
['카페라떼HOT', '4,000원']
['카페라떼ICE', '4,500원']
913
914
915
916
['카페라떼', '5,500원']
917
918
919
920
['Salty cream latte', '5,500원']
921
922
923
924
['카페라떼', '3,000원']
925
['라떼', '5,500원']
926
927
['(HOT)디카페인 카페라떼', '3,300원']
928
929
930
931
932
['카페 라떼', '5,000원']
933
934
['카페라떼 hot', '3,500원']
['카페라떼 ice', '4,000원']
935
936
['카페라떼', '3,000원']
937
['라떼', '4,500원']
938
['카페 라떼', '5,000원']
939
['카페 라떼', '5,000원']
940
941
942
943
['아메리카노/카페라떼/바닐라/연유라떼', '변동']
944
['카페 라떼', '5,000원']
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
['카페라떼 (아이스)', '6,800원']
970
971
972
['카페라떼', '5,500원']
973
974
975
976
['카페라떼/카푸치노', '4,500원']
977
978
979
980
['[HIVE]아이스 카페라떼', '5,000원']
981
['카페라떼', '5,500원']
982
983
['카페라떼', '1,900원']
984
985
986
987
988
989
990
991
['라떼', '5,300원']
992
['아이스 카페라떼', '6,500원']
993
994
995
996
['카페라떼', '5,500원']
997
['카페 라떼', '5,000원']
998
999
['카페 라떼', '5,000원']
1000
1001
['Kaffee_카페라떼', '5,800원']
1002
1003
1004
1005
['카페라떼', '5,400원']
1006
1007
1008
['카페라떼', '4,200원']
1009
1010
1011
1012
['(캔) LS 아이스 카페라떼', '4,000원']
['LS 아이스 카페라떼', '4,000원']
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
['카페라떼', '5,400원']
1024
['카페라떼', '3,800원']
1025
1026
1027
1028
['카페라떼', '3,500원']
1029
1030
['카페라떼', '5,000원']
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
['카페라떼', '3,700원']
['아이스 카페라떼', '4,200원']
1042
1043
1044
['카페라떼', '8,000원']
1045
1046
1047
1048
1049
1050
1051
['카페라떼 아이스', '3,500원']
1052
1053
1054
['카페라떼', '4,500원']
1055
1056
1057
1058
1059
1060
1061
1062
1063
['라떼', '4,900원']
1064
1065
['카페라떼 (Standard)', '5,700원']
1066
['카페라떼', '4,800원']
1067
1068
1069
1070
['카페라떼', '3,700원']
1071
1072
1073

In [ ]:
index2 = []
latte = []
for i in range(len(menu2)):
  print(i)
  for j in range(len(menu2['카카오 메뉴'][i])):
    if menu2['카카오 메뉴'][i][j][0].find("카페라떼") != -1:
      print(menu2['카카오 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['카카오 메뉴'][i][j])
    if menu2['카카오 메뉴'][i][j][0].find("카페 라떼") != -1:
      print(menu2['카카오 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['카카오 메뉴'][i][j])
    if menu2['카카오 메뉴'][i][j][0] == "카페 라떼":
      print(menu2['카카오 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['카카오 메뉴'][i][j])
    if menu2['카카오 메뉴'][i][j][0].find("latte") != -1:
      print(menu2['카카오 메뉴'][i][j])
      index2.append(i)
      latte.append(menu2['카카오 메뉴'][i][j])

0
1
['카페라떼(HOT)', '4,000']
2
3
['카페라떼', '2,500']
4
5
['카페라떼', '3,500']
6
['카페라떼', '3,500']
7
8
9
10
['카페라떼', '4,000']
11
12
13
14
15
16
17
18
['카페라떼', '5,500']
19
20
['카페 라떼', '3,500']
['카페 라떼', '3,500']
21
22
23
24
25
26
['카페라떼', '3,500']
27
['카페라떼(LARGE)', '3,300']
28
29
30
31
32
['카페라떼', '3,000']
33
['카페라떼', '5,500']
34
35
36
37
38
39
40
['카페라떼', '5,500']
41
42
43
44
45
['카페라떼', '5,500']
46
['카페라떼', '5,000']
47
48
49
50
['카페라떼', '4,000']
51
52
53
54
55
['카페라떼', '5,000']
56
['카페라떼', '5,500']
57
58
59
['카페라떼', '5,500']
60
61
62
63
64
65
['카페라떼', '5,800']
66
['카페라떼', '4,700']
67
68
69
70
['아이스 카페라떼(R)', '5,000']
71
72
73
74
75
['카페라떼', '3,800']
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
['추천\n카페라떼(Hot)', '4,000']
['아이스 카페라떼', '4,500']
93
94
95
96
97
98
99
100
['카페라떼(두유)', '5,000']
101
102
['카페라떼', '2,500']
103
['카페라떼', '4,000']
104
105
['카페라떼(핫)', '3,800']
106
107
108
109
110
111
['카페라떼', '4,300']
112
113
['카페 라떼', '5,500']
['카페 라떼', '5,500']
114
['카페라떼', '4,500']
115
116
117
118
119
120
121
122
123
124
125
126
['카페라떼', '5,000']
127
128
['흑임자 카페라떼', '5,500']
129
['카페라떼', '4,200']
130
131
132
['카페라떼 (HOT)', '4,800']
133
134
135
136
137
138
139
['카페라떼', '3,500']
140
['카페라떼', '3,900']
141
142
143
144
['카페라떼', '5,800']
145
146
147
['카페라떼(HOT)', '5,000']
148
149
150
['카페라떼 (HOT)', '5,000']
151
152
153
154
155
['카페라떼', '4,300']
156
['카페 라떼', '4,300']
['카페 라떼', '4,300']
157
158
159
160
161
162
163
164
165
['아이스 카페라떼(R)', '5,000']
166
167
168
169
170
171
172
173
174
175
176
['카페라떼', '3,200']
177
178
['카페라떼', '5,100']
179
['카페라떼', '5,100']
180
181
182
183
184
185
186
['카페라떼(HOT)', '4,500']
187
188
189
190
191
['카페라떼', '5,400']
192
193
194
['카페라떼', '4,500']
195
['카페라떼', '3,000']
196
197
198
199
200
201
['카페라떼', '4,500']
202
203
['카페라떼', '4,500']
204
205
['카페라떼', '5,000']
206
207
208
209
['생우유 카페라떼', '3,500']
210
211
212
['카페라떼', '4,000']
213
['카페라떼', '3,000']
214
215
['카페 라떼 (HOT)', '3,500']
216
217
218
219
220
221
222
223
['카페라떼', '6,000']
224
['카페라떼', '5,000']
225
226
['카페라떼', '4,500']
227
228
229
230
231
232
233
234
235
236
237
238
['아이스 카페라떼(R)', '5,000']
239
240
241
242
243
244
245
246
247
248
249
250
['카페라떼(ICE)', '4,800']
251
252
253
254
255
256
['카페라떼', '4,500']
257
['카페라떼', '4,500']
258
259
['카페라떼', '4,000']
260
261
262
['카페라떼', '4,000']
263
264
265
266
267
268
269
['카페라떼', '3,000']
270
['카페라떼', '3,500']
271
272
273
274
275
276
['카페라떼', '3,500']
277
278
['카페라떼', '2,500']
279
280
281
282
283
284
285
286
['카페 라떼', '4,500']
['카페 라떼', '4,500']
287
288
289
['카페라떼', '5,500']
290
291
292
['카페라떼', '4,000']
293
294
295
296
297
298
299
['카페라떼', '4,000']
300
301
302
303
304
305
306
307
308
['카페라떼', '2,000']
309
310
['카페라떼', '2,800']
311
312
313
314
315
316
['카페 라떼', '4,000']
['카페 라떼', '4,000']
317
318
319
320
['카페라떼(HOT)', '4,000']
321
322
323
324
['카페라떼', '2,000']
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
['카페라떼', '3,500']
347
348
349
['카페라떼', '3,800']
350
351
['카페라떼', '5,000']
352
353
['카페라떼', '2,900']
354
355
356
['카페라떼', '3,800']
357
358
359
360
361
362
363
364
['카페라떼', '5,000']
365
['카페라떼', '4,500']
366
['카페라떼', '4,500']
367
368
369
['카페라떼', '5,500']
['크림 카페라떼', '6,000']
370
371
372
373
['카페라떼', '4,000']
374
['카페라떼', '5,000']
375
376
377
['카페라떼', '4,800']
378
379
380
['카페라떼', '4,400']
381
382
383
384
['카페라떼', '3,500']
385
386
['아이스 카페라떼(R)', '5,000']
387
388
['카페라떼', '3,500']
389
['카페라떼', '4,500']
390
391
['카페라떼 HOT/ICED', '6,000']
392
393
['카페라떼', '3,500']
394
395
396
397
['카페라떼', '4,000']
398
399
400
401
402
403
404
405
406
407
['카페라떼 HOT', '3,300']
408
409
410
411
412
413
414
['카페라떼 (HOT)', '5,500']
415
416
417
418
419
['카페라떼', '4,500']
420
421
['카페라떼 (Large)', '2,800']
422
423
424
425
426
['카페라떼', '4,000']
427
['카페라떼', '3,500']
428
429
['카페라떼', '5,500']
430
431
['카페라떼', '4,500']
432
['추천\nNuttycream latte', '6,000']
['Mujagi latte with cup set', '9,000']
433
434
435
436
437
438
['카페라떼', '3,500']
439
440
441
442
443
444
445
446
447
448
['카페라떼', '4,000']
449
450
['카페라떼', '6,000']
451
452
453
454
455
456
457
458
459
460
['카페라떼', '4,500']
461
462
463
['카페라떼', '4,500']
464
465
466
['카페라떼', '4,100']
467
468
469
470
471
['카페라떼(HOT)', '4,000']
472
473
474
475
476
477
478
479
['카페라떼', '5,000']
480
['카페라떼', '4,000']
481
['카페라떼', '5,000']
482
483
484
['카페라떼', '4,000']
485
486
487
['카페라떼', '3,800']
488
489
490
491
492
493
['카페라떼', '4,500']
494
['카페라떼(HOT)', '3,000']
['카페라떼(ICE)', '3,500']
['바닐라카페라떼(HOT)', '3,500']
['바닐라카페라떼(ICE)', '4,000']
495
496
497
498
499
500
501
502
['카페라떼', '5,500']
503
504
505
506
507
508
509
510
['카페 라떼', '5,500']
['카페 라떼', '5,500']
511
512
['카페라떼', '5,000']
513
514
515
['카페라떼', '5,500']
516
['카페라떼', '4,500']
517
518
519
['카페라떼', '6,000']
520
521
['카페라떼', '4,200']
522
523
524
525
526
527
['카페라떼', '5,500']
528
529
530
531
532
533
['카페라떼', '4,500']
534
535
536
['카페라떼(ICE)', '5,500']
537
538
539
['카페라떼', '4,500']
540
['카페라떼', '5,000']
541
542
543
544
545
['카페라떼', '6,000']
546
547
548
['카페라떼', '2,900']
549
550
551
552
553
554
['Moon latte', '6,500']
555
556
557
558
559
560
['카페라떼', '3,900']
561
562
563
564
565
566
567
568
['카페라떼(HOT)', '5,000']
569
570
['카페라떼', '8,000']
571
572
573
['카페라떼(HOT)', '4,500']
574
575
576
577
['카페라떼', '5,500']
578
579
580
581
582
583
584
585
['카페라떼', '5,500']
586
587
588
589
590
591
592
['카페라떼', '6,000']
593
594
['카페라떼', '4,000']
595
596
597
598
['카페라떼', '4,500']
599
['카페라떼', '5,000']
600
['카페라떼', '4,000']
601
602
603
604
['카페라떼', '5,000']
605
606
607
608
609
610
611
612
613
['카페라떼', '5,500']
614
['카페라떼', '5,500']
615
616
617
618
619
['카페라떼', '4,500']
620
621
622
623
['카페라떼', '5,500']
624
['카페라떼', '4,500']
625
626
['카페라떼', '4,000']
627
628
629
['카페라떼(HOT)', '4,500']
630
631
632
633
634
635
636
637
['카페 라떼', '5,800']
['카페 라떼', '5,800']
638
639
640
641
642
643
644
645
646
647
['카페라떼', '4,000']
648
['카페라떼', '4,400']
649
650
651
652
['카페라떼', '6,000']
653
['latte', '5,000']
['vanilla latte', '5,500']
654
['카페라떼', '4,500']
655
656
['카페 라떼', '5,500']
['카페 라떼', '5,500']
657
658
659
660
661
662
['카페라떼', '7,500']
663
664
665
666
667
668
669
670
671
672
673
674
675
['카페라떼', '5,500']
676
677
678
['카페라떼', '6,500']
679
680
681
['카페라떼(HOT)', '5,500']
682
683
684
685
['카페라떼', '6,000']
686
687
688
689
690
691
692
693
694
695
696
['카페라떼', '5,400']
697
698
699
700
['카페라떼', '5,500']
701
702
703
['카페 라떼', '5,500']
['카페 라떼', '5,500']
704
['카페라떼', '5,500']
705
706
707
708
709
710
711
['카페 라떼', '6,000']
['카페 라떼', '6,000']
712
713
714
715
716
717
718
719
720
721
['카페라떼', '6,000']
722
723
724
725
726
727
728
['카페라떼', '4,600']
729
730
731
732
733
734
735
['카페라떼', '4,500']
736
737
738
739
740
741
['카페라떼', '5,000']
742
743
744
745
746
['카페라떼 (HOT)', '5,000']
747
748
['카페라떼', '6,000']
749
750
751
752
['클럽 카페라떼', '6,000']
753
['latte ( ice +200 )', '4,800']
754
755
756
['카페라떼', '3,000']
757
['카페라떼', '7,500']
758
759
['카페라떼', '4,500']
760
761
762
763
764
['카페 라떼', '6,500']
['카페 라떼', '6,500']
765
766
767
768
['카페라떼', '4,300']
769
['카페라떼(HOT)', '2,500']
770
771
772
773
774
775
776
777
['카페라떼', '3,000']
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
['카페라떼(ICE)', '3,500']
799
800
['카페라떼', '5,500']
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
['카페라떼(HOT)', '4,500']
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
['카페라떼', '5,000']
850
851
852
853
854
855
856
857
858
859
['카페라떼', '4,500']
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
['카페라떼', '4,000']
885
886
887
888
889
890
891
['카페라떼', '5,200']
892
893
894
895
896
897
898
899
900
['카페라떼', '5,000']
901
902
903
['카페라떼(HOT)', '3,000']
['카페라떼(ICED)', '3,500']
904
905
906
907
908
909
910
911
912
['카페라떼(HOT)', '4,500']
913
914
915
916
917
['카페라떼', '5,500']
918
919
920
['latte', '4,500']
['saltycreamlatte', '4,000']
921
922
923
924
925
926
927
928
929
930
931
['카페라떼', '4,000']
932
933
934
935
936
937
938
939
940
941
942
['카페라떼', '4,800']
943
944
945
946
947
948
949
950
951
952
953
954
['카페라떼(ICE)', '4,500']
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
['카페라떼', '5,400']
973
974
975
976
977
978
['카페라떼', '5,000']
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
['카페라떼', '5,400']
1006
1007
['카페라떼', '4,000']
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
['카페라떼', '5,400']
1024
1025
1026
1027
['카페라떼', '4,500']
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
['카페라떼', '8,000']
1045
1046
1047
1048
1049
1050
1051
1052
['카페라떼(HOT)', '3,300']
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073

In [ ]:
index1 = []
americano = []
for i in range(len(menu2)):
  print(i)
  for j in range(len(menu2['카카오 메뉴'][i])):
    if menu2['카카오 메뉴'][i][j][0].find("아메리카노") != -1:
      print(menu2['카카오 메뉴'][i][j])
      index1.append(i)
      americano.append(menu2['카카오 메뉴'][i][j])
    if menu2['카카오 메뉴'][i][j][0].find("americano") != -1:
      print(menu2['카카오 메뉴'][i][j])
      index1.append(i)
      americano.append(menu2['카카오 메뉴'][i][j])
    if menu2['카카오 메뉴'][i][j][0] == "커피":
      print(menu2['카카오 메뉴'][i][j])
      index1.append(i)
      americano.append(menu2['카카오 메뉴'][i][j])

0
1
['아메리카노(HOT)', '3,500']
['아메리카노(ICE)', '4,000']
2
3
['아메리카노', '1,700']
4
5
['아메리카노', '3,000']
6
['추천\n아이스아메리카노', '2,000']
['추천\n아메리카노', '1,500']
7
8
9
10
['아메리카노', '3,500']
11
12
13
14
15
16
17
18
['아메리카노', '5,000']
19
20
['아메리카노', '3,000']
21
['아메리카노 (Regular)', '2,000']
['아이스 아메리카노 (Regular)', '2,500']
22
23
['골드문롱블랙(아메리카노)', '4,000']
['누룽지롱블랙(아메리카노)', '4,000']
24
25
['아메리카노', '4,800']
26
['아메리카노', '3,000']
27
['아메리카노(LARGE)', '2,500']
28
29
30
31
['아메리카노', '4,000']
32
['아메리카노', '2,500']
33
['아메리카노', '5,000']
34
35
36
37
38
39
40
41
42
['아메리카노', '4,000']
43
44
45
['아메리카노', '5,000']
46
['아메리카노', '4,000']
47
48
49
50
['더블샷아메리카노', '3,500']
51
52
['아메리카노', '3,000']
53
['아메리카노', '5,000']
54
55
['아메리카노', '4,300']
56
['아메리카노', '5,000']
57
58
59
['아메리카노', '5,000']
60
61
62
63
64
65
['아메리카노', '5,300']
66
['아메리카노', '4,000']
67
68
69
70
['아이스 아메리카노(R)', '4,500']
['아메리카노(R)', '4,500']
71
['아메리카노 (HOT)', '4,500']
['프루티 아메리카노 (Iced Only)', '6,500']
72
73
74
75
['아메리카노', '3,500']
76
77
78
['(HOT) 아메리카노', '2,500']
['(ICE) 아메리카노', '3,000']
79
80
81
82
83
84
85
86
87
88
89
90
91
92
['아메리카노(Hot)', '3,000']
93
['추천\n아메리카노+스콘', '5,000']
94
95
['아메리카노', '2,000']
96
97
98
['아메리카노(싱글오리진)', '4,500']
99
100
101
['아메리카노', '4,000']
102
['추천\n아이스아메리카노', '1,500']
103
['아메리카노', '4,000']
104
105
['아메리카노(핫)', '3,000']
106
107
108
109
110
111
['아메리카노', '3,800']
112
113
['아메리카노', '4,500']
114
115
116
117
118
119
['아메리카노', '4,000']
120
121
122
123
124
125
126
['아메리카노', '4,500']
127
128
['아메리카노', '3,400']
129
['아메리카노', '3,000']
130
['아메리카노(ICE)', '4,300']
131
132
['아메리카노 (HOT)', '4,300']
133
134
['아메리카노', '3,500']
135
136
137
['세븐레이크아메리카노', '3,300']
138
139
['아메리카노', '3,000']
['아메리카노 (ICE)', '3,500']
140
['아메리카노', '2,900']
141
['아메리카노', '3,500']
142
143
144
['아메리카노', '4,800']
145
146
147
['아메리카노(HOT)', '4,000']
148
['아메리카노', '4,300']
149
150
['아메리카노 (HOT)', '4,000']
151
152
153
154
155
['아메리카노', '3,800']
156
['아메리카노', '3,800']
157
158
159
160
161
162
163
164
165
['아이스 아메리카노(R)', '4,500']
['아메리카노(R)', '4,500']
166
167
168
169
170
171
172
173
174
175
['아메리카노', '3,000']
176
['아메리카노', '2,800']
177
178
['아메리카노', '4,600']
179
['아메리카노', '4,600']
180
181
182
183
184
185
186
['아메리카노(HOT)', '4,000']
187
188
189
190
191
['카페 아메리카노', '4,900']
192
193
['아메리카노', '3,800']
194
['아메리카노', '4,000']
195
['아메리카노', '2,500']
196
197
198
199
200
201
['아메리카노', '3,500']
202
203
['아메리카노', '4,000']
204
['아메리카노', '4,500']
205
['아메리카노', '4,500']
206
207
['아메리카노', '5,500']
208
['아메리카노(2샷♥)', '4,000']
209
['아메리카노', '3,000']
210
['아메리카노', '4,000']
211
212
['클래식아메리카노', '3,000']
213
['아메리카노', '2,000']
214
215
['아메리카노 (HOT)', '3,000']
216
['추천\n아메리카노', '4,400']
217
218
219
['아메리카노', '3,500']
220
221
222
223
['아메리카노', '5,000']
224
['아메리카노', '4,000']
225
226
['아메리카노', '4,000']
227
228
['아메리카노', '4,500']
229
230
231
232
['커피', '변동가격']
233
234
235
['아메리카노', '3,200']
236
['추천\n아메리카노', '2,200']
['1L 아메리카노', '3,400']
237
238
['아이스 아메리카노(R)', '4,500']
['아메리카노(R)', '4,500']
239
240
241
242
243
244
245
['아메리카노', '4,500']
246
247
248
249
250
['아메리카노(ICE)', '3,800']
251
['아메리카노', '3,000']
252
253
254
255
256
['아메리카노', '4,000']
257
['아메리카노', '4,500']
258
259
['아메리카노', '3,500']
260
261
262
['아메리카노', '3,500']
263
264
265
['아메리카노', '4,500']
266
267
268
269
['아메리카노', '2,500']
270
['아메리카노', '3,000']
271
272
273
['아메리카노', '3,500']
274
275
276
['아메리카노', '2,800']
277
278
['아메리카노', '1,900']
279
['아메리카노(HOT)', '4,500']
280
281
['아메리카노', '3,500']
282
['크림치즈프레즐+아메리카노', '7,300']
283
284
285
['아메리카노(다크/미디엄)', '2,500']
286
['아메리카노', '3,500']
287
['아메리카노', '5,000']
288
289
['아메리카노', '4,000']
290
291
['아메리카노', '4,000']
292
['아메리카노', '3,500']
293
294
295
296
297
298
['아메리카노', '4,500']
299
['아메리카노', '3,000']
300
301
['아메리카노', '1,000']
302
303
304
305
306
307
308
['아메리카노', '1,500']
309
['추천\n아메리카노', '3,000']
310
['아메리카노', '2,300']
311
312
['아메리카노', '2,000']
313
314
315
316
['아메리카노', '2,000']
317
318
319
320
['아메리카노(HOT)', '3,500']
321
['아메리카노', '4,000']
322
323
324
['아메리카노', '1,500']
325
326
['추천\n아메리카노', '2,500']
327
328
['아메리카노', '3,000']
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
['아메리카노', '4,500']
345
346
['아메리카노', '3,000']
347
348
['아메리카노', '5,000']
349
['아메리카노', '3,000']
350
351
['아메리카노', '4,500']
352
353
['아메리카노', '2,900']
354
355
356
['아메리카노', '3,000']
357
358
['아메리카노', '4,300']
359
360
361
362
363
364
['아메리카노', '4,500']
365
['아메리카노', '4,000']
366
['아메리카노', '4,000']
367
['아메리카노', '4,500']
368
['아메리카노', '4,500']
369
['아메리카노', '5,000']
['크림 아메리카노', '5,500']
370
['아메리카노', '3,500']
371
372
373
['아메리카노', '3,800']
374
['아메리카노', '4,500']
375
376
['아메리카노는', '2,000']
377
['크림치즈 아메리카노', '5,500']
['아메리카노', '4,500']
378
['아메리카노', '3,000']
379
380
['아메리카노', '3,500']
381
382
383
384
['더치아메리카노', '3,000']
385
386
['아이스 아메리카노(R)', '4,500']
['아메리카노(R)', '4,500']
387
388
['아메리카노', '3,000']
389
['아메리카노', '3,500']
390
['아메리카노', '2,500']
391
['아메리카노 HOT/ICED', '4,500']
392
393
['아메리카노', '3,000']
394
395
['아메리카노', '2,500']
396
397
['아메리카노', '3,500']
398
399
400
401
['아메리카노(HOT)', '3,500']
['아메리카노(ICE)', '4,000']
402
403
404
405
['아메리카노', '2,000']
406
407
['아메리카노 HOT', '2,800']
408
409
410
411
412
413
414
['아메리카노 (HOT)', '5,300']
415
416
417
418
419
['아메리카노', '4,000']
420
421
['아메리카노 (Large)', '2,000']
422
423
424
425
426
['아메리카노', '3,500']
427
['아메리카노', '3,000']
428
['아메리카노', '5,000']
429
['아메리카노', '5,000']
430
431
['아메리카노', '4,000']
432
433
['아메리카노', '3,500']
434
435
['아메리카노', '5,000']
436
437
438
['아메리카노', '3,000']
439
440
441
['아메리카노', '3,800']
442
443
444
445
446
447
['추천\n아메리카노 다크나이트', '4,000']
448
['아메리카노', '3,500']
449
450
['아메리카노', '5,500']
451
452
453
['추천\n아메리카노', '4,500']
454
455
456
457
['아메리카노', '4,500']
458
459
460
['아메리카노', '4,000']
461
['아메리카노', '4,000']
462
463
['아메리카노', '4,000']
464
465
466
['아메리카노', '3,800']
467
468
['아메리카노', '4,000']
469
['아메리카노', '3,800']
470
['아메리카노', '3,500']
471
['아메리카노', '3,500']
472
473
474
475
476
477
478
479
['아메리카노', '4,500']
480
['아메리카노', '3,500']
481
['아메리카노', '4,500']
482
483
484
['아메리카노', '3,800']
485
['아메리카노', '4,300']
486
487
['아메리카노', '3,300']
488
489
490
491
492
493
['아메리카노', '4,000']
494
['아메리카노(HOT)', '2,000']
['아메리카노(ICE)', '2,500']
495
496
497
498
499
500
501
502
['아메리카노', '5,000']
503
['아메리카노', '3,500']
504
['아메리카노', '3,800']
505
506
507
508
['아메리카노', '4,000']
509
['아메리카노', '4,500']
510
['아메리카노', '5,000']
511
512
['아메리카노', '4,500']
513
514
515
['아메리카노', '5,000']
516
['아메리카노', '4,000']
517
518
['아메리카노', '4,000']
519
['아메리카노', '5,000']
520
['아메리카노', '3,000']
521
['아메리카노', '3,800']
522
['아메리카노', '5,000']
523
524
['아메리카노', '5,000']
525
526
527
['아메리카노', '5,000']
528
529
530
531
['(R)아메리카노', '4,500']
532
533
['아메리카노', '4,000']
534
535
536
['베트남아메리카노', '4,000']
['아메리카노(ICE)', '4,500']
537
['아메리카노', '4,600']
538
539
['아메리카노', '3,500']
540
['아메리카노', '4,500']
541
542
543
544
545
['아메리카노', '5,500']
546
547
548
['아메리카노', '2,900']
549
550
551
552
553
['아메리카노', '4,500']
554
555
556
557
558
559
560
['아메리카노', '2,900']
561
['아메리카노', '4,500']
562
563
564
565
566
567
568
['아메리카노(HOT)', '4,500']
569
570
['아메리카노', '7,000']
571
572
573
['아메리카노(HOT)', '4,000']
574
575
576
577
['아메리카노', '5,000']
578
579
580
581
582
583
['아메리카노', '4,500']
584
['아메리카노', '4,500']
585
['아메리카노', '5,000']
586
587
['아메리카노', '6,000']
588
['아메리카노', '4,800']
589
590
591
['아메리카노(따뜻한)', '4,000']
592
['아메리카노', '5,000']
593
594
['아메리카노', '3,500']
595
['아메리카노', '4,000']
596
597
598
['아메리카노', '4,000']
599
['아메리카노', '4,500']
600
['아메리카노', '3,700']
601
602
603
604
['아메리카노', '4,000']
605
606
['아메리카노', '6,300']
607
608
['아메리카노', '4,500']
609
610
['아메리카노', '4,500']
611
612
613
['아메리카노', '5,000']
614
['아메리카노', '4,000']
615
616
617
618
['아메리카노', '3,500']
619
['아메리카노', '4,000']
620
621
['아메리카노', '4,000']
622
['아메리카노 ICE', '4,500']
623
['아메리카노', '5,300']
624
['아메리카노', '4,000']
625
626
['아메리카노', '3,500']
627
628
['아메리카노', '4,500']
629
['아메리카노(HOT)', '3,500']
630
631
['카페 아메리카노(M)', '2,500']
632
633
634
635
636
637
['아메리카노 어센틱', '5,300']
638
639
640
641
642
643
644
645
['아메리카노', '3,500']
646
647
['아메리카노', '3,000']
648
['추천\n아메리카노', '3,900']
649
650
651
['그랑드카페 아이스아메리카노', '3,500']
652
['아메리카노', '5,500']
653
['americano', '4,500']
654
['아메리카노', '3,500']
655
656
['아메리카노', '5,000']
657
658
659
660
661
662
['아메리카노', '7,000']
663
664
665
666
667
668
669
['아메리카노ice', '4,300']
670
671
672
673
674
675
['아메리카노', '5,000']
676
['아메리카노', '5,500']
677
678
['아메리카노', '5,500']
679
680
681
['아메리카노(HOT)', '5,000']
682
683
684
685
['아메리카노', '5,000']
686
687
['아메리카노', '5,000']
688
689
690
691
692
693
694
695
696
['아메리카노', '4,900']
['디카페인 아메리카노', '5,400']
697
['아메리카노', '5,500']
698
699
700
['아메리카노', '5,000']
701
['아메리카노', '5,500']
702
703
['아메리카노(만델링, 엘사)', '5,000']
704
['아메리카노', '5,000']
705
['아메리카노', '5,000']
706
707
708
709
710
711
['아메리카노', '5,000']
712
713
714
715
716
['아메리카노', '4,500']
717
718
['아메리카노', '6,000']
719
720
721
['아메리카노', '5,500']
722
['아메리카노 (AMERICANO) (hot/iced)', '5,200']
723
['아이스 아메리카노', '5,000']
724
725
726
727
728
['아메리카노', '4,100']
729
730
731
732
733
734
735
['아메리카노', '4,000']
736
['아메리카노', '4,500']
737
738
739
740
741
['아메리카노', '4,500']
742
['추천\n아메리카노', '3,200']
743
744
745
746
['아메리카노 (HOT)', '4,500']
747
748
['아메리카노', '5,500']
749
750
['아메리카노', '4,800']
751
752
['아메리카노', '5,500']
753
['americano ( ice +200 )', '4,600']
754
755
756
['추천\n아메리카노', '2,000']
757
['아메리카노', '6,000']
758
759
['아메리카노', '4,000']
760
['아메리카노', '5,000']
761
762
763
764
['아메리카노', '6,000']
765
766
767
768
['아메리카노', '3,800']
769
['아메리카노', '2,000']
770
771
772
773
774
775
776
777
['아메리카노', '2,000']
778
779
780
['그랑드카페 아이스아메리카노', '3,500']
781
782
783
784
785
['아메리카노', '2,500']
786
787
788
789
790
791
792
793
794
795
796
797
798
['아메리카노', '3,000']
799
800
['아메리카노', '4,900']
801
802
803
804
805
806
807
808
['그랑드카페 아이스아메리카노', '3,500']
809
810
811
812
813
814
815
816
817
['그랑드카페 아이스아메리카노', '3,500']
818
819
['그랑드카페 아이스아메리카노', '3,500']
820
821
['그랑드카페 아이스아메리카노', '3,500']
822
823
824
825
826
827
828
829
['아메리카노(HOT)', '4,000']
830
831
832
833
834
835
836
837
838
839
840
['아메리카노', '3,900']
841
842
843
844
845
846
847
848
849
['아메리카노', '4,500']
850
851
852
['아메리카노', '4,000']
853
854
855
856
857
858
859
['아메리카노', '4,000']
860
861
['아메리카노', '4,000']
862
['아메리카노', '4,500']
863
['커피', '변동가격']
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
['아메리카노', '3,200']
885
886
887
['아메리카노', '4,000']
888
889
890
891
['아메리카노', '4,700']
892
893
894
895
896
897
898
899
900
['아메리카노', '4,000']
901
902
903
['아메리카노(HOT)', '2,500']
['아메리카노(ICED)', '3,000']
904
905
906
907
908
909
910
['아메리카노', '4,000']
911
912
['아메리카노(HOT)', '3,500']
913
914
915
916
917
['아메리카노', '5,000']
918
919
920
['americano', '3,800']
921
922
923
924
925
926
927
928
929
930
931
['아메리카노', '3,500']
932
933
934
['아메리카노(HOT)', '2,500']
935
['아메리카노', '4,800']
936
937
938
939
940
941
942
['아메리카노', '4,500']
943
944
945
946
947
948
949
950
951
952
953
954
['아메리카노(ICE)', '4,000']
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
['아메리카노', '4,800']
973
974
975
976
977
978
['아메리카노', '4,500']
979
980
981
982
983
['아메리카노', '1,900']
984
['아메리카노[Americano]', '5,000']
985
986
987
988
989
990
991
['아메리카노', '4,300']
992
993
994
995
996
997
998
999
1000
1001
1002
['그랑드카페 아이스아메리카노', '3,500']
1003
1004
1005
['카페 아메리카노', '4,900']
1006
1007
['아메리카노', '3,500']
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
['카페 아메리카노', '4,900']
1024
1025
1026
1027
['아메리카노', '4,000']
1028
1029
1030
['아메리카노', '4,000']
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
['아메리카노', '4,000']
1044
['아메리카노', '7,000']
1045
1046
1047
1048
1049
1050
1051
1052
['아메리카노(HOT)', '2,800']
['아메리카노(ICE)', '3,300']
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073

In [ ]:
index

[0,
 1,
 2,
 3,
 4,
 5,
 5,
 6,
 6,
 7,
 8,
 8,
 9,
 10,
 10,
 11,
 12,
 14,
 15,
 15,
 17,
 18,
 19,
 21,
 23,
 24,
 25,
 26,
 27,
 30,
 31,
 32,
 33,
 34,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 43,
 46,
 47,
 49,
 51,
 52,
 53,
 54,
 55,
 55,
 57,
 59,
 60,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 67,
 67,
 67,
 67,
 67,
 68,
 68,
 69,
 70,
 70,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 81,
 82,
 82,
 83,
 84,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 91,
 92,
 94,
 94,
 94,
 94,
 95,
 96,
 97,
 99,
 100,
 101,
 103,
 104,
 104,
 105,
 105,
 105,
 106,
 107,
 107,
 107,
 107,
 107,
 107,
 107,
 107,
 109,
 109,
 110,
 111,
 114,
 115,
 116,
 117,
 119,
 120,
 121,
 121,
 122,
 123,
 124,
 125,
 125,
 125,
 126,
 126,
 126,
 127,
 127,
 128,
 129,
 131,
 133,
 134,
 135,
 136,
 137,
 138,
 138,
 139,
 140,
 141,
 142,
 142,
 143,
 143,
 144,
 145,
 146,
 148,
 149,
 151,
 152,
 153,
 153,
 154,
 155,
 156,
 157,
 160,
 163,
 165,
 166,
 166,
 166,
 166,
 166,
 166,
 167,
 168,
 169,
 170,
 171,
 174,
 175,
 176,
 177,
 180,
 181,
 182,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 195,
 196,
 197,
 198,
 199,
 200,
 202,
 203,
 203,
 203,
 205,
 208,
 210,
 212,
 213,
 214,
 215,
 217,
 219,
 220,
 221,
 222,
 223,
 225,
 225,
 226,
 228,
 229,
 230,
 231,
 233,
 234,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 247,
 248,
 249,
 250,
 253,
 255,
 256,
 257,
 258,
 259,
 261,
 261,
 261,
 261,
 261,
 262,
 263,
 264,
 265,
 265,
 266,
 266,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 279,
 281,
 281,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 290,
 292,
 293,
 293,
 294,
 294,
 295,
 296,
 297,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 307,
 308,
 309,
 310,
 311,
 312,
 312,
 312,
 312,
 313,
 314,
 315,
 316,
 317,
 317,
 317,
 317,
 317,
 318,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 328,
 329,
 330,
 331,
 333,
 334,
 336,
 338,
 339,
 340,
 341,
 344,
 345,
 346,
 347,
 349,
 349,
 351,
 352,
 353,
 353,
 354,
 355,
 356,
 358,
 359,
 360,
 361,
 362,
 364,
 365,
 366,
 368,
 369,
 370,
 370,
 371,
 371,
 372,
 373,
 374,
 375,
 378,
 379,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 389,
 391,
 392,
 393,
 394,
 394,
 395,
 396,
 397,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 407,
 408,
 409,
 411,
 412,
 414,
 415,
 416,
 417,
 417,
 417,
 419,
 420,
 421,
 421,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 435,
 436,
 437,
 439,
 440,
 440,
 441,
 441,
 442,
 443,
 443,
 444,
 446,
 447,
 449,
 450,
 451,
 452,
 453,
 453,
 454,
 457,
 459,
 460,
 461,
 462,
 465,
 465,
 467,
 469,
 474,
 476,
 477,
 479,
 481,
 483,
 484,
 487,
 488,
 489,
 489,
 490,
 491,
 491,
 491,
 492,
 495,
 496,
 497,
 498,
 499,
 499,
 500,
 502,
 503,
 504,
 505,
 506,
 506,
 508,
 509,
 510,
 511,
 512,
 514,
 515,
 516,
 516,
 517,
 518,
 518,
 519,
 520,
 522,
 523,
 525,
 526,
 528,
 529,
 530,
 530,
 533,
 534,
 537,
 538,
 541,
 542,
 546,
 549,
 551,
 553,
 553,
 554,
 555,
 556,
 557,
 558,
 558,
 559,
 560,
 561,
 562,
 565,
 566,
 567,
 569,
 571,
 573,
 575,
 577,
 578,
 579,
 580,
 581,
 583,
 584,
 585,
 586,
 587,
 587,
 589,
 591,
 591,
 592,
 594,
 595,
 596,
 597,
 598,
 598,
 598,
 598,
 598,
 598,
 599,
 600,
 600,
 601,
 602,
 604,
 604,
 605,
 607,
 608,
 608,
 610,
 611,
 613,
 613,
 614,
 614,
 614,
 615,
 617,
 617,
 617,
 618,
 619,
 621,
 622,
 625,
 626,
 627,
 628,
 630,
 631,
 632,
 633,
 634,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 644,
 644,
 645,
 646,
 647,
 648,
 648,
 649,
 651,
 651,
 652,
 653,
 654,
 655,
 656,
 658,
 659,
 660,
 660,
 661,
 662,
 664,
 665,
 666,
 667,
 668,
 668,
 669,
 671,
 672,
 674,
 675,
 675,
 677,
 678,
 679,
 680,
 682,
 683,
 684,
 686,
 686,
 688,
 689,
 689,
 690,
 691,
 691,
 691,
 691,
 692,
 694,
 694,
 695,
 696,
 697,
 698,
 699,
 701,
 703,
 705,
 705,
 705,
 705,
 705,
 705,
 706,
 707,
 710,
 711,
 712,
 714,
 714,
 716,
 716,
 716,
 716,
 717,
 718,
 719,
 721,
 722,
 724,
 724,
 725,
 726,
 727,
 728,
 729,
 731,
 732,
 733,
 734,
 736,
 737,
 738,
 739]

In [ ]:
americano

[['아메리카노', '6,500원'],
 ['아메리카노', '3,500원'],
 ['핫아메리카노', '1,700원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '3,000원'],
 ['아이스아메리카노', '2,000원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노 ICE', '3,500원'],
 ['아메리카노', '3,000원'],
 ['아이스아메리카노', '4,000원'],
 ['샌드위치+아메리카노', '7,500원'],
 ['아메리카노', '3,700원'],
 ['아메리카노(ICED)', '4,300원'],
 ['아메리카노(HOT)', '3,800원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '2,000원'],
 ['아이스 아메리카노', '2,500원'],
 ['아메리카노', '4,800원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '4,300원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '3,300원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '5,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '4,300원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,600원'],
 ['아메리카노', '4,500원'],
 ['카페아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,800원'],
 ['콜드브루 아메리카노', '4,800원'],
 ['프루티 아메리카노', '6,500원'],
 ['아메리카노(HOT)', '3,000원'],
 ['아메리카노(ICE)', '3,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노 (펠트)', '4,500원'],
 ['아메리카노(HOT)', '2,500원'],
 ['아메리카노(ICE)', '3,000원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '2,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아이스아메리카노', '2,000원'],
 ['(L)HOT 카페 아메리카노', '3,200원'],
 ['(L)ICED 카페 아메리카노', '3,200원'],
 ['(EX)HOT 카페 아메리카노', '4,200원'],
 ['(EX)ICED 카페 아메리카노', '4,200원'],
 ['비니스트디카페인아메리카노(20T)', '4,700원'],
 ['비니스트디카페인아메리카노(80+20T)', '16,400원'],
 ['아메리카노', '4,300원'],
 ['벨벳아메리카노', '5,300원'],
 ['아메리카노', '3,000원'],
 ['아메리카노(HOT)', '2,400원'],
 ['아메리카노(ICE)', '2,400원'],
 ['빅사이즈 아메리카노', '2,500원'],
 ['아메리카노', '3,800원'],
 ['아메리카노(싱글오리진)', '4,800원'],
 ['아이스아메리카노', '2,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '4,000원'],
 ['더치아메리카노', '4,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노 R', '3,800원'],
 ['아메리카노 L', '4,800원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노 (hot/iced)', '4,000원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['연한 아메리카노', '3,500원'],
 ['핫아메리카노', '1,500원'],
 ['B 빅 아메리카노(4샷)', '4,600원'],
 ['B 빅 아메리카노(4샷)(1L)', '4,600원'],
 ['B 헤이즐넛아메리카노(1L)', '5,300원'],
 ['B 대만흑당  아메리카노(1L)', '5,800원'],
 ['아메리카노', '4,500원'],
 ['아메리카노 HOT/ICE', '3,400원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '5,500원'],
 ['아메리카노', '4,300원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,500원'],
 ['세븐레이크 아메리카노', '3,300원'],
 ['랑케블랙 아메리카노', '3,000원'],
 ['아메리카노 4+1(ICED ONLY(500ml))', '15,600원'],
 ['아메리카노 [ Americano ]', '3,900원'],
 ['아메리카노 1L', '7,300원'],
 ['아메리카노', '3,500원'],
 ['[하루 10개 한정세트] 아메리카노 4캔+백억떡 4개([2,600원 저렴합니당])', '19,000원'],
 ['[아메리카노 4캔 행사중입니다]', '14,000원'],
 ['[냉장 보관용] 아메리카노 (얼음X)(2+1 아메리카노 (얼음X))', '10,000원'],
 ['[냉장 보관용] 아메리카노 (얼음X)(5+1 아메리카노 (얼음X))', '20,000원'],
 ['[냉장 보관용] 아메리카노 (얼음X)(9+1 아메리카노 (얼음X))', '32,000원'],
 ['아메리카노(ICE(500ml캔))', '3,900원'],
 ['아메리카노(HOT(355ml캔))', '3,900원'],
 ['아메리카노(얼음빼주세요(355ml캔))', '3,900원'],
 ['아메리카노', '3,300원'],
 ['아메리카노 to go', '2,800원'],
 ['아메리카노', '4,800원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '3,900원'],
 ['아메리카노 HOT/ICE', '3,900원'],
 ['아메리카노', '3,800원'],
 ['카페아메리카노', '3,800원'],
 ['헤이즐넛 아메리카노', '5,000원'],
 ['아메리카노', '2,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '3,000원'],
 ['빽사이즈 아메리카노(ICED)', '3,500원'],
 ['아메리카노(HOT)', '1,800원'],
 ['아메리카노(ICED)', '2,300원'],
 ['(V)아이스 아메리카노', '5,500원'],
 ['(R)아메리카노', '4,500원'],
 ['(R)아이스 아메리카노', '4,500원'],
 ['아메리카노', '4,300원'],
 ['디카페인아메리카노', '4,800원'],
 ['에스프레소/아메리카노', '1,800원'],
 ['카페 아메리카노', '4,100원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '2,800원'],
 ['아메리카노(S)', '5,000원'],
 ['아메리카노 (H/I)', '4,900~5,400'],
 ['아메리카노', '5,000원'],
 ['헤이즐넛 아메리카노', '5,300원'],
 ['아메리카노', '4,800원'],
 ['생아메리카노', '1,800원'],
 ['아메리카노 hot', '4,000원'],
 ['아메리카노 코나 블렌드', '4,200원'],
 ['아메리카노 코나 100%', '6,000원'],
 ['HOT 아메리카노', '4,000원'],
 ['아이리쉬 아메리카노', '4,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노(Hot/Ice)', '3,500원'],
 ['카페 아메리카노', '4,900원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노 M', '1,600원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '3,500원'],
 ['디카페인아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,800원'],
 ['아메리카노', '2,800원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '4,400원'],
 ['(HOT)아메리카노', '2,000원'],
 ['(ICE)아메리카노', '2,500원'],
 ['(HOT)헤이즐넛아메리카노', '3,200원'],
 ['(ICE)헤이즐넛아메리카노', '3,200원'],
 ['메가엠지씨스틱 오리지날 아메리카노', '4,600원'],
 ['메가엠지씨스틱 디카페인 아메리카노', '5,400원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '5,000원'],
 ['카페 아메리카노', '5,000원'],
 ['아메리카노', '5,500원'],
 ['아메리카노', '4,000원'],
 ['카페 아메리카노', '3,200원'],
 ['시나몬 아메리카노', '2,900원'],
 ['아메리카노', '2,200원'],
 ['콜드브루 아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,400원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '1,500원'],
 ['아이스아메리카노', '3,800원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '2,900원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '2,900원'],
 ['오츠 아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,500원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '4,400원'],
 ['아메리카노 - hot', '4,500원'],
 ['빽사이즈 아메리카노(ICED)', '3,500원'],
 ['아메리카노(HOT)', '1,800원'],
 ['아메리카노(ICED)', '2,300원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '2,800원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '2,000원'],
 ['유기농 아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '3,900원'],
 ['아메리카노', '5,000원'],
 ['아메리카노(다크/미디움)', '2,500원'],
 ['아메리카노', '2,900원'],
 ['유자아메리카노', '6,000원'],
 ['아메리카노', '4,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '1,500원'],
 ['아메리카노(일반)', '3,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '3,200원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '1,000원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '1,700원'],
 ['아메리카노', '2,000원'],
 ['아메리카노 ', '1,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '2,300원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '3,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '1,500원'],
 ['제로슈가 스위트 아메리카노', '3,000원'],
 ['아메리카노', '2,500원'],
 ['시그니처 아메리카노', '2,700원'],
 ['헤이즐넛 아메리카노', '3,000원'],
 ['허니아메리카노', '3,000원'],
 ['아메리카노', '3,000원'],
 ['아이스 아메리카노 M', '1,400원'],
 ['아메리카노', '2,700원'],
 ['아메리카노', '1,500원'],
 ['아이스아메리카노', '1,900원'],
 ['아메리카노', '1,800원'],
 ['1리터 보틀 아메리카노', '4,200원'],
 ['아메리카노(디카페인)', '2,800원'],
 ['아메리카노 (세가지 블렌드 중 택)', '4,000원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '4,800원'],
 ['아메리카노(R)', '4,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '3,000원'],
 ['카페 아메리카노', '4,500원'],
 ['1리터 아메리카노', '3,000원'],
 ['아메리카노', '1,800원'],
 ['코코넛 아메리카노 L', '2,000원'],
 ['아메리카노', '3,300원'],
 ['아메리카노', '5,000원'],
 ['아메리카노ICE(리유저블컵)(IASO원두(Medium))', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노(HOT/ICE)', '4,500원'],
 ['아메리카노 (HOT/ICE)', '5,000원'],
 ['크림 아메리카노(HOT/ICE)', '5,500원'],
 ['아메리카노', '6,000원'],
 ['아메리카노(hot)', '4,500원'],
 ['아메리카노(ice)', '5,000원'],
 ['(NO.1) 아메리카노', '3,000원'],
 ['헤이즐넛아메리카노', '3,500원'],
 ['아메리카노', '4,500원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '4,300원'],
 ['아메리카노 L 사이즈', '2,800원'],
 ['아메리카노 ,D(ICE(2샷))', '3,800원'],
 ['아메리카노', '3,300원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '4,300원'],
 ['아메리카노', '3,500원'],
 ['아이스아메리카노', '3,000원'],
 ['아메리카노 HOT/ICED', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,000원'],
 ['1리터 아메리카노(only ICE)', '3,500원'],
 ['꿀 아메리카노', '3,300원'],
 ['치즈크림 아메리카노(only ICE)', '4,300원'],
 ['아메리카노', '2,800원'],
 ['아메리카노', '3,500원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['(L)HOT 카페 아메리카노', '3,200원'],
 ['(L)ICED 카페 아메리카노', '3,200원'],
 ['(EX)HOT 카페 아메리카노', '4,200원'],
 ['(EX)ICED 카페 아메리카노', '4,200원'],
 ['비니스트디카페인아메리카노(20T)', '4,700원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노(HOT)', '3,500원'],
 ['아메리카노', '1,900원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '4,800원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '5,300원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '4,100원'],
 ['아메리카노', '1,500원'],
 ['아메리카노(ICE+500원)', '2,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '5,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '6,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '3,500원'],
 ['꿀아메리카노', '4,300원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '5,500원'],
 ['디카페인 아메리카노', '4,800원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노 Americano', '4,000원'],
 ['아메리카노', '4,800원'],
 ['아메리카노', '변동'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,900원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '3,500원'],
 ['헤이즐넛 아메리카노', '4,000원'],
 ['아메리카노', '2,500원'],
 ['코코넛워터 아메리카노', '3,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '6,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '3,300원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '6,200원'],
 ['헤이즐넛 아메리카노', '6,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,300원'],
 ['아메리카노', '3,800원'],
 ['Hot 아메리카노', '5,000원'],
 ['Iced 아메리카노', '5,000원'],
 ['아메리카노', '6,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노 Americano', '5,000원'],
 ['아메리카노', '3,300원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,200원'],
 ['아메리카노', '5,000원'],
 ['아메리카노 AMERICANO', '3,500원'],
 ['아메리카노', '3,800원'],
 ['헤이즐넛 아메리카노', '4,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노(R)', '4,500원'],
 ['빽사이즈 아메리카노(ICED)', '3,500원'],
 ['아메리카노(HOT)', '1,800원'],
 ['아메리카노(ICED)', '2,300원'],
 ['아메리카노', '4,600원'],
 ['아이스아메리카노', '4,500원'],
 ['아메리카노 - TWO', '4,600원'],
 ['아메리카노 - XIX', '4,900원'],
 ['아메리카노(ICED OR HOT)', '3,800원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '3,200원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '5,500원'],
 ['아메리카노', '변동'],
 ['아메리카노', '1,400원'],
 ['아메리카노(2샷)', '2,900원'],
 ['Americano 아메리카노', '5,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노 아이스', '4,500원'],
 ['아메리카노', '4,800원'],
 ['아이스아메리카노', '5,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['디카페인 아메리카노', '5,000원'],
 ['아메리카노Americano', '4,500원'],
 ['아메리카노', '7,000원'],
 ['아메리카노', '5,800원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['마카롱 아이스크림 샌드위치+아메리카노', '9,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '6,000원'],
 ['아메리카노 R', '3,800원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노 (ICE)', '4,000원'],
 ['아메리카노 (HOT)', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '8,000원'],
 ['아메리카노', '5,000원'],
 ['카페 아메리카노', '4,100원'],
 ['아메리카노', '4,000~4,300'],
 ['아메리카노', '변동'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '5,300원'],
 ['아이스아메리카노', '5,800원'],
 ['아메리카노', '4,500원'],
 ['빽사이즈 아메리카노(ICED)', '3,500원'],
 ['아메리카노(HOT)', '1,800원'],
 ['아메리카노(ICED)', '2,300원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '2,800원'],
 ['ICE/HOT 카페 아메리카노', '2,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노(HOT)', '3,000원'],
 ['아메리카노 HOT', '5,300원'],
 ['아메리카노 ICE', '5,800원'],
 ['아메리카노(S)', '5,000원'],
 ['아메리카노', '4,000원'],
 ['아이스 아메리카노', '3,000원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '3,500원'],
 ['아이스아메리카노+ B.E.L.T 샌드위치', '9,800원'],
 ['아이스아메리카노+리얼브라우니', '6,500원'],
 ['아메리카노', '4,500원'],
 ['카페 알롱제(아메리카노)', '4,500원'],
 ['아메리카노', '4,600원'],
 ['아메리카노', '5,500원'],
 ['아이스 아메리카노', '7,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '1,500원'],
 ['Hot 아메리카노', '4,000원'],
 ['Iced)아메리카노(480ml)', '4,000원'],
 ['아메리카노(ice)', '4,300원'],
 ['아메리카노hot', '2,000원'],
 ['아메리카노ice', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '6,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '17,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,900원'],
 ['디카페인 아메리카노', '5,400원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,300원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['Black (아메리카노)', '5,000원'],
 ['아메리카노', '6,000원'],
 ['아메리카노', '5,200원'],
 ['아메리카노', '4,100원'],
 ['아메리카노 HOT', '4,300원'],
 ['아메리카노 iced', '4,800원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '2,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노HOT', '1,500원'],
 ['아메리카노ICE', '2,000원'],
 ['아메리카노_달콤 시그니처', '4,100원'],
 ['아메리카노', '4,500원'],
 ['카페 아메리카노', '3,200원'],
 ['아메리카노', '1,000원'],
 ['아메리카노', '3,500원'],
 ['Americano (아메리카노)', '5,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,200원'],
 ['아메리카노 H/I', '4,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '6,000원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '6,000원'],
 ['아메리카노', '4,300원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노 핫', '3,000원'],
 ['아메리카노', '2,500원'],
 ['아이스아메리카노+ B.E.L.T 샌드위치', '10,000원'],
 ['아이스아메리카노+리얼브라우니', '6,500원'],
 ['아메리카노', '4,500원'],
 ['아이스 아메리카노', '3,700원'],
 ['아메리카노', '3,200원'],
 ['아메리카노', '변동'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '3,900원'],
 ['아메리카노', '2,700원'],
 ['아메리카노', '5,000원'],
 ['아메리카노 + 시오빵 + 시오 카야버터', '10,200원'],
 ['아메리카노', '3,500원'],
 ['헤이즐넛 아메리카노', '4,000원'],
 ['아메리카노 (보틀)', '8,000원'],
 ['헤이즐넛 아메리카노 (보틀)', '9,000원'],
 ['콜드브루 아메리카노', '5,000원'],
 ['카페아메리카노', '4,100원'],
 ['그랑드카페 아메리카노(HOT)', '3,500원'],
 ['그랑드카페 아이스아메리카노', '3,500원'],
 ['아메리카노(hot/ice)', '3,000원'],
 ['아메리카노', '3,000원'],
 ['아이스 아메리카노', '3,800원'],
 ['아메리카노', '3,600원'],
 ['아메리카노', '3,800원'],
 ['아메리카노', '4,300원'],
 ['아이스 아메리카노', '3,700원'],
 ['아메리카노', '3,200원'],
 ['아메리카노 R', '2,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '2,500원'],
 ['눈꽃아메리카노', '3,500원'],
 ['아메리카노', '3,500원'],
 ['디카페인 아메리카노', '4,500원'],
 ['헤이즐넛 아메리카노', '4,000원'],
 ['아메리카노', '3,800원'],
 ['아이스 아메리카노', '3,700원'],
 ['BIG 아이스 아메리카노', '4,300원'],
 ['아메리카노', '3,200원'],
 ['아메리카노(ICE)', '3,500원'],
 ['아메리카노', '4,500원'],
 ['아이스 아메리카노', '4,500원'],
 ['아아스아메리카노', '3,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노 hot', '3,000원'],
 ['아메리카노', '1,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노 (핫)', '2,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '4,100원'],
 ['아메리카노', '2,500원'],
 ['아메리카노(고소한 원두)', '3,800원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '1,500원'],
 ['카페 아메리카노', '3,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노(Ice)', '4,500원'],
 ['아메리카노(Hot)', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,800원'],
 ['아메리카노', '3,000원'],
 ['아메리카노(UP)', '2,700원'],
 ['크로플 + 아메리카노', '10,000원'],
 ['아메리카노', '4,700원'],
 ['ICE 아메리카노', '4,000원'],
 ['HOT 아메리카노', '3,500원'],
 ['아메리카노', '3,800원'],
 ['아메리카노 S', '1,200원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '4,000원'],
 ['1L아메리카노', '6,000원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노 HOT', '2,000원'],
 ['아메리카노 ICE', '2,500원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '3,800원'],
 ['(HOT)디카페인 아메리카노', '2,800원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노 hot', '2,500원'],
 ['아메리카노 ice', '3,000원'],
 ['아메리카노', '2,000원'],
 ['아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노/카페라떼/바닐라/연유라떼', '변동'],
 ['카페 아메리카노', '4,500원'],
 ['아메리카노', '3,000원'],
 ['아메리카노(핫)', '3,000원'],
 ['아메리카노(아이스)', '3,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노 (아이스)', '6,500원'],
 ['아메리카노', '6,000원'],
 ['아메리카노/에스프레소', '5,000원'],
 ['아메리카노 클래식 h', '4,500원'],
 ['아메리카노 클래식 i', '5,000원'],
 ['아메리카노 어센틱 h', '5,000원'],
 ['아메리카노 어센틱 i', '5,500원'],
 ['아메리카노', '4,000원'],
 ['[HIVE]아이스 아메리카노', '4,400원'],
 ['[HIVE]아메리카노', '4,400원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '1,900원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '5,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '5,300원'],
 ['중복으로 선택하셔도 하나만나가용((후기약속)아메리카노ICE(얼음O))', '500원'],
 ['중복으로 선택하셔도 하나만나가용((후기약속)아메리카노ICE(얼음X))', '500원'],
 ['중복으로 선택하셔도 하나만나가용((후기약속)아메리카노HOT)', '500원'],
 ['아메리카노(ICE(얼음O))', '4,500원'],
 ['아메리카노(ICE(얼음X))', '4,500원'],
 ['아메리카노(HOT)', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '4,500원'],
 ['카페 아메리카노', '4,900원'],
 ['아메리카노+와플/크로폴(택1)', '6,500원'],
 ['아메리카노', '3,500원'],
 ['(캔) LS 아이스 아메리카노', '3,700원'],
 ['LS 아이스 아메리카노', '3,700원'],
 ['아메리카노(M)', '4,200원'],
 ['아이스 아메리카노(M)', '4,200원'],
 ['아이스 아메리카노(L)', '4,700원'],
 ['아이스 아메리카노(XL)', '5,700원'],
 ['카페 아메리카노', '4,900원'],
 ['아메리카노', '3,500원'],
 ['콜드브루 아메리카노', '3,800원'],
 ['아메리카노', '2,800원'],
 ['아메리카노', '4,000원'],
 ['아이스 아메리카노', '3,700원'],
 ['아메리카노', '3,200원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '7,000원'],
 ['아메리카노', '4,500원'],
 ['아메리카노', '4,000원'],
 ['아메리카노', '2,500원'],
 ['아메리카노', '3,900원'],
 ['아메리카노', '3,000원'],
 ['아메리카노', '3,500원'],
 ['아메리카노', '4,600원'],
 ['아메리카노', '4,300원'],
 ['콜드브루 아메리카노', '3,800원'],
 ['아메리카노', '3,200원'],
 ['아메리카노', '4,100원']]

In [ ]:
menu2['카_아메리카노'] = ""

In [ ]:
menu2['네_아메리카노'] = ""

In [ ]:
ame1 = pd.DataFrame({'index':index1, 'naver_americano':americano})

In [ ]:
lat1 = pd.DataFrame({'index':index2, 'naver_latte':latte})

In [ ]:
ame2 = pd.DataFrame({'index':index1, 'kakao_americano':americano})

In [ ]:
lat2 = pd.DataFrame({'index':index2, 'kakao_latte':latte})

In [ ]:
lat2

     index         kakao_latte
0        1  [카페라떼(HOT), 4,000]
1        2       [카페라떼, 2,500]
2        4       [카페라떼, 3,500]
3        5       [카페라떼, 3,500]
4        8       [카페라떼, 4,000]
..     ...                 ...
206    711       [카페라떼, 4,000]
207    717       [카페라떼, 5,400]
208    720       [카페라떼, 4,500]
209    726       [카페라떼, 8,000]
210    730  [카페라떼(HOT), 3,300]

[211 rows x 2 columns]

In [ ]:
#ame2 = kakao

In [ ]:
ame2

     index        kakao_americano
0        1    [아메리카노(HOT), 3,500]
1        1    [아메리카노(ICE), 4,000]
2        2         [아메리카노, 1,700]
3        4         [아메리카노, 3,000]
4        5  [추천\n아이스아메리카노, 2,000]
..     ...                    ...
350    722         [아메리카노, 4,000]
351    725         [아메리카노, 4,000]
352    726         [아메리카노, 7,000]
353    730    [아메리카노(HOT), 2,800]
354    730    [아메리카노(ICE), 3,300]

[355 rows x 2 columns]

In [ ]:
#ame = naver

In [ ]:
merge_outer_l = pd.merge(lat1,lat2, how='outer',on='index')
merge_outer_l

     index            naver_latte         kakao_latte
0        4        [카페 라떼, 4,200원]                 NaN
1        5         [카페라떼, 3,500원]       [카페라떼, 3,500]
2        7         [카페라떼, 4,000원]                 NaN
3        8  [카푸치노 / 카페라떼, 3,800원]                 NaN
4       10      [아이스카페라떼, 4,500원]       [카페라떼, 4,000]
..     ...                    ...                 ...
567    954                    NaN  [카페라떼(ICE), 4,500]
568    978                    NaN       [카페라떼, 5,000]
569   1007                    NaN       [카페라떼, 4,000]
570   1027                    NaN       [카페라떼, 4,500]
571   1052                    NaN  [카페라떼(HOT), 3,300]

[572 rows x 3 columns]

In [ ]:
merge_outer_2 = pd.merge(ame1,ame2, how='outer',on='index')
merge_outer_2

     index     naver_americano          kakao_americano
0        0     [아메리카노, 6,500원]                      NaN
1        1     [아메리카노, 3,500원]      [아메리카노(HOT), 3,500]
2        1     [아메리카노, 3,500원]      [아메리카노(ICE), 4,000]
3        3    [핫아메리카노, 1,700원]           [아메리카노, 1,700]
4        4  [카페 아메리카노, 3,200원]                      NaN
..     ...                 ...                      ...
842    978                 NaN           [아메리카노, 4,500]
843   1002                 NaN  [그랑드카페 아이스아메리카노, 3,500]
844   1027                 NaN           [아메리카노, 4,000]
845   1052                 NaN      [아메리카노(HOT), 2,800]
846   1052                 NaN      [아메리카노(ICE), 3,300]

[847 rows x 3 columns]

In [ ]:
ame

     index       naver_americano
0        0       [아메리카노, 6,500원]
1        1       [아메리카노, 3,500원]
2        2      [핫아메리카노, 1,700원]
3        3    [카페 아메리카노, 3,200원]
4        4       [아메리카노, 3,000원]
..     ...                   ...
699    734       [아메리카노, 4,600원]
700    736       [아메리카노, 4,300원]
701    737  [콜드브루 아메리카노, 3,800원]
702    738       [아메리카노, 3,200원]
703    739       [아메리카노, 4,100원]

[704 rows x 2 columns]

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,카_아메,아메리카노,네_라떼,카_라떼,라떼
0,1275361497,8.264307e+08,르플뢰브,"[[아메리카노, 6,500원]]",[],1,0,1,0,0,0
1,36877505,2.139356e+07,커피공장103 이촌점,"[[아메리카노, 3,500원], [(원두)하우스블렌드, 5,000원]]","[[에스프레소, 3,500], [아메리카노(HOT), 3,500], [아메리카노(I...",1,1,1,0,1,1
2,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[[핫아메리카노, 1,700원], [뚱카롱, 2,500원], [마카롱, 1,500원]]","[[아메리카노, 1,700], [카페라떼, 2,500], [핫초코, 2,400], ...",1,1,1,0,1,1
3,1149649924,1.910404e+09,이디야커피 용산원효점,"[[카페 아메리카노, 3,200원], [카페 라떼, 4,200원], [토피 넛 라떼...",[],1,0,1,1,0,1
4,37236205,2.405972e+07,카페로찌,"[[에스프레소, 3,000원], [아메리카노, 3,000원], [카페라떼, 3,50...","[[에스프레소, 3,000], [아메리카노, 3,000], [카페라떼, 3,500]...",1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
735,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,"[[룽고 (Standard), 4,900원], [카페라떼 (Standard), 5,...",[],0,0,0,1,0,1
736,18184715,8.123978e+06,파리크라상 한남점,"[[머쉬룸 오믈렛 브런치, 16,000원], [클럽 샌드위치 브런치, 16,000원...","[[파리 크라상(AOP 버터), 3,900], [몽블랑브레드, 6,500], [딸기...",1,0,1,1,0,1
737,11782468,2.006503e+09,배스킨라빈스 한남점,"[[파인트, 8,900원], [쿼터, 17,000원], [패밀리, 24,000원],...","[[옹기종기팩, 26,500], [아빠왔다팩, 13,500], [파인트, 8,900...",1,0,1,0,0,0
738,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[[꼬빠 삐꼴라(1가지맛)(컵or콘), 4,500원], [꼬빠 메디아(2가지맛)(컵...",[],1,0,1,1,0,1
739,11492935,8.257019e+06,던킨 서울역2호점,"[[아메리카노, 4,100원]]","[[올스타 도넛세트, 15,800], [버라이어티 10팩, 18,400], [내쉬빌...",1,0,1,0,0,0

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,카_아메,아메리카노,네_라떼,카_라떼,라떼
0,1275361497,8.264307e+08,르플뢰브,"[[아메리카노, 6,500원]]",[],1,0,1,0,0,0
1,36877505,2.139356e+07,커피공장103 이촌점,"[[아메리카노, 3,500원], [(원두)하우스블렌드, 5,000원]]","[[에스프레소, 3,500], [아메리카노(HOT), 3,500], [아메리카노(I...",1,1,1,0,1,1
2,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[[핫아메리카노, 1,700원], [뚱카롱, 2,500원], [마카롱, 1,500원]]","[[아메리카노, 1,700], [카페라떼, 2,500], [핫초코, 2,400], ...",1,1,1,0,1,1
3,1149649924,1.910404e+09,이디야커피 용산원효점,"[[카페 아메리카노, 3,200원], [카페 라떼, 4,200원], [토피 넛 라떼...",[],1,0,1,1,0,1
4,37236205,2.405972e+07,카페로찌,"[[에스프레소, 3,000원], [아메리카노, 3,000원], [카페라떼, 3,50...","[[에스프레소, 3,000], [아메리카노, 3,000], [카페라떼, 3,500]...",1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
735,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,"[[룽고 (Standard), 4,900원], [카페라떼 (Standard), 5,...",[],0,0,0,1,0,1
736,18184715,8.123978e+06,파리크라상 한남점,"[[머쉬룸 오믈렛 브런치, 16,000원], [클럽 샌드위치 브런치, 16,000원...","[[파리 크라상(AOP 버터), 3,900], [몽블랑브레드, 6,500], [딸기...",1,0,1,1,0,1
737,11782468,2.006503e+09,배스킨라빈스 한남점,"[[파인트, 8,900원], [쿼터, 17,000원], [패밀리, 24,000원],...","[[옹기종기팩, 26,500], [아빠왔다팩, 13,500], [파인트, 8,900...",1,0,1,0,0,0
738,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[[꼬빠 삐꼴라(1가지맛)(컵or콘), 4,500원], [꼬빠 메디아(2가지맛)(컵...",[],1,0,1,1,0,1
739,11492935,8.257019e+06,던킨 서울역2호점,"[[아메리카노, 4,100원]]","[[올스타 도넛세트, 15,800], [버라이어티 10팩, 18,400], [내쉬빌...",1,0,1,0,0,0

In [ ]:
menu2['index'] = ""

In [ ]:
for i in range(len(menu2)):
  menu2['index'][i] = i

<ipython-input-36-04eb77931ec1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu2['index'][i] = i

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,카_아메,아메리카노,네_라떼,카_라떼,라떼,index
0,1275361497,8.264307e+08,르플뢰브,"[[아메리카노, 6,500원]]",[],1,0,1,0,0,0,0
1,36877505,2.139356e+07,커피공장103 이촌점,"[[아메리카노, 3,500원], [(원두)하우스블렌드, 5,000원]]","[[에스프레소, 3,500], [아메리카노(HOT), 3,500], [아메리카노(I...",1,1,1,0,1,1,1
2,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[[핫아메리카노, 1,700원], [뚱카롱, 2,500원], [마카롱, 1,500원]]","[[아메리카노, 1,700], [카페라떼, 2,500], [핫초코, 2,400], ...",1,1,1,0,1,1,2
3,1149649924,1.910404e+09,이디야커피 용산원효점,"[[카페 아메리카노, 3,200원], [카페 라떼, 4,200원], [토피 넛 라떼...",[],1,0,1,1,0,1,3
4,37236205,2.405972e+07,카페로찌,"[[에스프레소, 3,000원], [아메리카노, 3,000원], [카페라떼, 3,50...","[[에스프레소, 3,000], [아메리카노, 3,000], [카페라떼, 3,500]...",1,1,1,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...
735,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,"[[룽고 (Standard), 4,900원], [카페라떼 (Standard), 5,...",[],0,0,0,1,0,1,735
736,18184715,8.123978e+06,파리크라상 한남점,"[[머쉬룸 오믈렛 브런치, 16,000원], [클럽 샌드위치 브런치, 16,000원...","[[파리 크라상(AOP 버터), 3,900], [몽블랑브레드, 6,500], [딸기...",1,0,1,1,0,1,736
737,11782468,2.006503e+09,배스킨라빈스 한남점,"[[파인트, 8,900원], [쿼터, 17,000원], [패밀리, 24,000원],...","[[옹기종기팩, 26,500], [아빠왔다팩, 13,500], [파인트, 8,900...",1,0,1,0,0,0,737
738,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[[꼬빠 삐꼴라(1가지맛)(컵or콘), 4,500원], [꼬빠 메디아(2가지맛)(컵...",[],1,0,1,1,0,1,738
739,11492935,8.257019e+06,던킨 서울역2호점,"[[아메리카노, 4,100원]]","[[올스타 도넛세트, 15,800], [버라이어티 10팩, 18,400], [내쉬빌...",1,0,1,0,0,0,739

In [ ]:
menu3 = pd.merge(merge_outer_2,merge_outer_l, how='outer',on='index')

In [ ]:
menu3

,index,naver_americano,kakao_americano,naver_latte,kakao_latte
0,0,"[아메리카노, 6,500원]",NaN,NaN,NaN
1,1,"[아메리카노, 3,500원]","[아메리카노(HOT), 3,500]",NaN,"[카페라떼(HOT), 4,000]"
2,1,"[아메리카노, 3,500원]","[아메리카노(ICE), 4,000]",NaN,"[카페라떼(HOT), 4,000]"
3,3,"[핫아메리카노, 1,700원]","[아메리카노, 1,700]",NaN,"[카페라떼, 2,500]"
4,4,"[카페 아메리카노, 3,200원]",NaN,"[카페 라떼, 4,200원]",NaN
...,...,...,...,...,...
1028,925,NaN,NaN,"[라떼, 5,500원]",NaN
1029,992,NaN,NaN,"[아이스 카페라떼, 6,500원]",NaN
1030,1001,NaN,NaN,"[Kaffee_카페라떼, 5,800원]",NaN
1031,1065,NaN,NaN,"[카페라떼 (Standard), 5,700원]",NaN
1032,40,NaN,NaN,NaN,"[카페라떼, 5,500]"

In [ ]:
menu2

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메리카노,카_아메리카노
0,1275361497,8.264307e+08,르플뢰브,"[[아메리카노, 6,500원]]",[],,
1,36877505,2.139356e+07,커피공장103 이촌점,"[[아메리카노, 3,500원], [(원두)하우스블렌드, 5,000원]]","[[에스프레소, 3,500], [아메리카노(HOT), 3,500], [아메리카노(I...",,
2,37568842,1.904932e+09,테이블스 용산점,"[[아인슈페너, 5,000원], [초코큐브파운드, 3,500원], [말차초코쿠키, ...",[],,
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[[핫아메리카노, 1,700원], [뚱카롱, 2,500원], [마카롱, 1,500원]]","[[아메리카노, 1,700], [카페라떼, 2,500], [핫초코, 2,400], ...",,
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[[카페 아메리카노, 3,200원], [카페 라떼, 4,200원], [토피 넛 라떼...",[],,
...,...,...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[[파인트, 8,900원], [쿼터, 17,000원], [패밀리, 24,000원],...","[[옹기종기팩, 26,500], [아빠왔다팩, 13,500], [파인트, 8,900...",,
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[[꼬빠 삐꼴라(1가지맛)(컵or콘), 4,500원], [꼬빠 메디아(2가지맛)(컵...",[],,
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[],,
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[[(아몬드)크림치즈스틱, 5,400원], [(할라피뇨,블랙페퍼)치즈핫도그, 5,4...",[],,
1073,11492935,8.257019e+06,던킨 서울역2호점,"[[아메리카노, 4,100원]]","[[올스타 도넛세트, 15,800], [버라이어티 10팩, 18,400], [내쉬빌...",,

In [ ]:
menu4 = pd.merge(menu2,menu3, how='outer',on='index')

In [ ]:
menu4.to_csv("/content/drive/MyDrive/Colab/최종파일모음/price_preview.csv", encoding="utf-8-sig")

In [ ]:
menu4

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,index,naver_americano,kakao_americano,naver_latte,kakao_latte
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]",NaN,0,"[아메리카노, 6,500원]",NaN,NaN,NaN
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ...",1,"[아메리카노, 3,500원]","[아메리카노(HOT), 3,500]",NaN,"[카페라떼(HOT), 4,000]"
2,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ...",1,"[아메리카노, 3,500원]","[아메리카노(ICE), 4,000]",NaN,"[카페라떼(HOT), 4,000]"
3,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[],2,NaN,NaN,NaN,NaN
4,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'...",3,"[핫아메리카노, 1,700원]","[아메리카노, 1,700]",NaN,"[카페라떼, 2,500]"
...,...,...,...,...,...,...,...,...,...,...
1394,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파...",1069,"[콜드브루 아메리카노, 3,800원]",NaN,NaN,NaN
1395,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN,1070,"[아메리카노, 3,200원]",NaN,"[카페라떼, 3,700원]",NaN
1396,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[],1071,NaN,NaN,NaN,NaN
1397,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN,1072,NaN,NaN,NaN,NaN
1398,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400...",1073,"[아메리카노, 4,100원]",NaN,NaN,NaN

In [ ]:
menu3

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,네_아메,카_아메,아메리카노,네_라떼,카_라떼,라떼,index,naver_americano,kakao_americano
0,1275361497,8.264307e+08,르플뢰브,"[[아메리카노, 6,500원]]",[],1,0,1,0,0,0,0,"[아메리카노, 6,500원]",NaN
1,36877505,2.139356e+07,커피공장103 이촌점,"[[아메리카노, 3,500원], [(원두)하우스블렌드, 5,000원]]","[[에스프레소, 3,500], [아메리카노(HOT), 3,500], [아메리카노(I...",1,1,1,0,1,1,1,"[아메리카노, 3,500원]","[아메리카노(HOT), 3,500]"
2,36877505,2.139356e+07,커피공장103 이촌점,"[[아메리카노, 3,500원], [(원두)하우스블렌드, 5,000원]]","[[에스프레소, 3,500], [아메리카노(HOT), 3,500], [아메리카노(I...",1,1,1,0,1,1,1,"[아메리카노, 3,500원]","[아메리카노(ICE), 4,000]"
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[[핫아메리카노, 1,700원], [뚱카롱, 2,500원], [마카롱, 1,500원]]","[[아메리카노, 1,700], [카페라떼, 2,500], [핫초코, 2,400], ...",1,1,1,0,1,1,2,"[핫아메리카노, 1,700원]","[아메리카노, 1,700]"
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[[카페 아메리카노, 3,200원], [카페 라떼, 4,200원], [토피 넛 라떼...",[],1,0,1,1,0,1,3,"[카페 아메리카노, 3,200원]",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,"[[룽고 (Standard), 4,900원], [카페라떼 (Standard), 5,...",[],0,0,0,1,0,1,735,NaN,NaN
896,18184715,8.123978e+06,파리크라상 한남점,"[[머쉬룸 오믈렛 브런치, 16,000원], [클럽 샌드위치 브런치, 16,000원...","[[파리 크라상(AOP 버터), 3,900], [몽블랑브레드, 6,500], [딸기...",1,0,1,1,0,1,736,"[아메리카노, 4,300원]",NaN
897,11782468,2.006503e+09,배스킨라빈스 한남점,"[[파인트, 8,900원], [쿼터, 17,000원], [패밀리, 24,000원],...","[[옹기종기팩, 26,500], [아빠왔다팩, 13,500], [파인트, 8,900...",1,0,1,0,0,0,737,"[콜드브루 아메리카노, 3,800원]",NaN
898,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[[꼬빠 삐꼴라(1가지맛)(컵or콘), 4,500원], [꼬빠 메디아(2가지맛)(컵...",[],1,0,1,1,0,1,738,"[아메리카노, 3,200원]",NaN
899,11492935,8.257019e+06,던킨 서울역2호점,"[[아메리카노, 4,100원]]","[[올스타 도넛세트, 15,800], [버라이어티 10팩, 18,400], [내쉬빌...",1,0,1,0,0,0,739,"[아메리카노, 4,100원]",NaN

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/price_full_ver.csv', encoding="utf-8", header = 0)

In [ ]:
df

,Unnamed: 0,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴,index,naver_americano,kakao_americano,naver_latte,kakao_latte
0,0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]",NaN,0,"['아메리카노', '6,500원']",NaN,NaN,NaN
1,2,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ...",1,"['아메리카노', '3,500원']","['아메리카노(ICE)', '4,000']",NaN,"['카페라떼(HOT)', '4,000']"
2,3,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[],2,NaN,NaN,NaN,NaN
3,4,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'...",3,"['핫아메리카노', '1,700원']","['아메리카노', '1,700']",NaN,"['카페라떼', '2,500']"
4,5,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN,4,"['카페 아메리카노', '3,200원']",NaN,"['카페 라떼', '4,200원']",NaN
...,...,...,...,...,...,...,...,...,...,...,...
1069,1394,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파...",1069,"['콜드브루 아메리카노', '3,800원']",NaN,NaN,NaN
1070,1395,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN,1070,"['아메리카노', '3,200원']",NaN,"['카페라떼', '3,700원']",NaN
1071,1396,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[],1071,NaN,NaN,NaN,NaN
1072,1397,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN,1072,NaN,NaN,NaN,NaN
1073,1398,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400...",1073,"['아메리카노', '4,100원']",NaN,NaN,NaN

In [ ]:
df.columns

Index(['Unnamed: 0', 'data-cid', 'kakao-id', '카페명', '네이버 메뉴', '카카오 메뉴',
       'index', 'naver_americano', 'kakao_americano', 'naver_latte',
       'kakao_latte'],
      dtype='object')

In [ ]:
col = ['data-cid', 'naver_americano', 'kakao_americano', 'naver_latte',
       'kakao_latte']

In [ ]:
menu = df[col]

In [ ]:
menu

,data-cid,naver_americano,kakao_americano,naver_latte,kakao_latte
0,1275361497,"['아메리카노', '6,500원']",NaN,NaN,NaN
1,36877505,"['아메리카노', '3,500원']","['아메리카노(ICE)', '4,000']",NaN,"['카페라떼(HOT)', '4,000']"
2,37568842,NaN,NaN,NaN,NaN
3,1985101469,"['핫아메리카노', '1,700원']","['아메리카노', '1,700']",NaN,"['카페라떼', '2,500']"
4,1149649924,"['카페 아메리카노', '3,200원']",NaN,"['카페 라떼', '4,200원']",NaN
...,...,...,...,...,...
1069,11782468,"['콜드브루 아메리카노', '3,800원']",NaN,NaN,NaN
1070,31363849,"['아메리카노', '3,200원']",NaN,"['카페라떼', '3,700원']",NaN
1071,1119858083,NaN,NaN,NaN,NaN
1072,1126198061,NaN,NaN,NaN,NaN
1073,11492935,"['아메리카노', '4,100원']",NaN,NaN,NaN

In [ ]:
review = pd.read_csv('/content/drive/MyDrive/Colab/review_최종_781.csv', encoding="utf-8", header = 0)

In [ ]:
review

,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count
0,1,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251
1,2,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48
2,3,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115
3,5,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237
4,6,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130
...,...,...,...,...,...,...,...,...
775,940,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819
776,941,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371
777,942,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164
778,943,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76
779,945,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179"

In [ ]:
new = pd.merge(review, menu, how='outer',on='data-cid')

In [ ]:
new

,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,naver_americano,kakao_americano,naver_latte,kakao_latte
0,1.0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN,NaN,NaN
1,2.0,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['아메리카노(ICE)', '4,000']",NaN,"['카페라떼(HOT)', '4,000']"
2,3.0,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,NaN,NaN,NaN,NaN
3,5.0,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']",NaN,"['카페 라떼', '4,200원']",NaN
4,6.0,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['아메리카노', '3,000']","['카페라떼', '3,500원']","['카페라떼', '3,500']"
...,...,...,...,...,...,...,...,...,...,...,...,...
1069,NaN,19923981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1070,NaN,1676574304,NaN,NaN,NaN,NaN,NaN,NaN,"['아메리카노', '4,600원']",NaN,"['라떼', '4,900원']",NaN
1071,NaN,1496827922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1072,NaN,37264311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1073,NaN,1126198061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
new.dropna(subset=['카페명'], inplace=True)

In [ ]:
new

,Unnamed: 0.1,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,naver_americano,kakao_americano,naver_latte,kakao_latte
0,0,1.0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN,NaN,NaN
1,1,2.0,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['아메리카노(ICE)', '4,000']",NaN,"['카페라떼(HOT)', '4,000']"
2,2,3.0,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,NaN,NaN,NaN,NaN
3,3,5.0,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']",NaN,"['카페 라떼', '4,200원']",NaN
4,4,6.0,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['아메리카노', '3,000']","['카페라떼', '3,500원']","['카페라떼', '3,500']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,940.0,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,NaN,NaN,NaN,NaN
776,776,941.0,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"['콜드브루 아메리카노', '3,800원']",NaN,NaN,NaN
777,777,942.0,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"['아메리카노', '3,200원']",NaN,"['카페라떼', '3,700원']",NaN
778,778,943.0,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,NaN,NaN,NaN,NaN
779,779,945.0,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","['아메리카노', '4,100원']",NaN,NaN,NaN

In [ ]:
new.to_csv('/content/drive/MyDrive/Colab/최종파일모음/price_780.csv', encoding='utf-8-sig')

In [ ]:
new = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/price_780.csv', encoding='utf-8-sig')

In [ ]:
new['naver_ame_null']=new['naver_americano'].isnull()

In [ ]:
new['naver_lat_null']=new['naver_latte'].isnull()

In [ ]:
new

,Unnamed: 0.1,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,naver_americano,kakao_americano,naver_latte,kakao_latte,naver_ame_null,naver_lat_null
0,0,1.0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN,NaN,NaN,False,True
1,1,2.0,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['아메리카노(ICE)', '4,000']","['카페라떼(HOT)', '4,000']","['카페라떼(HOT)', '4,000']",False,False
2,2,3.0,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,NaN,NaN,NaN,NaN,True,True
3,3,5.0,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']",NaN,"['카페 라떼', '4,200원']",NaN,False,False
4,4,6.0,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['아메리카노', '3,000']","['카페라떼', '3,500원']","['카페라떼', '3,500']",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,940.0,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,NaN,NaN,NaN,NaN,True,True
776,776,941.0,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"['콜드브루 아메리카노', '3,800원']",NaN,NaN,NaN,False,True
777,777,942.0,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"['아메리카노', '3,200원']",NaN,"['카페라떼', '3,700원']",NaN,False,False
778,778,943.0,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,NaN,NaN,NaN,NaN,True,True
779,779,945.0,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","['아메리카노', '4,100원']",NaN,NaN,NaN,False,True

In [ ]:
from numpy import NaN
for i in range(0,780):
  if new['naver_ame_null'][i] == True :
    new['naver_americano'][i] = new['kakao_americano'][i]

<ipython-input-58-2ed4f4e85700>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['naver_americano'][i] = new['kakao_americano'][i]

In [ ]:
for i in range(0,780):
  if new['naver_lat_null'][i] == True :
    new['naver_latte'][i] = new['kakao_latte'][i]

<ipython-input-59-7bdfbd2b7465>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['naver_latte'][i] = new['kakao_latte'][i]

In [ ]:
#앞에 과정 반복

In [ ]:
from numpy import NaN
for i in range(0,780):
  if new['naver_ame_null'][i]==True and new['naver_lat_null'][i]==True :
    new.drop(i , inplace=True)

In [ ]:
new

,Unnamed: 0.1,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,naver_americano,kakao_americano,naver_latte,kakao_latte,naver_ame_null,naver_lat_null
0,0,1.0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN,NaN,NaN,False,True
1,1,2.0,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['아메리카노(ICE)', '4,000']","['카페라떼(HOT)', '4,000']","['카페라떼(HOT)', '4,000']",False,False
3,3,5.0,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']",NaN,"['카페 라떼', '4,200원']",NaN,False,False
4,4,6.0,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['아메리카노', '3,000']","['카페라떼', '3,500원']","['카페라떼', '3,500']",False,False
5,5,8.0,1912771394,1.030741e+08,루트카페,서울 용산구 원효로19길 18 1층 ROOT카페,"카페,디저트",https://pcmap.place.naver.com/restaurant/19127...,149,"['아메리카노', '3,000원']",NaN,"['루트라떼': '4,500원']",NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,773,938.0,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,서울 용산구 한남대로 48,카페,https://pcmap.place.naver.com/restaurant/37769...,"1,238",NaN,NaN,"['카페라떼 (Standard)', '5,700원']",NaN,True,False
774,774,939.0,18184715,8.123978e+06,파리크라상 한남점,서울 용산구 독서당로 78 청화빌딩,베이커리,https://pcmap.place.naver.com/restaurant/18184...,696,"['아메리카노', '4,300원']",NaN,"['카페라떼', '4,800원']",NaN,False,False
776,776,941.0,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"['콜드브루 아메리카노', '3,800원']",NaN,NaN,NaN,False,True
777,777,942.0,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"['아메리카노', '3,200원']",NaN,"['카페라떼', '3,700원']",NaN,False,False
779,779,945.0,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","['아메리카노', '4,100원']",NaN,NaN,NaN,False,True

In [ ]:
new.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'data-cid', '카카오 id', '카페명', '네이버주소',
       '분류', 'naver_url', 'review_count', 'naver_americano', 'kakao_americano',
       'naver_latte', 'kakao_latte', 'naver_ame_null', 'naver_lat_null'],
      dtype='object')

In [ ]:
new = new.drop(['kakao_americano', 'kakao_latte', 'naver_ame_null', 'naver_lat_null'], axis=1)

In [ ]:
new

,Unnamed: 0.1,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,naver_americano,naver_latte
0,0,1.0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN
1,1,2.0,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['카페라떼(HOT)', '4,000']"
3,3,5.0,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']","['카페 라떼', '4,200원']"
4,4,6.0,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['카페라떼', '3,500원']"
5,5,8.0,1912771394,1.030741e+08,루트카페,서울 용산구 원효로19길 18 1층 ROOT카페,"카페,디저트",https://pcmap.place.naver.com/restaurant/19127...,149,"['아메리카노', '3,000원']","['루트라떼': '4,500원']"
...,...,...,...,...,...,...,...,...,...,...,...
773,773,938.0,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,서울 용산구 한남대로 48,카페,https://pcmap.place.naver.com/restaurant/37769...,"1,238",NaN,"['카페라떼 (Standard)', '5,700원']"
774,774,939.0,18184715,8.123978e+06,파리크라상 한남점,서울 용산구 독서당로 78 청화빌딩,베이커리,https://pcmap.place.naver.com/restaurant/18184...,696,"['아메리카노', '4,300원']","['카페라떼', '4,800원']"
776,776,941.0,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"['콜드브루 아메리카노', '3,800원']",NaN
777,777,942.0,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"['아메리카노', '3,200원']","['카페라떼', '3,700원']"
779,779,945.0,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","['아메리카노', '4,100원']",NaN

In [ ]:
from ast import literal_eval

# 문자열을 리스트로 변환
def str_to_list(x):
    try:
        return literal_eval(x)
    except: #해당 값이 null값이거나 오류가 있을 때, None을 return 하기
        return None

# df['컬럼명'] = df['컬럼명'].apply(lambda x: str_to_list(x))
# df['결측값수'] = df['결측값수'].apply(lambda x: str_to_list(x))
new['naver_americano'] = new['naver_americano'].apply(lambda x: str_to_list(x))
new['naver_latte'] = new['naver_latte'].apply(lambda x: str_to_list(x))

In [ ]:
new['naver_americano'].str[1]

0      6,500원
1      3,500원
3      3,200원
4      3,000원
5      3,000원
        ...
773      None
774    4,300원
776    3,800원
777    3,200원
779    4,100원
Name: naver_americano, Length: 564, dtype: object

In [ ]:
new['americano'] = new['naver_americano'].str[1]

In [ ]:
new['latte'] = new['naver_latte'].str[1]

In [ ]:
new = new.rename(columns={'naver_americano':'americano_full'})

In [ ]:
new = new.rename(columns={'naver_latte':'latte_full'})

In [ ]:
new.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'data-cid', '카카오 id', '카페명', '네이버주소',
       '분류', 'naver_url', 'review_count', 'americano_full', 'latte_full',
       'americano', 'latte'],
      dtype='object')

In [ ]:
new = new.rename(columns={'Unnamed: 0.1':'no.'})

In [ ]:
new = new.drop(['Unnamed: 0'], axis=1)

In [ ]:
new

,no.,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,americano_full,latte_full,americano,latte
0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"[아메리카노, 6,500원]",None,"6,500원",None
1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"[아메리카노, 3,500원]","[카페라떼(HOT), 4,000]","3,500원","4,000"
3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"[카페 아메리카노, 3,200원]","[카페 라떼, 4,200원]","3,200원","4,200원"
4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"[아메리카노, 3,000원]","[카페라떼, 3,500원]","3,000원","3,500원"
5,5,1912771394,1.030741e+08,루트카페,서울 용산구 원효로19길 18 1층 ROOT카페,"카페,디저트",https://pcmap.place.naver.com/restaurant/19127...,149,"[아메리카노, 3,000원]",None,"3,000원",None
...,...,...,...,...,...,...,...,...,...,...,...,...
773,773,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,서울 용산구 한남대로 48,카페,https://pcmap.place.naver.com/restaurant/37769...,"1,238",None,"[카페라떼 (Standard), 5,700원]",None,"5,700원"
774,774,18184715,8.123978e+06,파리크라상 한남점,서울 용산구 독서당로 78 청화빌딩,베이커리,https://pcmap.place.naver.com/restaurant/18184...,696,"[아메리카노, 4,300원]","[카페라떼, 4,800원]","4,300원","4,800원"
776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"[콜드브루 아메리카노, 3,800원]",None,"3,800원",None
777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"[아메리카노, 3,200원]","[카페라떼, 3,700원]","3,200원","3,700원"
779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","[아메리카노, 4,100원]",None,"4,100원",None

In [ ]:
new.to_csv('/content/drive/MyDrive/Colab/최종파일모음/price_separate.csv',  encoding='utf-8-sig')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/price_separate(최종).csv', encoding='utf-8-sig')

In [ ]:
df

,Unnamed: 0,no.,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,americano_full,latte_full,americano,latte
0,0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN,"6,500원",NaN
1,1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['카페라떼(HOT)', '4,000']","3,500원","4,000"
2,3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']","['카페 라떼', '4,200원']","3,200원","4,200원"
3,4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['카페라떼', '3,500원']","3,000원","3,500원"
4,5,5,1912771394,1.030741e+08,루트카페,서울 용산구 원효로19길 18 1층 ROOT카페,"카페,디저트",https://pcmap.place.naver.com/restaurant/19127...,149,"['아메리카노', '3,000원']",NaN,"3,000원",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,773,773,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,서울 용산구 한남대로 48,카페,https://pcmap.place.naver.com/restaurant/37769...,"1,238",NaN,"['카페라떼 (Standard)', '5,700원']",NaN,"5,700원"
560,774,774,18184715,8.123978e+06,파리크라상 한남점,서울 용산구 독서당로 78 청화빌딩,베이커리,https://pcmap.place.naver.com/restaurant/18184...,696,"['아메리카노', '4,300원']","['카페라떼', '4,800원']","4,300원","4,800원"
561,776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"['콜드브루 아메리카노', '3,800원']",NaN,"3,800원",NaN
562,777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"['아메리카노', '3,200원']","['카페라떼', '3,700원']","3,200원","3,700원"
563,779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","['아메리카노', '4,100원']",NaN,"4,100원",NaN

In [ ]:
#/content/drive/MyDrive/Colab/최종파일모음/review_lnglat.csv
#/content/drive/MyDrive/Colab/최종파일모음/기본정보count_final.csv
#/content/drive/MyDrive/Colab/최종파일모음/price_separate(최종).csv
#/content/drive/MyDrive/Colab/최종파일모음/classify_0-779_top5(최종).csv

In [ ]:
full = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/review_lnglat.csv', encoding='utf-8-sig')
info = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/기본정보count_final.csv', encoding='utf-8-sig')
price = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/price_separate(최종).csv', encoding='utf-8-sig')

In [ ]:
classify = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/classify_0-779_top5(최종).csv', encoding='utf-8-sig')

In [ ]:
hashtags = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/hashtags.csv', encoding='utf-8-sig')

In [ ]:
hashtags

,cafe,TOP1,TOP2,TOP3,TOP4,TOP5,TOP6,TOP7
0,0,"('뷰', '150')","('비싸다', '14')","('브런치', '11')","('예쁘다', '11')","('야경', '9')","('파스타', '7')","('층', '7')"
1,1,"('조용하다', '3')","('넓다', '1')","('아늑하다', '1')","('파니니', '1')","('다양하다', '1')","('홍차', '1')","('편안하다', '1')"
2,2,"('샌드위치', '7')","('과일', '5')","('아메리카노', '4')","('카페라떼', '3')","('크로와상', '3')","('치아바타', '3')","('음악', '3')"
3,3,"('조용하다', '8')","('깨끗하다', '5')","('깔끔하다', '4')","('쾌적하다', '3')","('대화', '3')","('위치', '2')","('청결하다', '2')"
4,4,"('스콘', '6')","('깔끔하다', '6')","('인테리어', '4')","('편하다', '3')","('예쁘다', '3')","('넓다', '3')","('디저트', '3')"
...,...,...,...,...,...,...,...,...
775,775,"('다양하다', '11')","('샐러드', '7')","('청결하다', '5')","('케잌', '5')","('넓다', '4')","('신선하다', '4')","('빵집', '4')"
776,776,"('아이스크림', '8')","('예쁘다', '4')","('기다리다', '2')","('케이크', '2')","('다양하다', '2')","('와플', '2')","('깨끗하다', '2')"
777,777,"('젤라또', '25')","('아이스크림', '24')","('아이', '5')","('비싸다', '3')","('넓다', '2')","('쾌적하다', '2')","('층', '2')"
778,778,"('식빵', '6')","('치아바타', '5')","('비싸다', '5')","('빵집', '4')","('지나가다', '3')","('깔끔하다', '3')","('피자', '3')"
779,779,"('서울역', '29')","('기다리다', '6')","('쉬다', '5')","('청결하다', '4')","('간단하다', '4')","('편하다', '4')","('아메리카노', '3')"

In [ ]:
hashtags.columns

Index(['cafe', 'TOP1', 'TOP2', 'TOP3', 'TOP4', 'TOP5', 'TOP6', 'TOP7'], dtype='object')

In [ ]:
col = ['TOP1', 'TOP2', 'TOP3', 'TOP4', 'TOP5', 'TOP6', 'TOP7']

In [ ]:
hashtags = hashtags[col]

In [ ]:
hashtags

,TOP1,TOP2,TOP3,TOP4,TOP5,TOP6,TOP7
0,"('뷰', '150')","('비싸다', '14')","('브런치', '11')","('예쁘다', '11')","('야경', '9')","('파스타', '7')","('층', '7')"
1,"('조용하다', '3')","('넓다', '1')","('아늑하다', '1')","('파니니', '1')","('다양하다', '1')","('홍차', '1')","('편안하다', '1')"
2,"('샌드위치', '7')","('과일', '5')","('아메리카노', '4')","('카페라떼', '3')","('크로와상', '3')","('치아바타', '3')","('음악', '3')"
3,"('조용하다', '8')","('깨끗하다', '5')","('깔끔하다', '4')","('쾌적하다', '3')","('대화', '3')","('위치', '2')","('청결하다', '2')"
4,"('스콘', '6')","('깔끔하다', '6')","('인테리어', '4')","('편하다', '3')","('예쁘다', '3')","('넓다', '3')","('디저트', '3')"
...,...,...,...,...,...,...,...
775,"('다양하다', '11')","('샐러드', '7')","('청결하다', '5')","('케잌', '5')","('넓다', '4')","('신선하다', '4')","('빵집', '4')"
776,"('아이스크림', '8')","('예쁘다', '4')","('기다리다', '2')","('케이크', '2')","('다양하다', '2')","('와플', '2')","('깨끗하다', '2')"
777,"('젤라또', '25')","('아이스크림', '24')","('아이', '5')","('비싸다', '3')","('넓다', '2')","('쾌적하다', '2')","('층', '2')"
778,"('식빵', '6')","('치아바타', '5')","('비싸다', '5')","('빵집', '4')","('지나가다', '3')","('깔끔하다', '3')","('피자', '3')"
779,"('서울역', '29')","('기다리다', '6')","('쉬다', '5')","('청결하다', '4')","('간단하다', '4')","('편하다', '4')","('아메리카노', '3')"

In [ ]:
classify

,no.,[0]브런치/식사,[1]커피,[2]차,[3]디저트,[4]비건,[5]공부/개인작업/업무,[6]팀플/회의/스터디,[7]대모임,[8]대화/수다,...,[10]할아버지/할머니,[11]파티,[12]휴식,[13]sns/핫플,[14]테마,TOP1,TOP2,TOP3,TOP4,TOP5
0,0,95,4,0,3,0,15,12,32,16,...,-13,19,205,218,0,"('sns/핫플', 218)","('휴식', 205)","('브런치/식사', 95)","('대모임', 32)","('파티', 19)"
1,1,0,1,1,0,0,4,1,-14,2,...,5,-14,4,3,0,"('할아버지/할머니', 5)","('공부/개인작업/업무(1인)', 4)","('휴식', 4)","('sns/핫플', 3)","('대화/수다', 2)"
2,2,13,4,2,0,0,1,0,6,1,...,1,2,-2,8,0,"('브런치/식사', 13)","('sns/핫플', 8)","('대모임', 6)","('커피', 4)","('차', 2)"
3,3,1,0,1,0,0,13,5,-38,12,...,15,-38,10,1,0,"('할아버지/할머니', 15)","('공부/개인작업/업무(1인)', 13)","('대화/수다', 12)","('휴식', 10)","('아이', 7)"
4,4,1,0,0,5,0,9,4,13,8,...,13,-1,25,21,2,"('휴식', 25)","('sns/핫플', 21)","('대모임', 13)","('할아버지/할머니', 13)","('공부/개인작업/업무(1인)', 9)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,19,0,0,1,0,5,5,0,3,...,10,2,0,3,0,"('브런치/식사', 19)","('할아버지/할머니', 10)","('아이', 8)","('공부/개인작업/업무(1인)', 5)","('팀플/회의/스터디', 5)"
776,776,0,0,0,1,0,2,3,-4,2,...,3,7,-2,10,0,"('sns/핫플', 10)","('아이', 8)","('파티', 7)","('팀플/회의/스터디', 3)","('할아버지/할머니', 3)"
777,777,1,0,0,0,0,7,-2,9,1,...,0,2,-4,3,0,"('아이', 26)","('대모임', 9)","('공부/개인작업/업무(1인)', 7)","('sns/핫플', 3)","('파티', 2)"
778,778,17,0,0,2,0,3,1,-3,1,...,5,-3,2,4,0,"('브런치/식사', 17)","('할아버지/할머니', 5)","('아이', 4)","('sns/핫플', 4)","('공부/개인작업/업무(1인)', 3)"
779,779,11,3,0,1,0,2,21,-24,5,...,6,8,8,12,0,"('팀플/회의/스터디', 21)","('sns/핫플', 12)","('브런치/식사', 11)","('파티', 8)","('휴식', 8)"

In [ ]:
classify.columns

Index(['no.', '[0]브런치/식사', '[1]커피', '[2]차', '[3]디저트', '[4]비건', '[5]공부/개인작업/업무',
       '[6]팀플/회의/스터디', '[7]대모임', '[8]대화/수다', '[9]아이', '[10]할아버지/할머니', '[11]파티',
       '[12]휴식', '[13]sns/핫플', '[14]테마', 'TOP1', 'TOP2', 'TOP3', 'TOP4',
       'TOP5'],
      dtype='object')

In [ ]:
col = ['[0]브런치/식사', '[1]커피', '[2]차', '[3]디저트', '[4]비건', '[5]공부/개인작업/업무',
       '[6]팀플/회의/스터디', '[7]대모임', '[8]대화/수다', '[9]아이', '[10]할아버지/할머니', '[11]파티',
       '[12]휴식', '[13]sns/핫플', '[14]테마']

In [ ]:
full

,Unnamed: 0.1,Unnamed: 0,data-cid,카카오 id,카페명_x,네이버주소,분류,naver_url,review_count,카페명_y,lng(x),lat(y)
0,0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,르플뢰브,126.945801,37.535276
1,1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,커피공장103 이촌점,126.954935,37.526261
2,2,2,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,테이블스 용산점,126.955187,37.532618
3,3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,이디야커피 용산원효점,126.951642,37.532505
4,4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,카페로찌,126.952272,37.533069
...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,775,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,파리바게뜨 한남점,127.006148,37.533367
776,776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,배스킨라빈스 한남점,127.005521,37.533197
777,777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,빨라쪼델프레도 HQ점,126.973638,37.540711
778,778,778,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,베이커스코드 숙대입구점,126.971670,37.542075
779,779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179",던킨 서울역2호점,126.970484,37.549118

In [ ]:
info

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Column1,cafe,단체석,주차,포장,예약,배달,무선 인터넷,반려동물 동반,남/녀 화장실 구분,장애인 편의시설,방문접수/출장,콘센트,테라스
0,0,0,0,0,마포역 근처일 시: 지하철 도보시 마포역 4번 출구로 나와서 왼쪽으로 백다방을 지나...,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
1,1,1,1,1,이촌2동 주민센터 옆\n삼보아파트 2층\n영업 종료10:30에 영업 시작10시 30...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,2,2,자가용 이용시: 강변북로-->원효대교 북단-->전자상가방향에서 유턴\n버스 이용시:...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
3,3,3,3,3,영업 중21:20에 라스트오더21시 20분에 라스트오더펼쳐보기06/03-06/11 ...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,4,4,4,4,영업 중21:50에 라스트오더21시 50분에 라스트오더펼쳐보기\n02-706-403...,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,775,775,775,영업 중24:00에 영업 종료0시 0분에 영업 종료펼쳐보기\n02-798-0012복...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,776,776,776,776,영업 중23:00에 영업 종료23시 0분에 영업 종료펼쳐보기\n02-749-3868...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,777,777,777,777,영업 종료10:00에 영업 시작10시 0분에 영업 시작펼쳐보기\n02-709-782...,1.0,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN
778,778,778,778,778,영업 종료내일 휴무내일 휴무펼쳐보기\n02-717-9010복사\n가격표 사진을 올려...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
779,779,779,779,779,서울 용산구 청파로 378 철도청14공항경의중앙서울역 3번 출구에서300m\n토요일...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
price

,Unnamed: 0,no.,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count,americano_full,latte_full,americano,latte
0,0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,"['아메리카노', '6,500원']",NaN,"6,500",NaN
1,1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,"['아메리카노', '3,500원']","['카페라떼(HOT)', '4,000']","3,500","4,000"
2,3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,"['카페 아메리카노', '3,200원']","['카페 라떼', '4,200원']","3,200","4,200"
3,4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,"['아메리카노', '3,000원']","['카페라떼', '3,500원']","3,000","3,500"
4,5,5,1912771394,1.030741e+08,루트카페,서울 용산구 원효로19길 18 1층 ROOT카페,"카페,디저트",https://pcmap.place.naver.com/restaurant/19127...,149,"['아메리카노', '3,000원']",NaN,"3,000",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,773,773,37769824,2.685204e+07,폴바셋 한남 커피스테이션점,서울 용산구 한남대로 48,카페,https://pcmap.place.naver.com/restaurant/37769...,"1,238",NaN,"['카페라떼 (Standard)', '5,700원']",NaN,"5,700"
560,774,774,18184715,8.123978e+06,파리크라상 한남점,서울 용산구 독서당로 78 청화빌딩,베이커리,https://pcmap.place.naver.com/restaurant/18184...,696,"['아메리카노', '4,300원']","['카페라떼', '4,800원']","4,300","4,800"
561,776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,"['콜드브루 아메리카노', '3,800원']",NaN,"3,800",NaN
562,777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,"['아메리카노', '3,200원']","['카페라떼', '3,700원']","3,200","3,700"
563,779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179","['아메리카노', '4,100원']",NaN,"4,100",NaN

In [ ]:
full.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'data-cid', '카카오 id', '카페명_x', '네이버주소',
       '분류', 'naver_url', 'review_count', '카페명_y', 'lng(x)', 'lat(y)'],
      dtype='object')

In [ ]:
col = ['Unnamed: 0', 'data-cid', '카카오 id', '카페명_x', '네이버주소',
       '분류', 'naver_url', 'review_count', 'lng(x)', 'lat(y)']

In [ ]:
full = full[col]

In [ ]:
full

,Unnamed: 0,data-cid,카카오 id,카페명_x,네이버주소,분류,naver_url,review_count,lng(x),lat(y)
0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276
1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261
2,2,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618
3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505
4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069
...,...,...,...,...,...,...,...,...,...,...
775,775,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,127.006148,37.533367
776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,127.005521,37.533197
777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,126.973638,37.540711
778,778,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,126.971670,37.542075
779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179",126.970484,37.549118

In [ ]:
info.columns

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'Column1', 'cafe', '단체석',
       '주차', '포장', '예약', '배달', '무선 인터넷', '반려동물 동반', '남/녀 화장실 구분', '장애인 편의시설',
       '방문접수/출장', '콘센트', '테라스'],
      dtype='object')

In [ ]:
col = ['Unnamed: 0', '단체석',
       '주차', '포장', '예약', '배달', '무선 인터넷', '반려동물 동반', '남/녀 화장실 구분', '장애인 편의시설',
       '방문접수/출장', '콘센트', '테라스']

In [ ]:
info = info[col]

In [ ]:
info

,Unnamed: 0,단체석,주차,포장,예약,배달,무선 인터넷,반려동물 동반,남/녀 화장실 구분,장애인 편의시설,방문접수/출장,콘센트,테라스
0,0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
1,1,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
3,3,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,4,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,776,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,777,1.0,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN
778,778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
779,779,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
price.columns

Index(['Unnamed: 0', 'no.', 'data-cid', '카카오 id', '카페명', '네이버주소', '분류',
       'naver_url', 'review_count', 'americano_full', 'latte_full',
       'americano', 'latte'],
      dtype='object')

In [ ]:
col = ['Unnamed: 0', 'americano_full', 'latte_full',
       'americano', 'latte']

In [ ]:
price = price[col]

In [ ]:
price

,Unnamed: 0,americano_full,latte_full,americano,latte
0,0,"['아메리카노', '6,500원']",NaN,"6,500",NaN
1,1,"['아메리카노', '3,500원']","['카페라떼(HOT)', '4,000']","3,500","4,000"
2,3,"['카페 아메리카노', '3,200원']","['카페 라떼', '4,200원']","3,200","4,200"
3,4,"['아메리카노', '3,000원']","['카페라떼', '3,500원']","3,000","3,500"
4,5,"['아메리카노', '3,000원']",NaN,"3,000",NaN
...,...,...,...,...,...
559,773,NaN,"['카페라떼 (Standard)', '5,700원']",NaN,"5,700"
560,774,"['아메리카노', '4,300원']","['카페라떼', '4,800원']","4,300","4,800"
561,776,"['콜드브루 아메리카노', '3,800원']",NaN,"3,800",NaN
562,777,"['아메리카노', '3,200원']","['카페라떼', '3,700원']","3,200","3,700"
563,779,"['아메리카노', '4,100원']",NaN,"4,100",NaN

In [ ]:
entire = pd.merge(full, info, how='outer',on='Unnamed: 0')

In [ ]:
entire = pd.merge(entire, price, how='outer',on='Unnamed: 0')

In [ ]:
new = pd.concat([entire, hashtags],axis=1)

In [ ]:
entire

,Unnamed: 0,data-cid,카카오 id,카페명_x,네이버주소,분류,naver_url,review_count,lng(x),lat(y),...,반려동물 동반,남/녀 화장실 구분,장애인 편의시설,방문접수/출장,콘센트,테라스,americano_full,latte_full,americano,latte
0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276,...,NaN,1.0,NaN,NaN,NaN,NaN,"['아메리카노', '6,500원']",NaN,"6,500",NaN
1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261,...,NaN,NaN,NaN,NaN,NaN,NaN,"['아메리카노', '3,500원']","['카페라떼(HOT)', '4,000']","3,500","4,000"
2,2,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618,...,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505,...,NaN,NaN,NaN,NaN,1.0,NaN,"['카페 아메리카노', '3,200원']","['카페 라떼', '4,200원']","3,200","4,200"
4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069,...,1.0,1.0,NaN,NaN,NaN,1.0,"['아메리카노', '3,000원']","['카페라떼', '3,500원']","3,000","3,500"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,127.006148,37.533367,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,127.005521,37.533197,...,NaN,NaN,NaN,NaN,NaN,NaN,"['콜드브루 아메리카노', '3,800원']",NaN,"3,800",NaN
777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,126.973638,37.540711,...,NaN,1.0,NaN,NaN,NaN,NaN,"['아메리카노', '3,200원']","['카페라떼', '3,700원']","3,200","3,700"
778,778,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,126.971670,37.542075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179",126.970484,37.549118,...,NaN,1.0,NaN,NaN,NaN,NaN,"['아메리카노', '4,100원']",NaN,"4,100",NaN

In [ ]:
entire.to_csv('/content/drive/MyDrive/Colab/최종파일모음/위치기본가격까지.csv', encoding = 'utf-8-sig')

In [ ]:
new.to_csv('/content/drive/MyDrive/Colab/최종파일모음/위치기본가격해시태그까지.csv', encoding = 'utf-8-sig')

In [ ]:
new

,Unnamed: 0,data-cid,카카오 id,카페명_x,네이버주소,분류,naver_url,review_count,lng(x),lat(y),...,latte_full,americano,latte,TOP1,TOP2,TOP3,TOP4,TOP5,TOP6,TOP7
0,0,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276,...,NaN,"6,500",NaN,"('뷰', '150')","('비싸다', '14')","('브런치', '11')","('예쁘다', '11')","('야경', '9')","('파스타', '7')","('층', '7')"
1,1,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261,...,"['카페라떼(HOT)', '4,000']","3,500","4,000","('조용하다', '3')","('넓다', '1')","('아늑하다', '1')","('파니니', '1')","('다양하다', '1')","('홍차', '1')","('편안하다', '1')"
2,2,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618,...,NaN,NaN,NaN,"('샌드위치', '7')","('과일', '5')","('아메리카노', '4')","('카페라떼', '3')","('크로와상', '3')","('치아바타', '3')","('음악', '3')"
3,3,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505,...,"['카페 라떼', '4,200원']","3,200","4,200","('조용하다', '8')","('깨끗하다', '5')","('깔끔하다', '4')","('쾌적하다', '3')","('대화', '3')","('위치', '2')","('청결하다', '2')"
4,4,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069,...,"['카페라떼', '3,500원']","3,000","3,500","('스콘', '6')","('깔끔하다', '6')","('인테리어', '4')","('편하다', '3')","('예쁘다', '3')","('넓다', '3')","('디저트', '3')"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,127.006148,37.533367,...,NaN,NaN,NaN,"('다양하다', '11')","('샐러드', '7')","('청결하다', '5')","('케잌', '5')","('넓다', '4')","('신선하다', '4')","('빵집', '4')"
776,776,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,127.005521,37.533197,...,NaN,"3,800",NaN,"('아이스크림', '8')","('예쁘다', '4')","('기다리다', '2')","('케이크', '2')","('다양하다', '2')","('와플', '2')","('깨끗하다', '2')"
777,777,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,126.973638,37.540711,...,"['카페라떼', '3,700원']","3,200","3,700","('젤라또', '25')","('아이스크림', '24')","('아이', '5')","('비싸다', '3')","('넓다', '2')","('쾌적하다', '2')","('층', '2')"
778,778,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,126.971670,37.542075,...,NaN,NaN,NaN,"('식빵', '6')","('치아바타', '5')","('비싸다', '5')","('빵집', '4')","('지나가다', '3')","('깔끔하다', '3')","('피자', '3')"
779,779,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179",126.970484,37.549118,...,NaN,"4,100",NaN,"('서울역', '29')","('기다리다', '6')","('쉬다', '5')","('청결하다', '4')","('간단하다', '4')","('편하다', '4')","('아메리카노', '3')"

In [ ]:
#/content/drive/MyDrive/Colab/review_최종_781.csv
#/content/drive/MyDrive/Colab/최종파일모음/classify_0-779_top5(최종).csv

In [ ]:
datacid = pd.read_csv('/content/drive/MyDrive/Colab/review_최종_781.csv', encoding='utf-8-sig')
top = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/classify_0-779_top5(최종).csv', encoding='utf-8-sig')

In [ ]:
datacid

,Unnamed: 0,data-cid,카카오 id,카페명,네이버주소,분류,naver_url,review_count
0,1,1275361497,8.264307e+08,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251
1,2,36877505,2.139356e+07,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48
2,3,37568842,1.904932e+09,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115
3,5,1149649924,1.910404e+09,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237
4,6,37236205,2.405972e+07,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130
...,...,...,...,...,...,...,...,...
775,940,11690056,8.123634e+06,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819
776,941,11782468,2.006503e+09,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371
777,942,31363849,1.305696e+07,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164
778,943,1119858083,2.559310e+08,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76
779,945,11492935,8.257019e+06,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179"

In [ ]:
col = ['data-cid', 'review_count']

In [ ]:
datacid = datacid[col]

In [ ]:
top

,no.,[0]브런치/식사,[1]커피,[2]차,[3]디저트,[4]비건,[5]공부/개인작업/업무,[6]팀플/회의/스터디,[7]대모임,[8]대화/수다,...,[10]할아버지/할머니,[11]파티,[12]휴식,[13]sns/핫플,[14]테마,TOP1,TOP2,TOP3,TOP4,TOP5
0,0,95,4,0,3,0,15,12,32,16,...,-13,19,205,218,0,"('sns/핫플', 218)","('휴식', 205)","('브런치/식사', 95)","('대모임', 32)","('파티', 19)"
1,1,0,1,1,0,0,4,1,-14,2,...,5,-14,4,3,0,"('할아버지/할머니', 5)","('공부/개인작업/업무(1인)', 4)","('휴식', 4)","('sns/핫플', 3)","('대화/수다', 2)"
2,2,13,4,2,0,0,1,0,6,1,...,1,2,-2,8,0,"('브런치/식사', 13)","('sns/핫플', 8)","('대모임', 6)","('커피', 4)","('차', 2)"
3,3,1,0,1,0,0,13,5,-38,12,...,15,-38,10,1,0,"('할아버지/할머니', 15)","('공부/개인작업/업무(1인)', 13)","('대화/수다', 12)","('휴식', 10)","('아이', 7)"
4,4,1,0,0,5,0,9,4,13,8,...,13,-1,25,21,2,"('휴식', 25)","('sns/핫플', 21)","('대모임', 13)","('할아버지/할머니', 13)","('공부/개인작업/업무(1인)', 9)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,19,0,0,1,0,5,5,0,3,...,10,2,0,3,0,"('브런치/식사', 19)","('할아버지/할머니', 10)","('아이', 8)","('공부/개인작업/업무(1인)', 5)","('팀플/회의/스터디', 5)"
776,776,0,0,0,1,0,2,3,-4,2,...,3,7,-2,10,0,"('sns/핫플', 10)","('아이', 8)","('파티', 7)","('팀플/회의/스터디', 3)","('할아버지/할머니', 3)"
777,777,1,0,0,0,0,7,-2,9,1,...,0,2,-4,3,0,"('아이', 26)","('대모임', 9)","('공부/개인작업/업무(1인)', 7)","('sns/핫플', 3)","('파티', 2)"
778,778,17,0,0,2,0,3,1,-3,1,...,5,-3,2,4,0,"('브런치/식사', 17)","('할아버지/할머니', 5)","('아이', 4)","('sns/핫플', 4)","('공부/개인작업/업무(1인)', 3)"
779,779,11,3,0,1,0,2,21,-24,5,...,6,8,8,12,0,"('팀플/회의/스터디', 21)","('sns/핫플', 12)","('브런치/식사', 11)","('파티', 8)","('휴식', 8)"

In [ ]:
entire = pd.merge(entire, price, how='outer',on='Unnamed: 0')

In [ ]:
new = pd.concat([datacid, top],axis=1)

In [ ]:
new

,data-cid,review_count,no.,[0]브런치/식사,[1]커피,[2]차,[3]디저트,[4]비건,[5]공부/개인작업/업무,[6]팀플/회의/스터디,...,[10]할아버지/할머니,[11]파티,[12]휴식,[13]sns/핫플,[14]테마,TOP1,TOP2,TOP3,TOP4,TOP5
0,1275361497,251,0,95,4,0,3,0,15,12,...,-13,19,205,218,0,"('sns/핫플', 218)","('휴식', 205)","('브런치/식사', 95)","('대모임', 32)","('파티', 19)"
1,36877505,48,1,0,1,1,0,0,4,1,...,5,-14,4,3,0,"('할아버지/할머니', 5)","('공부/개인작업/업무(1인)', 4)","('휴식', 4)","('sns/핫플', 3)","('대화/수다', 2)"
2,37568842,115,2,13,4,2,0,0,1,0,...,1,2,-2,8,0,"('브런치/식사', 13)","('sns/핫플', 8)","('대모임', 6)","('커피', 4)","('차', 2)"
3,1149649924,237,3,1,0,1,0,0,13,5,...,15,-38,10,1,0,"('할아버지/할머니', 15)","('공부/개인작업/업무(1인)', 13)","('대화/수다', 12)","('휴식', 10)","('아이', 7)"
4,37236205,130,4,1,0,0,5,0,9,4,...,13,-1,25,21,2,"('휴식', 25)","('sns/핫플', 21)","('대모임', 13)","('할아버지/할머니', 13)","('공부/개인작업/업무(1인)', 9)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,11690056,819,775,19,0,0,1,0,5,5,...,10,2,0,3,0,"('브런치/식사', 19)","('할아버지/할머니', 10)","('아이', 8)","('공부/개인작업/업무(1인)', 5)","('팀플/회의/스터디', 5)"
776,11782468,371,776,0,0,0,1,0,2,3,...,3,7,-2,10,0,"('sns/핫플', 10)","('아이', 8)","('파티', 7)","('팀플/회의/스터디', 3)","('할아버지/할머니', 3)"
777,31363849,164,777,1,0,0,0,0,7,-2,...,0,2,-4,3,0,"('아이', 26)","('대모임', 9)","('공부/개인작업/업무(1인)', 7)","('sns/핫플', 3)","('파티', 2)"
778,1119858083,76,778,17,0,0,2,0,3,1,...,5,-3,2,4,0,"('브런치/식사', 17)","('할아버지/할머니', 5)","('아이', 4)","('sns/핫플', 4)","('공부/개인작업/업무(1인)', 3)"
779,11492935,"2,179",779,11,3,0,1,0,2,21,...,6,8,8,12,0,"('팀플/회의/스터디', 21)","('sns/핫플', 12)","('브런치/식사', 11)","('파티', 8)","('휴식', 8)"

In [ ]:
new.columns

Index(['data-cid', 'review_count', 'no.', '[0]브런치/식사', '[1]커피', '[2]차',
       '[3]디저트', '[4]비건', '[5]공부/개인작업/업무', '[6]팀플/회의/스터디', '[7]대모임',
       '[8]대화/수다', '[9]아이', '[10]할아버지/할머니', '[11]파티', '[12]휴식', '[13]sns/핫플',
       '[14]테마', 'TOP1', 'TOP2', 'TOP3', 'TOP4', 'TOP5'],
      dtype='object')

In [ ]:
col = ['no.', 'data-cid', '[0]브런치/식사', '[1]커피', '[2]차',
       '[3]디저트', '[4]비건', '[5]공부/개인작업/업무', '[6]팀플/회의/스터디', '[7]대모임',
       '[8]대화/수다', '[9]아이', '[10]할아버지/할머니', '[11]파티', '[12]휴식', '[13]sns/핫플',
       '[14]테마']

In [ ]:
new.columns = ['Unnamed: 0', 'data-cid', 'brunch', 'coffee', 'tea',
       'dessert', 'vegan', 'work', 'team', 'large',
       'chat', 'child', 'senior', 'party', 'rest', 'sns',
       'theme']

In [ ]:
new = new[col]

KeyError: ignored

In [ ]:
new

,Unnamed: 0,data-cid,brunch,coffee,tea,dessert,vegan,work,team,large,chat,child,senior,party,rest,sns,theme
0,0,1275361497,95,4,0,3,0,15,12,32,16,12,-13,19,205,218,0
1,1,36877505,0,1,1,0,0,4,1,-14,2,0,5,-14,4,3,0
2,2,37568842,13,4,2,0,0,1,0,6,1,1,1,2,-2,8,0
3,3,1149649924,1,0,1,0,0,13,5,-38,12,7,15,-38,10,1,0
4,4,37236205,1,0,0,5,0,9,4,13,8,9,13,-1,25,21,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,11690056,19,0,0,1,0,5,5,0,3,8,10,2,0,3,0
776,776,11782468,0,0,0,1,0,2,3,-4,2,8,3,7,-2,10,0
777,777,31363849,1,0,0,0,0,7,-2,9,1,26,0,2,-4,3,0
778,778,1119858083,17,0,0,2,0,3,1,-3,1,4,5,-3,2,4,0
779,779,11492935,11,3,0,1,0,2,21,-24,5,7,6,8,8,12,0

In [ ]:
new.to_csv('/content/drive/MyDrive/Colab/최종파일모음/classify.csv', encoding='utf-8-sig')

In [ ]:
datacid = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/cafe.csv', header=0, encoding='utf-8-sig')
# menu = pd.read_csv('/content/drive/MyDrive/Colab/최종파일모음/yongsangu_menu.csv', encoding='utf-8-sig')

In [ ]:
menu

,data-cid,kakao-id,카페명,네이버 메뉴,카카오 메뉴
0,1275361497,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]+Sheet1!",NaN
1,36877505,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,37568842,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,1985101469,9.910023e+08,24시무인셀프카페 원효로점,"[{'핫아메리카노': '1,700원'}, {'뚱카롱': '2,500원'}, {'마카...","[{'아메리카노': '1,700'}, {'카페라떼': '2,500'}, {'핫초코'..."
4,1149649924,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
...,...,...,...,...,...
1069,11782468,2.006503e+09,배스킨라빈스 한남점,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파..."
1070,31363849,1.305696e+07,빨라쪼델프레도 HQ점,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN
1071,1119858083,2.559310e+08,베이커스코드 숙대입구점,[],[]
1072,1126198061,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN
1073,11492935,8.257019e+06,던킨 서울역2호점,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400..."

In [ ]:
menu.columns

Index(['data-cid', 'kakao-id', '카페명', '네이버 메뉴', '카카오 메뉴'], dtype='object')

In [ ]:
col = ['data-cid', '네이버 메뉴', '카카오 메뉴']

In [ ]:
datacid

,Unnamed: 0.1,Unnamed: 0,data-cid,카페명,네이버주소,분류,naver_url,review_count,lng(x),lat(y),...,TOP2,TOP2_count,TOP3,TOP3_count,TOP4,TOP4_count,TOP5,TOP5_count,TOP6,TOP6_count
0,0,0,1275361497,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276,...,비싸다,14.0,브런치,11,예쁘다,11.0,야경,9.0,파스타,7.0
1,1,1,36877505,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261,...,넓다,1.0,아늑하다,1,파니니,1.0,다양하다,1.0,홍차,1.0
2,2,2,37568842,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618,...,과일,5.0,아메리카노,4,카페라떼,3.0,크로와상,3.0,치아바타,3.0
3,3,3,1149649924,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505,...,깨끗하다,5.0,깔끔하다,4,쾌적하다,3.0,대화,3.0,위치,2.0
4,4,4,37236205,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069,...,깔끔하다,6.0,인테리어,4,편하다,3.0,예쁘다,3.0,넓다,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,775,11690056,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,127.006148,37.533367,...,샐러드,7.0,청결하다,5,케잌,5.0,넓다,4.0,신선하다,4.0
776,776,776,11782468,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,127.005521,37.533197,...,예쁘다,4.0,기다리다,2,케이크,2.0,다양하다,2.0,와플,2.0
777,777,777,31363849,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,126.973638,37.540711,...,아이스크림,24.0,아이,5,비싸다,3.0,넓다,2.0,쾌적하다,2.0
778,778,778,1119858083,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,126.971670,37.542075,...,치아바타,5.0,비싸다,5,빵집,4.0,지나가다,3.0,깔끔하다,3.0
779,779,779,11492935,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179",126.970484,37.549118,...,기다리다,6.0,쉬다,5,청결하다,4.0,간단하다,4.0,편하다,4.0

In [ ]:
entire = pd.merge(datacid, menu, how='outer',on='data-cid')

In [ ]:
entire

,Unnamed: 0.1,Unnamed: 0,data-cid,카페명_x,네이버주소,분류,naver_url,review_count,lng(x),lat(y),...,TOP4,TOP4_count,TOP5,TOP5_count,TOP6,TOP6_count,kakao-id,카페명_y,네이버 메뉴,카카오 메뉴
0,0.0,0.0,1275361497,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276,...,예쁘다,11.0,야경,9.0,파스타,7.0,8.264307e+08,르플뢰브,"[{'아메리카노': '6,500원'}]+Sheet1!",NaN
1,1.0,1.0,36877505,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261,...,파니니,1.0,다양하다,1.0,홍차,1.0,2.139356e+07,커피공장103 이촌점,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,2.0,2.0,37568842,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618,...,카페라떼,3.0,크로와상,3.0,치아바타,3.0,1.904932e+09,테이블스 용산점,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,3.0,3.0,1149649924,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505,...,쾌적하다,3.0,대화,3.0,위치,2.0,1.910404e+09,이디야커피 용산원효점,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
4,4.0,4.0,37236205,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069,...,편하다,3.0,예쁘다,3.0,넓다,3.0,2.405972e+07,카페로찌,"[{'에스프레소': '3,000원'}, {'아메리카노': '3,000원'}, {'카...","[{'에스프레소': '3,000'}, {'아메리카노': '3,000'}, {'카페라..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069,NaN,NaN,19923981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.000593e+09,북카페 청마루,[],[]
1070,NaN,NaN,1676574304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEGINTIXIX,"[{'에스프레소': '4,600원'}, {'아메리카노': '4,600원'}, {'라...",[]
1071,NaN,NaN,1496827922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.136631e+07,행복플러스가게,[],[]
1072,NaN,NaN,37264311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.271084e+07,라온에스,"[{'게임비 시간당': '3,000원'}]",[]
1073,NaN,NaN,1126198061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.683265e+07,앤티앤스 서울역점,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN

Warning: Total number of columns (39) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
entire.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'data-cid', '카페명_x', '네이버주소', '분류',
       'naver_url', 'review_count', 'lng(x)', 'lat(y)', '단체석', '주차', '포장',
       '예약', '배달', '무선 인터넷', '반려동물 동반', '남/녀 화장실 구분', '장애인 편의시설', '콘센트', '테라스',
       'americano', 'latte', 'TOP1', 'TOP1_count', 'TOP2', 'TOP2_count',
       'TOP3', 'TOP3_count', 'TOP4', 'TOP4_count', 'TOP5', 'TOP5_count',
       'TOP6', 'TOP6_count', 'kakao-id', '카페명_y', '네이버 메뉴', '카카오 메뉴'],
      dtype='object')

In [ ]:
col = ['Unnamed: 0', 'data-cid', '카페명_x', '네이버주소', '분류',
       'naver_url', 'review_count', 'lng(x)', 'lat(y)', '단체석', '주차', '포장',
       '예약', '배달', '무선 인터넷', '반려동물 동반', '남/녀 화장실 구분', '장애인 편의시설', '콘센트', '테라스',
       'americano', 'latte', 'TOP1', 'TOP1_count', 'TOP2', 'TOP2_count',
       'TOP3', 'TOP3_count', 'TOP4', 'TOP4_count', 'TOP5', 'TOP5_count',
       'TOP6', 'TOP6_count', '네이버 메뉴', '카카오 메뉴']

In [ ]:
entire = entire[col]

In [ ]:
entire

,Unnamed: 0,data-cid,카페명_x,네이버주소,분류,naver_url,review_count,lng(x),lat(y),단체석,...,TOP3,TOP3_count,TOP4,TOP4_count,TOP5,TOP5_count,TOP6,TOP6_count,네이버 메뉴,카카오 메뉴
0,0.0,1275361497,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276,1.0,...,브런치,11,예쁘다,11.0,야경,9.0,파스타,7.0,"[{'아메리카노': '6,500원'}]+Sheet1!",NaN
1,1.0,36877505,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261,NaN,...,아늑하다,1,파니니,1.0,다양하다,1.0,홍차,1.0,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,2.0,37568842,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618,1.0,...,아메리카노,4,카페라떼,3.0,크로와상,3.0,치아바타,3.0,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,3.0,1149649924,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505,NaN,...,깔끔하다,4,쾌적하다,3.0,대화,3.0,위치,2.0,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
4,4.0,37236205,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069,1.0,...,인테리어,4,편하다,3.0,예쁘다,3.0,넓다,3.0,"[{'에스프레소': '3,000원'}, {'아메리카노': '3,000원'}, {'카...","[{'에스프레소': '3,000'}, {'아메리카노': '3,000'}, {'카페라..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069,NaN,19923981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[]
1070,NaN,1676574304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'에스프레소': '4,600원'}, {'아메리카노': '4,600원'}, {'라...",[]
1071,NaN,1496827922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[]
1072,NaN,37264311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'게임비 시간당': '3,000원'}]",[]
1073,NaN,1126198061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'(아몬드)크림치즈스틱': '5,400원'}, {'(할라피뇨,블랙페퍼)치즈핫도그...",NaN

In [ ]:
entire.columns = ['Unnamed: 0', 'data-cid', '카페명', '네이버주소', '분류',
       'naver_url', 'review_count', 'lng(x)', 'lat(y)', '단체석', '주차', '포장',
       '예약', '배달', '무선 인터넷', '반려동물 동반', '남/녀 화장실 구분', '장애인 편의시설', '콘센트', '테라스',
       'americano', 'latte', 'TOP1', 'TOP1_count', 'TOP2', 'TOP2_count',
       'TOP3', 'TOP3_count', 'TOP4', 'TOP4_count', 'TOP5', 'TOP5_count',
       'TOP6', 'TOP6_count', '네이버 메뉴', '카카오 메뉴']

In [ ]:
entire

,Unnamed: 0,data-cid,카페명,네이버주소,분류,naver_url,review_count,lng(x),lat(y),단체석,...,TOP2,TOP2_count,TOP3,TOP3_count,TOP4,TOP4_count,TOP5,TOP5_count,TOP6,TOP6_count
0,0,1275361497,르플뢰브,서울 용산구 원효로1길 20 르플뢰브,브런치,https://pcmap.place.naver.com/restaurant/12753...,251,126.945801,37.535276,1.0,...,브런치,11,예쁘다,11.0,야경,9.0,파스타,7.0,"[{'아메리카노': '6,500원'}]+Sheet1!",NaN
1,1,36877505,커피공장103 이촌점,서울 용산구 이촌로18길 16 삼보아파트 2층,"카페,디저트",https://pcmap.place.naver.com/restaurant/36877...,48,126.954935,37.526261,NaN,...,아늑하다,1,파니니,1.0,다양하다,1.0,홍차,1.0,"[{'아메리카노': '3,500원'}, {'(원두)하우스블렌드': '5,000원'}]","[{'에스프레소': '3,500'}, {'아메리카노(HOT)': '3,500'}, ..."
2,2,37568842,테이블스 용산점,서울 용산구 원효로 103-3,베이커리,https://pcmap.place.naver.com/restaurant/37568...,115,126.955187,37.532618,1.0,...,아메리카노,4,카페라떼,3.0,크로와상,3.0,치아바타,3.0,"[{'아인슈페너': '5,000원'}, {'초코큐브파운드': '3,500원'}, {...",[]
3,3,1149649924,이디야커피 용산원효점,서울 용산구 원효로 70,카페,https://pcmap.place.naver.com/restaurant/11496...,237,126.951642,37.532505,NaN,...,깔끔하다,4,쾌적하다,3.0,대화,3.0,위치,2.0,"[{'카페 아메리카노': '3,200원'}, {'카페 라떼': '4,200원'}, ...",NaN
4,4,37236205,카페로찌,서울 용산구 원효로19길 7 1층,"카페,디저트",https://pcmap.place.naver.com/restaurant/37236...,130,126.952272,37.533069,1.0,...,인테리어,4,편하다,3.0,예쁘다,3.0,넓다,3.0,"[{'에스프레소': '3,000원'}, {'아메리카노': '3,000원'}, {'카...","[{'에스프레소': '3,000'}, {'아메리카노': '3,000'}, {'카페라..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,775,11690056,파리바게뜨 한남점,서울 용산구 대사관로 73,베이커리,https://pcmap.place.naver.com/restaurant/11690...,819,127.006148,37.533367,NaN,...,청결하다,5,케잌,5.0,넓다,4.0,신선하다,4.0,"[{'프랑보아즈무즈': '20,000원'}, {'블루베리 치즈무스': '19,000...",[]
776,776,11782468,배스킨라빈스 한남점,서울 용산구 대사관로 68 1층,아이스크림,https://pcmap.place.naver.com/restaurant/11782...,371,127.005521,37.533197,NaN,...,기다리다,2,케이크,2.0,다양하다,2.0,와플,2.0,"[{'파인트': '8,900원'}, {'쿼터': '17,000원'}, {'패밀리':...","[{'옹기종기팩': '26,500'}, {'아빠왔다팩': '13,500'}, {'파..."
777,777,31363849,빨라쪼델프레도 HQ점,서울 용산구 한강대로72길 3 해태제과 1층,아이스크림,https://pcmap.place.naver.com/restaurant/31363...,164,126.973638,37.540711,1.0,...,아이,5,비싸다,3.0,넓다,2.0,쾌적하다,2.0,"[{'꼬빠 삐꼴라(1가지맛)(컵or콘)': '4,500원'}, {'꼬빠 메디아(2가...",NaN
778,778,1119858083,베이커스코드 숙대입구점,서울 용산구 한강대로77길 18,베이커리,https://pcmap.place.naver.com/restaurant/11198...,76,126.971670,37.542075,NaN,...,비싸다,5,빵집,4.0,지나가다,3.0,깔끔하다,3.0,[],[]
779,779,11492935,던킨 서울역2호점,서울 용산구 청파로 378 철도청,도넛,https://pcmap.place.naver.com/restaurant/11492...,"2,179",126.970484,37.549118,NaN,...,쉬다,5,청결하다,4.0,간단하다,4.0,편하다,4.0,"[{'아메리카노': '4,100원'}]","[{'올스타 도넛세트': '15,800'}, {'버라이어티 10팩': '18,400..."

Warning: Total number of columns (36) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
entire.to_csv('/content/drive/MyDrive/Colab/최종파일모음/cafemenu.csv', encoding='utf-8-sig')